### ISSUE TITLE
[1.4.0 Beta 1] White flash : Midi instrument parameters

### ISSUE THREAD

**Issue by acidf2018** [polyend/TrackerIssues#1008]
On the page : Midi instrument parameters
When you change the CC , the screen turns white

To reproduce the problem: choose CC E, turn the jog wheel

The problem occurs every time

**Comment by dimatura** [comment]
Happens for me as well.

**Comment by eholzbach** [comment]
@ambv This should be re-opened. The issue persists in 1.4.0 beta 2. I can reproduce it by scrolling through CC E and F menus. After a few go's the screen will go solid white if I scroll all the way up.
