### ISSUE TITLE
'Favorites' Hotkeys

### ISSUE THREAD

**Issue by 0x0zzz** [polyend/TrackerIssues#1011]
My suggestion is to use the 8 black keys beneath the screen as Favorites hotkeys.  The user would have 16 favorites each for Note, Instrument, FX1, and FX2.  Holding the Key, Instrument, FX1, or FX2 key and then tapping the corresponding black key would select Favorite 1-8, and holding Shift while doing so would select 9-16. 

Favorites could be set by:
holding Note/etc key > scrolling to the desired slot with the jog wheel > holding the desired black key for two or three seconds (Shift rules apply).

I would immediately use this to set the MIDI channels to my Instrument Favorites.  Switching between Instruments in the 1-48 bank and the MIDI channels can get a little awkward, especially if you do it frequently.

**Comment by tomhayes** [comment]
+1 for this - would also minimise excessive jogwheel scrolling when switching to MIDI instruments etc, which is something I am quite concerned about given people's jogwheel issues.

**Comment by 0x0zzz** [comment]
I've been cheating that a little by holding the Instrument key, tapping the bottom-right-most pad to jump to slot 48, and then using arrow-down into the channels.

**Comment by tomhayes** [comment]
Thanks, that's an awesome tip!
