### ISSUE TITLE
"Play Thru"/Continuous Slice Mode

### ISSUE THREAD

**Issue by tomhayes** [polyend/TrackerIssues#1012]
Currently, when we slice a sample, playing back each slice plays from that slice's marker and stops when it hits the marker of the next slice. 

It would be absolutely awesome if we had a mode where slices would play from their respective marker through to the end of the sample (or as far as it can whilst the note is on) instead of stopping when it reaches the next marker. 

This is possible in Renoise with the little 1> button at the top right of the slicing screen, as an example of what I'm talking about.

**Comment by ketumatek** [comment]
Good ideas + In Renoise the first slice it use to play the all sample...
That will be nice fracture two..
Because sometimes you need to play the entire sample and for this you need to copy sample in another slot...

**Comment by gherat** [comment]
I've asked this a long time ago, still no update on that. It is really lame that the sample stops at the end of the slice.. The sliceponts should be like a start point: "play sample from here". Then you should be able to let it stop by a gate/step time, which plays it back like: [ 1/32th ]    [ 1/16th ]     [ 1/8th ]     [ 1/1 ]     [ 2/1 ] They have the gate time fx now in the new firmware but that only plays the slice shorter :( Like 50%, 25% etc. It should also go up like 200%, 800% etc

**Comment by dramaone** [comment]
this... standard requirement well before games

**Comment by danapeks** [comment]
+1 on this one, really needed for samplists.
Already made a precious feature request for this and there are a few more. See #461 and #254 etc
