### ISSUE TITLE
[1.4.0b1] Tempo counter resets when trying to tap out a tempo slower than ~150bpm

### ISSUE THREAD

**Issue by Justplanecrazy** [polyend/TrackerIssues#1013]
I'm unable to tap out slower tempos in the new beta. (<150 bpm) In Song mode, the tempo counter will recognize the first 1-2 taps but resets the counter before the 3rd and 4th can be entered.

Steps to reproduce:
1. Start a new project
2. Go to the Song page
3. Try to tap a fairly slow tempo on the rightmost "soft" button (90 bpm)
4. Note the tempo counter recognizes the first 1-2 taps but resets before the 3rd and 4th can be entered. This causes the tempo to remain unchanged.
5. Try tapping out a fairly fast tempo (160 bpm)
6. Note that the tempo counter counts up as expected, then changes the current tempo.

Bug only appears to be present in 1.4.0b1, was unable to reproduce in 1.3.1.

Bug happens every time.

**Comment by math0ne** [comment]
I am also experiencing this issue
