### ISSUE TITLE
please! midi implementation for "instrument parameters" !

### ISSUE THREAD

**Issue by PaulAntioche** [polyend/TrackerIssues#1018]
Would it be possible to finally have a midi implementation for "instrument parameters" and "position" for Granular and wavetable.
For the active instrument ...
This is essential.

**Comment by loktez** [comment]
For all separate instruments Kermit man (ah aha ah) ?

**Comment by PaulAntioche** [comment]
for the selected instrument !
Kermit man?

**Comment by loktez** [comment]
"Kermut" sorry i'm out, i was thinking you was some one from Swiss...

**Comment by PaulAntioche** [comment]
> "Kermut" sorry i'm out, i was thinking you was some one from Swiss...

yes!

**Comment by PaulAntioche** [comment]
zut! I accidentally closed
