### ISSUE TITLE
Real time song editing

### ISSUE THREAD

**Issue by tfspsound** [polyend/TrackerIssues#1022]
I don’t know if this is possible but I think it would be useful if there was an edit mode we could go into when the song is playing whereby we could select a pattern from the song as it plays and edit it without the pattern on display changing as the song progresses. 

[edit] maybe I didn’t mean real time, maybe editing during live play.

**Comment by UserOverflow** [comment]
The same issue here. I would to use it as in other sequencers to change for example beat (add new notes) while playing in loop.

**Comment by doelman** [comment]
Also in desperate need for this, would really be a game changer to be able
to implement ideas on the fly while jamming /performing

**Comment by ketumatek** [comment]
What could be great too is the possibility to play all your sample with the grid pad in song mode.
Yet I could only play one sample I select ...

But like in pattern mode use instruments position in song mode will be very useful for jam, creation and live performance.
