### ISSUE TITLE
[1.4.1b] short cut sample editor and other

### ISSUE THREAD

**Issue by ketumatek** [polyend/TrackerIssues#1025]
It could be nice to have a short cut to go directly at the end of the sample and go back to the beginning just with one button and not with the jog wheel.

Using for example END button (screen key) + HOME button or SHIFT + HOME button
And same execution when you are at the end and you want to go back to the beginning.

It will take less of time.
And it can be apply in sample editor, sample playback and maybe instruments parameters.

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
