### ISSUE TITLE
What about "relative" applied LFO function

### ISSUE THREAD

**Issue by SoundRider007** [polyend/TrackerIssues#1070]
## Hi, we're excited to hear your idea!
Tracker OS 1.3.1
### A new feature

On instrument screen 1 and screen 2 we can set and automate the "volume". The volume-LFO seems to work in Triangle-mode absolute between 0 and 1 and is "multiplied" with the setting on screen 1. 

I would love to have it implemented in a later OS version that we can select to have LFOs work relatively from the settings on screen 1. What I mean is that the LFOs add/subtract from a given setting and create small variations from the baseline setting only instead of riding the values between 0 to max. 

This would provide a great option to apply the small fluctuations to the sounds, which most synthesizer user use to get an "organic" behaviour of sounds.

**Comment by tfspsound** [comment]
I can’t tell how the lfo works on PT but it does seem difficult to use it subtly. Setting it to 1 can have a huge effect and a setting of 70 doesn’t sound too different from 100 (particularly when set to sample position.)
