### ISSUE TITLE
Saving instruments preset

### ISSUE THREAD

**Issue by CarloAvanti** [polyend/TrackerIssues#1080]
It would be a great feature to save instruments preset, to share between different project or even between different people. We could work on sound libraries specific for the tracker.
Or at least would be great to have the possibility to copy/paste Instruments parameters from/to different instruments.

**Comment by anemlife** [comment]
You can already copy instruments + their parameters in the sample loader (use the copy/paste buttons). 
What you can't do is loading an instrument from another project

**Comment by CarloAvanti** [comment]
Yes, and this is very useful, but in this case would be better to have the possibility to copy just one or more instruments parameter without coping the sample, for example, pressing REC in Instruments Parameters could let us select one or more parameters and copy/paste them to another instruments. That would be fun !

**Comment by anemlife** [comment]
Got it, this could bring some new workflows yeah :)

**Comment by zandergrin** [comment]
+1

**Comment by bambrose** [comment]
Yes I realised this several times as a request. Single most obvious omission currently I think

**Comment by MattWilsh** [comment]
+1

This is something I'd really like, and know a couple of other owner who would love this.

**Comment by bambrose** [comment]
Single most important outstanding feature I think

**Comment by Jacknametrouble** [comment]
This has been added in the newest 1.5b1 beta.
