### ISSUE TITLE
Another send effect for chorus

### ISSUE THREAD

**Issue by CarloAvanti** [polyend/TrackerIssues#1081]
It would be great to have some more send fx, something like a chorus (would be great to help the stereo image), a phaser or a flanger.

**Comment by anemlife** [comment]
Definitely, a Phaser/Flanger would be really great! Especially for glitchy percs

The Sample Editor ones are not really intuitive as you need to find the "sweet" spots, then render, retry, etc... A "live" solution would be really welcome

**Comment by k4ot** [comment]
yes please, live phaser and flanger
not rendered in sample. phaser written in the sample = phaser that never changes = useless phaser

"imagine dub music with same phase at each skank sample, it's very cool"  said no one ever

**Comment by Jacknametrouble** [comment]
Thank you for your feedback, this won't be possible due to the limited resources.
