### ISSUE TITLE
[1.1.17] Loud "pop" sound when selecting Sample Recorder

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#109]
Turn on Tracker, push "Sample Recorder". A loud "pop" sound will be heard.

### Other important information

* How often does this bug happen? (every time)

* Does this bug happen in previous firmware versions? (haven't tested)

* Does this bug happen in every project? (yes)

**Comment by ArtFluids** [comment]
I can confirm this one too, but I just figured it wasn't a big deal
