### ISSUE TITLE
[1.4.0.b1] pattern length tweak all tracks regardless of the selected track

### ISSUE THREAD

**Issue by loktez** [polyend/TrackerIssues#1093]
When I engage a Pattern Length value in performance FX mode, regardless of the selected track (track 1 or track 4 or another or both for example), all other tracks are subject to the pattern length value (while they are not selected). It seems that this problem only appeared on this version 1.4.0.b1. My best

**Comment by sunfallz** [comment]
As far as I know, pattern length fx has always been locked to all tracks, from the get go. Individual pattern lengths is not a feature. It was the 1st thing I noticed when I got the tracker, and my 1st feature request, which has yet to be enabled.
