### ISSUE TITLE
Tracker freezing due to grounding / static electricity

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#110]
A weird thing happened today, I touched Tracker while working and transferred static electricity to its metal case. Tracker's screen froze to blur and hopefully after a restart it was still working. Maybe grounding the metal case somehow in the next hardware batch, if possible?

**Comment by Jacknametrouble** [comment]
The coming 1.1.18 firmware will bring a fix to this issue.

**Comment by piotr3500** [comment]
Of course, it is grounded.
How do you power your Tracker?

**Comment by MegaTurrican** [comment]
At the time the static electricity thing happened, I was powering it from the official power supply. Now I am working from a brick to see if it will happen again.
