### ISSUE TITLE
Output noise

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#111]
I checked Tracker's output noise and found out that when on Line in - Monitor On there is additional noise produced, even with no source attached (see pic). Also the machine produces some noise while idle (check pic) which disappears if you turn the Master Volume at 0.  

![line in - monitor on](https://user-images.githubusercontent.com/71126897/94694844-ef714b80-033d-11eb-8841-eeed2ff24347.png)
![master volume 100](https://user-images.githubusercontent.com/71126897/94694851-f13b0f00-033d-11eb-84c9-9354a079e4f9.png)

**Comment by piotr3500** [comment]
It happens only when there is no signal fed into line in.
