### ISSUE TITLE
[1.4.0b2] Track Mixer visuals stutter & lag

### ISSUE THREAD

**Issue by trutypesounds** [polyend/TrackerIssues#1110]
### Steps to reproduce

play track, go to pattern, go to track mixer, hold shift - see mixer visuals stutter and lag

### Attachments and links

https://user-images.githubusercontent.com/17484006/122684467-3249bb00-d20e-11eb-81b0-ee3cd4db91c4.MOV

**Comment by trutypesounds** [comment]
this is still occurs on 1.4.1b1, less lag but noticable

**Comment by Jacknametrouble** [comment]
Fixed in firmware v1.5.0
