### ISSUE TITLE
Various (simple but useful) FX suggestions

### ISSUE THREAD

**Issue by prds100** [polyend/TrackerIssues#1130]
Not asking for the impossible, rather some simple FX commands that I think would be pretty easy to implement?

ADSR - Adjust the AMP envelope
LFO Amount - Seems odd this isnt here already
Reverb DELAY parameters - Ability to adjust Delay time, reverb size as an FX

**Comment by Jacknametrouble** [comment]
Thank you for your feedback, this won't be possible due to the limited resources.
