### ISSUE TITLE
[1.4.0b2] Out of sync tracks

### ISSUE THREAD

**Issue by pigeonsky** [polyend/TrackerIssues#1133]
Tracks go out of sync if previous pattern isnt a  "normal" 4/4 bar i.e. 16, 32, 64 etc step sequence. 

### Steps to reproduce
Example - Make one pattern in 4/4 e.g. 32. Have next pattern set to a length of 37 steps (this is example, use any length that isn't 4/4). Play pattern of 37 step and then the 32 step. The 32 step pattern will be out of sync.

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

### Other important information

* How often does this bug happen? every time

* Does this bug happen in previous firmware versions?
* haven't tried

* Does this bug happen in every project?
Yes, in current firmware.

**Comment by ambv** [comment]
Do the tracks go out of sync in Song mode or on the Perform screen?
