### ISSUE TITLE
Configuration option for MIDI/TRS output type

### ISSUE THREAD

**Issue by bastilian** [polyend/TrackerIssues#1139]
The Polyend tracker follows the Type-B standard over mini jack, the Type-A (which seems to become the standard), differs only in having the output/input of tip and sleeve flipped.

Would it be possible to add an option to the MIDI config section to be able and choose what type it should use?

**Comment by Jacknametrouble** [comment]
As far as I know, this is a hardware choice, not a configurable option.

**Comment by bastilian** [comment]
Too bad. I was thinking that it might be possible to at least reroute the signals within the firmware and expose a setting for that in the MIDI configuration options.
