### ISSUE TITLE
1.0.4b Tracker very slow when plugged in pc

### ISSUE THREAD

**Issue by Obliviousfre** [polyend/TrackerIssues#1141]
Hi,

I upgraded to version 1.0.4b and noticed that the device is behaving very slowly when plugging it into the pc for power.
Every action takes a few seconds to complete (like scrolling in the pattern view).

It didn't happen in previous versions.

Thanks!

**Comment by Jacknametrouble** [comment]
Make sure you're powering your tracker properly. When underpowered may behave funky.
