### ISSUE TITLE
[1.3.1] Audio silenced after edits

### ISSUE THREAD

**Issue by dirtysampling** [polyend/TrackerIssues#1165]
This is really strange behaviour. After I do any edit on track or pattern or instrument when I press preview, play/start or C2 pad to play audio I have a second or so of silence. On second press all is back to normal, until next edit. See videos. 

https://user-images.githubusercontent.com/86979723/126489053-6b82c39a-f8a2-4c0c-87cf-fecaae6d0f01.MOV

https://user-images.githubusercontent.com/86979723/126489058-7118886f-2d6a-4d2e-a372-c837fbf59daa.MOV

**Comment by Jacknametrouble** [comment]
This is a dedicated pad display for beat slice instruments. These are some manual basics. Please refer to the manual instead of posting at Github.
