### ISSUE TITLE
[1.3.1] Rendered audio not saved?

### ISSUE THREAD

**Issue by dirtysampling** [polyend/TrackerIssues#1166]
Ok I don't get this. I managed to use Render Selection without the unit freezing (by selecting only a few steps intsead of all tracks), when I hit Render Selection, I create a name, and then? Where the heck do I find my rendered audio? Sure it is not in the 'recordings' folder, nor in the 'samples' folder. So where????

**Comment by Jacknametrouble** [comment]
Find your selection renders in the Export folder.
