### ISSUE TITLE
[1.4.0b3] Buttons unresponsive after Update

### ISSUE THREAD

**Issue by dirtysampling** [polyend/TrackerIssues#1167]
OK, I've upgraded to 1.4.0b3 (as recommended by tech support bcz I was having issues with 1.3.1, and now all buttons are unresponsive. The data wheel works and lest me scroll through the track of the current project/pattern, but nothing else work. I did a reboot with the reset button, and it flashed 1.2.0, and stalled with counter 100. Not finishing the install. 
Did an on/off, then reflashed 1.3.1, and all went fine.

**Comment by Jacknametrouble** [comment]
As mentioned in the beta Testing Pre-release Builds of the Tracker firmware:
https://github.com/polyend/TrackerIssues/blob/master/HOWTO_BETA_FIRMWARE.md


When anything like this freeze happens, the irst and simplest action to try is to disconnect the USB C cable connector from its port on the back panel of the instrument. This usually helps.
 
Please get back to 1.4.0b3 as it's a big improvement in regard to 1.3.1 (check the changelogs).
