### ISSUE TITLE
[v1.4.0 b1] Can't send MIDI to some Devices

### ISSUE THREAD

**Issue by 77377** [polyend/TrackerIssues#1177]
### Steps to reproduce

I tried to hook up my Digitone to Tracker, but neither notes nor Transport are received despite both Devices being correctly configured. There's nothing wrong with Digitone, I can slave the unit to other machines without any problem whatsoever. 

It's not a faulty midi cable either, I tried several. 

It doesn't affect all Elektron gear though, hooking up a Model Cycles is no problem at all.

Is this a polarity issue? 

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

Consistent! Whatever I do, those Devices don't talk to eachother

* Does this bug happen in previous firmware versions?
Yes

* Does this bug happen in every project?

Yes

**Comment by bignutemporium1** [comment]
Hey 77377,

I know this is closed but did you make sure that you are using a 3.5mm - 5 DIN **type B MIDI**?
