### ISSUE TITLE
[1.1.17] audio stops working in sample loader

### ISSUE THREAD

**Issue by cclcng** [polyend/TrackerIssues#118]
### Steps 
I had just started a new project and began to load samples into instruments, and after previewing 8-10 wavs, the audio cut out, but the tracker wasn’t frozen, as I could reach the different modules etc.
In the pattern module, I could start playback of the pattern but even if I loaded an instrument, it would not playback. I reset config after this, and nothing happened so I rebooted. When I rebooted, I was able to again get preview audio, but once I loaded an instrument I could not play the pads for example, on the sample playback menu. Nothing would happen. So I went to my computer and deleted the workspace folder, and reloaded the card on the tracker, but when I went to the sample loader, I had audio for the first 8 or so wavs, and then it cut out, with the same behaviour as before (including working play-pattern) yet no sound from the previously loaded instrument ... 
thinking about reinstalling the firmware and seeing what that does...

**Comment by cclcng** [comment]
The bug happens every time now. I hadn’t had this  issue since 1.1.15, but it only happened sporadically with that build , and was resolved by 17 (initially, at least).
It happens with every project, but since I had to format my SD last revision, I  lost my old projects, so can’t check with those, only new ones.

**Comment by cclcng** [comment]
I’ll add that , upon restart, the sample loader preview works temporarily, but nothing happens when hitting the pads in sample playback mode

**Comment by cclcng** [comment]
also, the pads do not work in the save as... module either.

**Comment by cclcng** [comment]
Reinstalling the 17 firmware did not resolve the pad issue.

**Comment by Jacknametrouble** [comment]
From the 1.1.17 Changelog:
Sample Preview from the pads in the Sample Loader was causing unit freeze and was removed. Same in Sample Editor but only when an Fx is chosen for a preview.

> also, the pads do not work in the save as... module either.

Do you mean that you cannot enter letters in order to name the project?

**Comment by cclcng** [comment]
> From the 1.1.17 Changelog:
> Sample Preview from the pads in the Sample Loader was causing unit freeze and was removed. Same in Sample Editor but only when an Fx is chosen for a preview.
> 
> > also, the pads do not work in the save as... module either.
> 
> Do you mean that you cannot enter letters in order to name the project?

Correct. And they do not work in the playback module or pattern either.. 

I was able to restore functionality  with an emergency update  to 1.1.17 using the polyend tool.

**Comment by Jacknametrouble** [comment]
Thank you for the update. Are you refering to Pattern screen view by the "playback module"?

**Comment by cclcng** [comment]
Thank you for the update. Are you refering to Pattern screen view by the "playback module"?

Yes , the pads do not work in the pattern screen, playback screen or even the file>save as... menu after the sound stops within the sample loader screen

**Comment by pandamaschine** [comment]
same problem for me

**Comment by HakkahFR** [comment]
Same problem, and big big problem

**Comment by piotr3500** [comment]
Guys, can you send a video showing when the problems occur?
We have a hard time reproducing the bug.

**Comment by HakkahFR** [comment]
The problem didn't happend for me since 2 days now. Very strange

**Comment by pandamaschine** [comment]
the problem happened very randomly , it's very difficult to reproduce it :)
in some time when it happened , on sample loader , I preview very fast several samples in a row.

**Comment by cclcng** [comment]
I had some luck  with no crashing for a little bit after I did an emergency flash (to 1.1.17) with the polyend tool, and for some time was not able to reproduce it. But now it is back. I will link to the specific samples that it happens with consistently.  To reproduce this error, I would navigate to the folder of waveforms linked below, and hold the preview key whilst  taping the down arrow to scroll. Sometimes I have to use the up arrow after scrolling with tge down arrow to reproduce. Also, any combination of holding the preview button, alternately tapping up/down,  and turning the jog wheel intermittently seems to cause this issue. 

Here are the waveforms that I was previewing: 

https://waveeditonline.com/wav-files.zip

Best,

**Comment by piotr3500** [comment]
@cclcng thanks for the package

I managed to replicate it on 1.1.17.
Have zero issues with that on 1.1.18 (out very soon).

**Comment by cclcng** [comment]
I’m happy you were able to see this !! I cannot reproduce this with other folders of samples it seems 🤬
