### ISSUE TITLE
1.4.0 b3 Missing File transfer menu in Config

### ISSUE THREAD

**Issue by Aisjam** [polyend/TrackerIssues#1185]
Spotted while testing new beta. tried with multiple tested usb on windows and File transfer menu still didn't popup for windows pc. 

### Steps to reproduce

Connect to PC
Config > File transfer

**Comment by acidf2018** [comment]
"MTP file transfer functionality is disabled until further notice due to reliability issues with the supporting third-party library; we're sorry for the inconvenience"

https://github.com/polyend/TrackerIssues/releases/tag/1.4.0b3

**Comment by Aisjam** [comment]
Cheers for that acid, should off had a look at the beta 3 notes :(. I'll mark it as closed
