### ISSUE TITLE
Assign Sidechain Compression to Individual Tracks 

### ISSUE THREAD

**Issue by Goldfasan** [polyend/TrackerIssues#1190]
Dear Polyend Team,
I love your product...

I am suggesting an option to be able to assign the sidechain compression to one or multiple destinations . 
For example:

Master 1/3 > Limiter > Sidechain > Destination  (Selection: a single track or multiple tracks)
or
Track Mixer 2/3 > Track1 Sidechain on/off, Track 2 Sidechain on/off, and so on...
or 
Perform 2/2 > Sidechain assign to Track...

Currently the sidechain compression effects the entire mix except the "line in" signal. My second suggestion is to add the option to apply sidechaining to the "line in" signal as well.

Thank you, can't wait to read your feedback.

**Comment by frognerboy** [comment]
Great idea!
