### ISSUE TITLE
[Firmware version] Bug title

### ISSUE THREAD

**Issue by vampi1068** [polyend/TrackerIssues#1198]
Hi 
I am having a serious problem with my tracker, since stopped playing any kind of sound, when I plug in the headphones I hear only a constant and stunned click. the problem is with all outputs, including MIDI out.
I have the latest firewire but I already tried going back to the old firewire and that didn't help.
I hope someone can help me, greetings from Argentina

**Comment by Jacknametrouble** [comment]
Sounds like a hardware issue (audio codec). Polyend customer support can be reached here > https://help.polyend.com/submit_ticket

You may like to reach out to your retailer in order to open up an RMA procedure.
