### ISSUE TITLE
New Buttons!

### ISSUE THREAD

**Issue by djr005** [polyend/TrackerIssues#120]
## Hi, we're excited to hear your idea!

Before you start, did you check whether your feature was already requested?
Searching might save you quite a bit of time here.

### A new feature

Where and when can we purchase the new buttons ? 
I have the original ones and would like to update.

Cheers

**Comment by Jacknametrouble** [comment]
This was a hardware design change not a cosmetic one. These are not user interchangeable nor available for purchase.

**Comment by djr005** [comment]
So why were they changed ?

**Comment by Jacknametrouble** [comment]
The ones used in the first batch have become unavailable.
