### ISSUE TITLE
MIDI Instruments Page

### ISSUE THREAD

**Issue by grodriUMD** [polyend/TrackerIssues#1214]
The quickest way I've found to switch between samples is by hitting the pads while holding the instrument selector button. The problem is the MIDI OUT instruments are all outside of that range, so I have to select the last pad, wait for the menu to scroll to Inst 48, then go down manually to the MIDI channel I'm looking for. 

I would love to be able to double tap the instrument selector and have it switch pages so all 16 MIDI channels can be seen laid out on the pads. Otherwise it is very tedious to switch between MIDI channels when sequencing external gear

**Comment by arphex** [comment]
since we are on the MIDI Instr page, wouuld be great if there could be custom names for the cc msgs at least on that page
