### ISSUE TITLE
External audio input always on

### ISSUE THREAD

**Issue by HakkahFR** [polyend/TrackerIssues#122]
Is this possible ? I mean you have an external synth and can't heard the sound of it in the tracker, oO' ?

**Comment by ambv** [comment]
This is not currently possible.

**Comment by HakkahFR** [comment]
Ok thanks for answer, znd the implementation of a metronome during record?

Le lun. 19 oct. 2020 à 13:48, Łukasz Langa <notifications@github.com> a
écrit :

**Comment by ambv** [comment]
If you wish to see this, please report a separate issue.

**Comment by jaap3** [comment]
I think this is the same as #57 and should now be possible with firmware version 1.3.0

**Comment by Jacknametrouble** [comment]
Audio input monitoring is available since firmware version 1.3.0
