### ISSUE TITLE
sampling / recording / dumping NES music and sounds

### ISSUE THREAD

**Issue by patois** [polyend/TrackerIssues#1221]
Hey there!
I like the NES emulator and I would love to be able to sample/record/dump game music and sound into the sample recorder even more! Do you think it'd be feasible to implement this feature? Please upvote if you think this is a useful feature.

Thank you

**Comment by Jacknametrouble** [comment]
Emulator and audio engine are two separate things, can't do two at the same time.

**Comment by patois** [comment]
Yet, the Nofrendo emulator being open source, it could be modified so it would dump sounds to the SD card but I understand it's probably not the highest priority on your list of feature requests ;)
