### ISSUE TITLE
Old Impulse Tracker (.it) files do not import correctly. Must be re-saved in schism.

### ISSUE THREAD

**Issue by antf4rm** [polyend/TrackerIssues#1227]
I have written thousands of (.it) files with Impulse Tracker.

I've found that when tying to import these files, the sample data becomes corrupted and turns to noise.

There must be some discrepancy from the original (.it) files to the schism (.it) files causing the import to fail.

If I open the old (.it) file in schism and re-save it as a new (.it) file in a new folder, the mod seems to import as expected.

**Comment by Jacknametrouble** [comment]
Note: The .mod file import is still under development and its functionality should be improved.
