### ISSUE TITLE
[1.4.0] Part of the "Additional Info" bar clears when moving from - and then back to - the pattern screen

### ISSUE THREAD

**Issue by Anexium** [polyend/TrackerIssues#1230]
This is a really minor UI bug and the workaround is really simple.  I just thought I'd log it so there's a record of it.

### Steps to reproduce

If 'Config -> General -> Pattern Top Info' is set to 'Additional Info' then the current instrument name or FX is shown in the top right-hand corner of the pattern window.

When you move to another screen (Song, Sample Editor, etc) and then back to the Pattern screen then the information that was displayed in the top right-hand corner is gone.

If you change the Instrument or press one of the FX buttons then this information is returned.

The pattern number (top left-hand side), playing time and position (both top centre) are unaffected - it is just the info at the top right-hand side that disappears when you return to the pattern window.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
Every time

* Does this bug happen in previous firmware versions?
I believe that this 'Additional Info' bar is new functionality for version 1.4.0

* Does this bug happen in every project?
Yes.

**Comment by Jacknametrouble** [comment]
@ambv
