### ISSUE TITLE
[1.4.0] Copy/paste from song mode not reliable

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#1249]
If you copy/paste multiple patterns at once it behaves strange (sometimes it works sometimes not). Same if you press undo it doesn't go to the last state, it only undo certains patterns and make you lose other ones. (also works randomly)

**Comment by MortalJS** [comment]
Hi @anemlife. I am trying to replicate your problem. Unfortunately without success. At the moment I can't forward it to the developers department.

**Comment by anemlife** [comment]
Hi,

After a few try I understood what's happening so it's actually not a bug. 

If I copy/paste let's say 3 lanes at once and hit undo, it will first undo the third copied bar, then the second, then the first.
I thought it would undo the whole 3 lanes at once. But I got it now, closing this issue, thanks!
