### ISSUE TITLE
[1.4.0] Sidechain issue

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#1250]
After editing a sample, sidechain lose its source "connexion". I have to go and move the "attack" cursor and the "threshold" one to make it catch the source again.

This bug is present since a lot of firmwares and I already opened a ticket long time ago about it but it's still not working so I want to catch developper's attention about this point.

**Comment by trutypesounds** [comment]
yes, confirmed, bug is still in 1.4.0 @ambv

**Comment by MortalJS** [comment]
@ambv 
Bug confirmed. 
As in the description.
