### ISSUE TITLE
[1.4.0] Render selection bug

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#1251]
Sometimes it only render a few step and not the full steps selection. If you don't check what's been rendered you might lose some things. (also it happens randomly, did 3 tries with the same selection of 80 steps it finally worked the third time while at first it was only recording about 60 steps).

**Comment by bambrose** [comment]
Yeah I've seen this behaviour too
It all relates to where in the grid the elements are.
What it likes is elements in column 1,2,3
If events are in 2,3 or 1,4 or something it doesn't work.
I'd been meaning to raise a ticket

**Comment by orbitfold** [comment]
Yep, happens all the time

**Comment by trutypesounds** [comment]
mentioned here #1162

i have the same issue (1.4.0 fw)
