### ISSUE TITLE
Support more than 100 projects

### ISSUE THREAD

**Issue by imehesz** [polyend/TrackerIssues#1255]
## Hi, we're excited to hear your idea!

The Tracker is currently limited to only 100 projects. I know this limitation is mentioned in the manual, but it would be a great improvement as there is no useful workaround.

See the original bug ticket for more details.
https://github.com/polyend/TrackerIssues/issues/1253

### A new feature

Please tell us about your feature in as much detail as you can provide.
Vague ideas are less likely to be successful.  Concrete requests are
easier to estimate.

It is pretty obvious, but please support more than 100 projects.

**Comment by Jacknametrouble** [comment]
That's one of the limitations brought by the initial assumptions, which may be unfortunate, but hey, we're still learning. On the other hand, do you use 100 or more projects at the same time? Just copy some to another location and move them back to the SD when needed, as adviced.
