### ISSUE TITLE
[1.4.0] MIDI output inconsistent/buggy

### ISSUE THREAD

**Issue by tfspsound** [polyend/TrackerIssues#1263]
I set up a new project. Connected my midi keyboard to midi in with the supplied trs adapter and the midi out with another trs type b adapter to my laptop through a midi to USB adapter.
 I found as I played on the keyboard notes would be missed out entirely despite registering a trigger on the midi to usb device. Sometimes the wrong note would be played. I recorded into the track to see if that would make a difference but found I got similar results from playing it back but there was no real pattern to it that I could make out. 
 I tested the midi keyboard and midi to usb device by replacing the tracker with a qy70 which worked perfectly. I can’t test the type b trs adapter because I don’t have any other instruments that require it, however it is brand new and I’d suspect if it didn’t work it wouldn’t work at all. 
 I haven’t tried this on earlier firmwares or projects as I don’t often use the tracker like this. 
 Cheers

**Comment by MortalJS** [comment]
Hi @tfspsound . I am trying to reproduce your problem. In my configuration I used. Arturia keystep>MIDI cable +original Polyend adapter> Tracker >Original Polyend adapter +Midi cable+ original Micromonsta 2 adapter> Micromonsta 2.

**Comment by tfspsound** [comment]
Hey @MortalJS 
Thanks for taking time to try it. Here’s a video of the issue

https://user-images.githubusercontent.com/73538421/141360019-0e3c359b-7632-4952-9028-cbca783ef3f5.MOV

As you can see it misses notes out, plays one note 17 semitones lower than it’s supposed, sometimes it sustains notes. 

Unfortunately I don’t have an interface with midi connection but this is a problem with the tracker not the usb midi device as the old qy70 has no troubles with it. 

Thanks for looking into it.

**Comment by MortalJS** [comment]
Hello @tfspsound 

 Unfortunately I cannot approve this bug at this time.
Problems with midi>usb converters happen quite often which you can check on many forums. If you can, try to borrow audio interface with midi output for testing.

**Comment by tfspsound** [comment]
Hi @MortalJS 

Ok, if you can’t replicate it and nobody else seems to be experiencing this issue I guess it would be difficult to work on. 
Im not sure which forum I’d have to check to get this to work it’s only a cheap midi>usb converter, that said the qy70 seems to work without issue. I have also used the same device to flash the OS into an elektron machinedrum in the past without issue. Both these machines are over 20 years old and I suspect the midi >usb is old too so maybe it’s an old midi meets new midi issue?
I don’t know anyone with an audio interface with midi to test this so I’m afraid I can’t test further.
