### ISSUE TITLE
[v1.4.0] Sample preview in sample recorder is distorted.

### ISSUE THREAD

**Issue by antf4rm** [polyend/TrackerIssues#1267]
### Steps to reproduce

Record sample from radio. Preview sample.

Sample sounds overloaded and distorted on preview on sample recorder page. However, when the sample is loaded into the the session it is free of errors.

**Comment by Gareth-Dawson** [comment]
To add a little more info here. 

If I'm working on a track and have lowered the bitrate under the Instrument Parameters for sample (X). 

I then go to the Sample Loader and go to add a new sample (Y). When previewing sample (Y) it previews with the reduced bitrate that I had applied to sample (X).
