### ISSUE TITLE
[1.4.0] Line in will stay mono even when changed to stereo

### ISSUE THREAD

**Issue by sebpmtl** [polyend/TrackerIssues#1269]
Line in is inconsistent. It sometimes stay in mono and will produce weird clipping sounds. I don't know how to explain the frequency. It's like with all the bugs with this machine. It will sometimes do it, sometimes not. You can reflash the firmware and it will be fine or not...

**Comment by MortalJS** [comment]
Hi @sebpmtl. I'm trying to reproduce your problem. I use an external 12 voice synthesizer (with stereo output) for this. Everything works according to the selected function. Can you describe what kind of signal you are putting into the line in?

**Comment by Jacknametrouble** [comment]
https://help.polyend.com/797585-Can-audio-be-passed-through-from-line-in-straight-to-output-in-Tracker
