### ISSUE TITLE
[1.1.17] perform mode (global mode) don't save the two last colomns preset

### ISSUE THREAD

**Issue by pandamaschine** [polyend/TrackerIssues#127]
In perform mode , (global mode) , when you adjust each preset , the last right two colomns preset didn't stay registered when you reboot.

* How often does this bug happen? (every time, often, "it only happened once")

every time

* Does this bug happen in previous firmware versions?

in all prévious versions

* Does this bug happen in every project?

yes

**Comment by Jacknametrouble** [comment]
As far as I remember this is already fixed in the soon coming v1.1.18
