### ISSUE TITLE
snip internal section of audio in sample editor

### ISSUE THREAD

**Issue by barda123** [polyend/TrackerIssues#1273]
So, I think it would be really useful to be able to remove an internal part of the sample i.e. snip out the section of the sample from start->end and concatenate the remaining two segments. kinda the opposite of cropping (which removes audio outside the selected area of the sample).

**Comment by k4ot** [comment]
also #1113

**Comment by tfspsound** [comment]
Also #1170 and #1194 are related. Would be great to see this as a future addition.

**Comment by Jacknametrouble** [comment]
Cropping sample from the SD card in the Sample loaded is available since 1.3 firmware.
