### ISSUE TITLE
[1.4. official] TSTP command makes song stem export not working

### ISSUE THREAD

**Issue by DJTonton** [polyend/TrackerIssues#1276]
### Steps to reproduce

If TSTP command is used (eg to stop external MIDI drum machine) then the song stem export fails (hangs on process, if cancelled, no wav files are in the relevant folder)

This happened with a certain project. Deleting TSTP command cured the issue (song stem export ok).

**Comment by MortalJS** [comment]
@ambv 
Bug confirmed.

TSTP command stop stems export process. The device still works and you can use the cancel option.
