### ISSUE TITLE
[1.4.0] Fast rolls volume increase between pattern start/end

### ISSUE THREAD

**Issue by 60pfennig** [polyend/TrackerIssues#1280]
### Steps to reproduce
-New Project
-Take short sample
-set note on last step in pattern
-apply RV12 on note
-set cut/fade on step 2 of pattern

--> You get extrem volume increase. If you do the same for example with note on step 3 and fade on step 5 it fades without volume increase

### Attachments and links

![20211107_155135](https://user-images.githubusercontent.com/22796753/140650342-e61a9636-983a-421f-b318-28309c72cfd4.jpg)

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
Everytime
* Does this bug happen in previous firmware versions?
Dont know
* Does this bug happen in every project?
Think so

**Comment by MortalJS** [comment]
@ambv 
Bug confirmed.

@60pfennig Thank you for the clear description and the attached image. It always speeds up the process of verifying the problem and reproducing it.
