### ISSUE TITLE
Apple air pods support?

### ISSUE THREAD

**Issue by Casaelastic** [polyend/TrackerIssues#1284]
Hi,

not sure if this is even possible, but could it be possible somehow to use apple air pods with the tracker?

Thanks

**Comment by talktogreg** [comment]
Tracker doesn't have built in bluetooth. You'd need a self powered transmitter dongle via headphone jack. Also note that the lag may a problem, especially with cheaper bluetooth dongles. AirPods also use the AAC audio codec, which can be tricky to find a transmitter for (they'll fallback to SSB - single-sideband, but this would sound woefully and have awful lag)
