### ISSUE TITLE
[Firmware 1.4] The default velocity is undocumented in the manual

### ISSUE THREAD

**Issue by jarkk0sakkinen** [polyend/TrackerIssues#1287]
The manual for the firmware 1.4 does not document the default velocity, i.e. when you do not explicitly use the **V**-effect.

**Comment by Jacknametrouble** [comment]
V - Velocity sets the Velocity of an Instrument from 0% to 100%. When V is not specified, the default velocity set in Instrument Parameters is used.

**Comment by jarkkojs** [comment]
What does 0% and 100% mean exactly? Instrument volume is measured in dB's, i.e. how do you define **f(v): V -> dB**?

**Comment by jarkkojs** [comment]
There is bunch of other parts in the UI where I'm a bit lost when it comes to meaning of the parameters. E.g. I neither have any idea what do value ranges mean in the  master reverb and delay.
