### ISSUE TITLE
Enhancement: Polyrhytm; END FX

### ISSUE THREAD

**Issue by michaalhell** [polyend/TrackerIssues#1293]
On the Nerdseq tracker sequencer you use an END FX to end a tracks sequence looping it back to its first position or jumping to the next sequence.  using this on different positions on different tracks creates polyrhytm. 

I suggest an added per track FX which ends a tracks sequence and loops it back to the start position. having this effect affecting only the track the FX is on would create polyrhythms.

**Comment by fleewortep** [comment]
also i would like to see an addition of independent track length for each 8 tracks
