### ISSUE TITLE
The ability to disable pattern follow

### ISSUE THREAD

**Issue by demolen** [polyend/TrackerIssues#1294]
It would be quite pleasing to be able to disable the pattern follow completely. As with the current version: 1.4.0 the pattern follow automatically disables as you enter step editing mode. But in playback mode, it's not possible to disable it. 

This makes the tracker quite hard to use with people with epilepsy, as it can trigger attacks and some other problems.

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
