### ISSUE TITLE
factory SD card file transfer to computer, hangs bad on projects folder

### ISSUE THREAD

**Issue by thumperjack** [polyend/TrackerIssues#1298]
### Steps to reproduce

copying factory content from 16GB sd card to computer, so i can put factory content back on a 128GB sd card, when the file transfer gets to the projects folder it hangs really really bad

### Attachments and links

![tracker transfer slow](https://user-images.githubusercontent.com/95144333/144521196-b115a1a2-826a-466b-8ba1-2e3f8d766485.png)

* How often does this bug happen? (every time, often, "it only happened once")

the other folders went pretty fast, the projects folder hangs on something. windows 10 pro, thinkpad P71 (as maxed out as they get)

**Comment by Jacknametrouble** [comment]
This rather indicates an issue with the file system on your SD card. Just download the SD content here > official SD card content.
