### ISSUE TITLE
User changeable color theme

### ISSUE THREAD

**Issue by moshier1** [polyend/TrackerIssues#1305]
See title. The default theme is gross.

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.

**Comment by bambrose** [comment]
I disagree about teh current theme (I really like it in fact)
But as someone who looks at typography all day I do find the innumerable font sizes a bit odd.
to my eyes it would look a lot better if there was basically one font and as few font sizes as possible..
In the preferences menu for example the headings are 1-2 pt bigger than the options within.. which looks weird.

**Comment by trutypesounds** [comment]
> See title. The default theme is gross.

check the new one, you'll like it ahhahaha
![photo_2021-12-24_14-58-03](https://user-images.githubusercontent.com/17484006/147351267-9927532e-9117-4b3d-af59-cc392e8896c6.jpg)
![photo_2021-12-24_14-57-56](https://user-images.githubusercontent.com/17484006/147351296-0d0a22c6-546e-4d46-8134-0ba799ede418.jpg)
![photo_2021-12-24_14-57-52](https://user-images.githubusercontent.com/17484006/147351324-163e7632-4220-4d45-8eb2-a0f6c28162d2.jpg)

**Comment by trutypesounds** [comment]
user customizable theme yes please +1

**Comment by moshier1** [comment]
> > See title. The default theme is gross.
> 
> check the new one, you'll like it ahhahaha ![photo_2021-12-24_14-58-03](https://user-images.githubusercontent.com/17484006/147351267-9927532e-9117-4b3d-af59-cc392e8896c6.jpg) ![photo_2021-12-24_14-57-56](https://user-images.githubusercontent.com/17484006/147351296-0d0a22c6-546e-4d46-8134-0ba799ede418.jpg) ![photo_2021-12-24_14-57-52](https://user-images.githubusercontent.com/17484006/147351324-163e7632-4220-4d45-8eb2-a0f6c28162d2.jpg)
I hate light themes and I love it. finally gonna b able to use the tacker outside come summer
