### ISSUE TITLE
[sample playback ]Synced looppoints

### ISSUE THREAD

**Issue by mardlib** [polyend/TrackerIssues#1307]
Hi,
would it be possible to get beatsynced loopoints in the sample playback menue?
Much like the LFO Times menue, you choose a division you like, let’s say 16 and the loop start/endpoint are automatically set to the correct length, then you can change the selection as a whole instead of changing loopstart/end separately.
Thanks!

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
