### ISSUE TITLE
Option to start patterns from the beginning when switching patterns

### ISSUE THREAD

**Issue by mardlib** [polyend/TrackerIssues#1308]
I have a hard time switching patterns with different steplengths, as of now if I switch from a 16 step pattern to a 32 steps pattern, the 32 steps pattern starts from step 16, this can be nice but I’d love to have the option to switch patterns and have them always start from step 1 instead of just picking up wherever the playhead is at this point in time.

**Comment by doelman** [comment]
You can already do that by holding the pattern button and pressing the left
or right arrow button! This will switch to the pattern you've selected once
your current pattern has finished. Good luck.

**Comment by mardlib** [comment]
That’s awesome, thanks for letting me know!
