### ISSUE TITLE
Mono midi recording

### ISSUE THREAD

**Issue by zikajk** [polyend/TrackerIssues#1313]
Hi, i dont usually use live recording as it easily gets messy. Would it be possible to add recording mode where all notes would be forced to only one column - can you add this feature please? It would be great for hihats, mono instruments etc.

**Comment by zikajk** [comment]
I would like to add label but it is not possible from mobile app - should be •enchancement•

**Comment by anemlife** [comment]
press shift + rec in pattern view so you can chose which tracks are armed for recording :) then you simply arm the track you want and disable others

**Comment by zikajk** [comment]
Amazing, I totally missed that, thank you!
