### ISSUE TITLE
Quick Way To Select MIDI Instrument

### ISSUE THREAD

**Issue by SeanHub** [polyend/TrackerIssues#1318]
I use the tracker as the hub behind my music setup, I have multiple MIDI instruments and love performing live.

In order to play a MIDI instrument through tracker you need to select instruments 51 to 66. Could the selection process be made quicker to aid live performance?

Maybe shift + white buttons allows you to select the next numbers higher than 48 for example? Or maybe we can bind a track to a MIDI instrument channel allowing us to quickly switch between the different instruments we have when performing live on the fly!

**Comment by Jacknametrouble** [comment]
Sean, have you tried the Instrument function key hold + jog wheel shortcut for a fast MIDI instrument selection?

**Comment by lucianthorr** [comment]
This might be a closed issue because this feature is new but I just realized you can hold Instrument and press the bottom-right grid button to jump down to Instrument 48.  From there, it's pretty quick to get to the midi channels.
