### ISSUE TITLE
Mono record option

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#132]
When recording in note mode, it would be nice to have the option to limit recording to a single track.
For instance, when playing a melody line, if the line is legato in nature, and played as such, the notes will end up scattered across 2 or sometimes 3 tracks.

Often this behavior seems to be the result of conflict between the new note and the note off event for the previous note. Even playing two successive 16th notes on the same pad will cause the second note to record on a new track.

This could be addressed in a number of ways, but I think a mono record  option which restricts event recording to a single track would be a clean way to implement this, since the record algorithm will not need to guess at the user's intent.

Alternately the ability to designate an instrument as mono/poly would be another equally good approach.

**Comment by Jacknametrouble** [comment]
The track Arming function allows this since 1.3.0.
