### ISSUE TITLE
pattern comp

### ISSUE THREAD

**Issue by thumperjack** [polyend/TrackerIssues#1322]
you can hold down pattern while it's running and switch back and forth between patterns at the sequencer's current location in real time, it's a fun performance method. you can't do that with octatrack or most sequencers, they usually have to get to the end of the pattern

it would be cool if there was a way to capture that performance comp of switching between multiple patterns in real time into a new pattern to chop up and twist around

**Comment by Jacknametrouble** [comment]
This won't be possible.
