### ISSUE TITLE
save/load track

### ISSUE THREAD

**Issue by thumperjack** [polyend/TrackerIssues#1323]
probably a little far fetched, but like in ableton you have clips...you can save the clip and then browse your clips by clicking on them, the browser menu plays what's in the clip, then you can load the clip into the project, and it loads up the track with the midi and samples/instruments/effects to play the clip as saved.

if i've got a track set up with a bunch of hihats, i've got open hat accents and ghost notes and all kinds of volume edits and intricacies, took a good few minutes of jamming to set up the way it like it. "save track" and it saves all that in a "hihats" folder in a "tracks" directory. i could find that complicated hihat track and load it up into any other pattern in another project next time without having to rewrite it or copy/paste it

**Comment by Jacknametrouble** [comment]
Thank you for your feedback. This won't be possible in the exact way you've mentioned. But we're working on something close to this but in another manner. Stay tuned for the coming beta!
