### ISSUE TITLE
Improve Tap-Tempo Behaviour 

### ISSUE THREAD

**Issue by jhrynlds** [polyend/TrackerIssues#134]
Current tap-tempo jumps between multiple values and is imprecise, averaging over 4 taps may improve behaviour allowing to match pattern tempo to sample.

**Comment by mxactvtd** [comment]
Also, sometimes after doing Tap tempo and then trying to change the tempo with the jogwheel or cursor, the value jumps, maybe because the selecton of the parameter might be interpreted as one more TAP, so there needs to be a way of resolving this.

**Comment by Jacknametrouble** [comment]
done
