### ISSUE TITLE
Envelope hold time

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#138]
Currently the only way (that I know of) to get gate times shorter than one step is put a note on the previous step and micromove the note off event to obtain the desired length. This is workable, but having a hold time on the envelope would make this much easier, and also offer another modulation possibility.

**Comment by x2db** [comment]
the CUT available via JOG while entering notes could be enhanced with a few NEW values; Example the **C10** would shorten the gate to 1/10th of a step almost the same way Roll works, or another FX called Gate Length
