### ISSUE TITLE
Absolute need

### ISSUE THREAD

**Issue by HakkahFR** [polyend/TrackerIssues#146]
I wanted to thank the polyend team for the work they do for the tracker and for listening to customers.
 Also I would like to point out that I am absolutely a fan of the tracker and that it is the first machine that I am considering replacing in my computer. 
However there are still points that seriously affect my workflow, which I posted previously but which I recall through this post because I think they are vital to the good functionality of the machine, in addition to the bugs, which are not so common with me. 
It could also be that these features already exist and that I did not understand how to activate them.

 - tuner analyze

 -tune option in instrument automation in addition to finetune

 - sine wave for automation (LFO, ect ..)

 - the possibility to delete the samples from the SD card directly from the sample loader menu 

 -Metronome in the sample recorder

 -possibility to play midi pattern + record audio at a single button in sample recorder, for record in time

 - Auto normalization of samples

I know most of these requests have already been posted but I wanted to support their crucial importance as I have stop most of my current projects due to their absence.
Thank you again very much for your work and see you soon.
(I used google translate so maybe some weird stuff)

**Comment by piotr3500** [comment]
one issue/feature per post, please
it will help organize it all
thanks!
