### ISSUE TITLE
1.1.18 line in no sound until switched to mic and back to line

### ISSUE THREAD

**Issue by theGh0stCat** [polyend/TrackerIssues#152]
### Steps to reproduce

Volume is inaudible for line in until you switch to mic and then back to line in. Volume overrides master and is too loud. Relationship between master and sample volumes doesn’t seem correct either. Switching back to 1.1.17 until fixed as this makes sampling a pain. It was fine in 1.1.17.

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

* Does this bug happen in previous firmware versions?

* Does this bug happen in every project?

**Comment by synthexpert** [comment]
The same happens with radio recording: if you adjust the MASTER VOLUME and go back to sample recorder you cannot hear nothing and have to switch to other input options to make it work. It seems there’s a problem with volume and sample record ...
