### ISSUE TITLE
[1.1.18] The font is different between from and to in the Fill window.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#159]
I don't think this is an important issue, but I will report it.
![F65BD951-1861-4C2C-902B-E971662672DE](https://user-images.githubusercontent.com/45414776/95185729-0ca58e80-0804-11eb-96a3-49d1611e45a4.jpeg)
The frequency is every time.  This cannot be confirmed in earlier versions.

**Comment by piotr3500** [comment]
Nicely spotted! 👀 
This is as important as all the other bugs.
Thanks.

**Comment by modmodmodmod** [comment]
You're welcome.  I love polyend tracker so much.  And I'm looking forward to seeing how the new Next Button will be updated!
