### ISSUE TITLE
Song to perform bug ( NEW : VIDEO LINKED )

### ISSUE THREAD

**Issue by HakkahFR** [polyend/TrackerIssues#164]
Since i went from 1.1 to other beta version, i have the same bug: my song is instantly stop when i switch to perform and my current pattern is looped. This bug stop when I flash to 1.1

**Comment by HakkahFR** [comment]
link to the video : https://youtu.be/50eoZ6mK2ks

**Comment by piotr3500** [comment]
This is done on purpose. 
You either play a song or perform with your patterns.
Playing a song and switching tracks in Perform would cause a mess.

**Comment by HakkahFR** [comment]
Oh yesss thanks so much
