### ISSUE TITLE
More modulation control

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#167]
I don't know what kind of sound design improvements you have on your roadmap, but there are a few relatively simple modulation enhancements that would make the wavetable synthesis engine much more usable, as well as being just generally useful:
- Envelope polarity
- Envelope retrigger
- LFO Unipolar
- LFO phase
- Unsynced LFO (This is also a feature request elsewhere)

BTW, thanks for the great work you've already done. I'm very glad that you're continuing development and making point releases publicly available.

**Comment by keith-macleod** [comment]
Also, not strictly modulation, but key tracking for the filter would also be helpful for sound design.

**Comment by sebsonf** [comment]
I noticed that the lfo is reset with each voice / note. It would be nice to have the option for a global / per instrument free running lfo (e.g. for panning).
