### ISSUE TITLE
Preview Line

### ISSUE THREAD

**Issue by Terumi** [polyend/TrackerIssues#168]
It would be nice to be able to hear what all the tracks are playing so you can easily figure out harmonies.

**Comment by clarte-dot** [comment]
this exists already, you can select all steps across the channels and press preview

**Comment by Terumi** [comment]
It exists indeed but it is counter intuitive because you have to do multiple button presses. 
And again, if you want to add a few lines more to your selection you have to repeat the process again.
But you are right, it exists, so I'll close this issue.

:)
