### ISSUE TITLE
[1.1.19] "No" on Sample Recorder's "Do you want to stop the pattern?" dialog still stops the transport

### ISSUE THREAD

**Issue by ambv** [polyend/TrackerIssues#176]
1. Play a song.
2. Go to Sample Recorder.
3. It will ask "This action will stop the pattern. Do you want to continue?"
4. If you respond "No" it stops the transport anyway.

### Other important information

* How often does this bug happen? every time
* Does this bug happen in previous firmware versions? didn't check
* Does this bug happen in every project? yes

**Comment by Just-Peter** [comment]
+1 confirmed.
