### ISSUE TITLE
Per track Midi Channel for CC/PC(Program Change)

### ISSUE THREAD

**Issue by Just-Peter** [polyend/TrackerIssues#177]
At this moment you can only set a one global Midi Channel for CC/PC(Program Change). It would be great if you can set a Midi Channel for each track seperate. Example : 
- Channel 1 : C5 M01 f1
- Channel 2 : C5 M02 f1

**Comment by sebsonf** [comment]
I am hoping for this as well, currently it is limited to changing cc values of one external synth.

**Comment by BTourist** [comment]
Yes I am also hoping that this is done. It would be a good enhancement

**Comment by twonk** [comment]
I'd like to add my voice to this one - being able to send midi cc/pc to the channel in the step rather than to the one defined in the config would make a huge difference for me.

**Comment by uija** [comment]
Came here to write this ticket, found out it’s already there!

**Comment by jonreade** [comment]
+1 vote from me too for this please :-)

**Comment by ROM72** [comment]
+ 1 !

**Comment by ROM72** [comment]
Plus one vote !

**Comment by Tomsketom** [comment]
One program change out channel is a **big limitation** for tracer currently. Serious sequence toy with single PCH OUT? Come on, gentlemen! @Jacknametrouble
Pozdro!

**Comment by phaelam** [comment]
thumbs up for this one.

**Comment by piotr3500** [comment]
This will be solved a bit differently (tick all boxes tho) very soon.

**Comment by Just-Peter** [comment]
> 
> 
> This will be solved a bit differently (tick all boxes tho) very soon.

Thanks!

**Comment by jaap3** [comment]
The release notes of firmware 1.3.0 mention a big change related to this: "Tracker can now be configured to send 6 distinct MIDI CCs per MIDI channel (configured per project in Instrument Parameters of MIDI instruments 51-67)"
