### ISSUE TITLE
Allow continuing playback of the song or looping a pattern without stopping the transport

### ISSUE THREAD

**Issue by ambv** [polyend/TrackerIssues#179]
In 1.1.0 entering performance mode did not loop the current pattern. The song continued as is. This enabled complex performances like https://www.facebook.com/moreanman/videos/10222060928246379 (note: entering performance mode at 0:50 and leaving at 1:50).

Now performance mode automatically loops playback on the current pattern. This solves issues with switching tracks while playing but limits performance capability. This was in fact reported as https://github.com/polyend/TrackerIssues/issues/164

Let's solve this as follows in the Song screen:
- the first two options on the command line are PLAY PATTERN and PLAY SONG, that stays as is;
- when the transport is on, currently those two options say STOP and STOP, that will change;
- when the transport is on, instead of the first STOP on the command line there should be a command that says "CONTINUE SONG" (if playback is currently looped) or "LOOP PATTERN" (if playback plays the entire song); pressing thatkey should **not** stop the transport;
- SHIFT + PLAY during playback should toggle between loop/song playback without stopping transport.

Finally, in the transport header we should replace the `|` sign to show ▶️ or ↺ depending on whether playback is all song or looped pattern:
![show-loop-status](https://user-images.githubusercontent.com/55281/95366876-4e056f00-08d4-11eb-9af0-4cea36304ceb.jpg)

Those same icons are already displayed in the Song slots list.

**Comment by stevesomeone** [comment]
Great suggestion. I've always had an issue with the implementation of those 2 buttons with regards to switching in/out of song/pattern without disrupting the sequencer.
