### ISSUE TITLE
[1.1.20] Delay in audio signal when switching in and out of sample recorder page

### ISSUE THREAD

**Issue by Intothegroove** [polyend/TrackerIssues#181]
When you're in the Sample recorder page and you have audio coming in from any one of the sources. When you leave the Sample Recorder page and go back in from another page, there is a slight delay in the audio being heard, in previous versions aside from 1.1.19 the audio would be present as soon as you enter the sample recorder page. Thanks! 

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? I noticed it in 1.1.19

* Does this bug happen in every project? Yes

**Comment by piotr3500** [comment]
It's done on purpose.
This is to cancel audible pop when switching to and from Sample Recorder
It's rather an enhancement then the bug ;)
