### ISSUE TITLE
Export without playing in realtime 

### ISSUE THREAD

**Issue by loukltd** [polyend/TrackerIssues#188]
Hi all,

Can't find the request for this, have already emailed the feature request e-mail.  Would love it if the following feature was implemented.

Is it possible to when rendering the song as a wav file, for it to render without having to listen to the track to play through, as rendering 50 x 5 min files yesterday took 5 hours when in Renoise this would have taken about 30 minutes to do.

**Comment by loukltd** [comment]
1.1.0 is the firmware i am using

**Comment by Jacknametrouble** [comment]
No, this is not possible at the moment. Please update the firmware in your unit to gain access to other improvements.
