### ISSUE TITLE
[1.1.14] Tracks manually recorded to DAW (Tracker as a MIDI slave) drifts from each other.

### ISSUE THREAD

**Issue by Jacknametrouble** [polyend/TrackerIssues#19]
While recording a new track to disk, track after track.

Here is the setup: Use Live 10 for master clock/ transport > the Tracker via USB, I solo one track, record it, then go on to the next track on another channel etc.

The problem is the Tracker since to drive in time so none of the Track is correctly synced, and it seems that it keeps drifting as after I recorded four of the channels I now have to edit every bar so they sync up.

I just tried exporting the stems out of the Tracker and none of them is correctly synced when put in a DAW.

Additional questions to answer:
Does this bug happen every time or just once? - Always,
Does this bug happen in previous firmware versions? - It was working way better on the last firmware I've been using (v1.1.12).
Does this bug happen in every project? - On the ones I've tried,

**Comment by shuler323** [comment]
@Jacknametrouble there was a fix with ext clock in 1.1.17, regarding to #7 and #12, is bug still present in 1.1.17?

**Comment by Jacknametrouble** [comment]
@shuler323 no user reports in regard to this issue/fix.

**Comment by Jacknametrouble** [comment]
@Stazma any changes? (that was your report as far as I remember),

**Comment by Stazma** [comment]
> 
> 
> @Stazma any changes? (that was your report as far as I remember),

I did not experienced any trouble with this but I havn't really tested either. I'll try to run a real test about it today if I have some free time for it and report back asap.

**Comment by Stazma** [comment]
Back on it today, I'm having a super hard time syncing the Tracker the Live, it just keep freezing almost every minutes. Maybe it's the project I'm working on so i'll try with a fresh one and report back.

**Comment by Stazma** [comment]
Ok so I just ran a quick test with a three different channels of HiHats in a new project, still firmware 1.1.7, synced via USB, everything seems tight. I can see some minor timing offset if I zzom like crazy but nothing to be heard really.

![image](https://user-images.githubusercontent.com/71116037/94939725-d0f08900-04d2-11eb-960a-491cc5ef3a12.png)

**Comment by shuler323** [comment]
cool, so I'm closing this issue
