### ISSUE TITLE
[v1.1.20] Most steps inside a single track sound at lower volume (-6dB or so) [until more tracks are playing simultaneously]

### ISSUE THREAD

**Issue by Sft-mlk** [polyend/TrackerIssues#196]
I'm seriously suspecting it has **some relation to the master volume, I write more on the third point;**

**_Explanation_**; _[In this case Kick & Snare shares the same track]_

All sounds good till;

**1.** _I **mute the rest of the tracks**_, then automatically the kicks and snares low their volumes. _(and I'm sure that I'm not confusing the energy of the master with the energy of a single track)_

**2.** **If that track is the only track with any information of the pattern**. _(Other tracks are empty, wich is similar to 'mute' function)_

**3.** Curiously, It becomes **more evident if the master volume is lower.** At 0dB is more concealed, _I would even say it's completely concealed at 0dB_. In fact I compared lowing the 'master' of my portable speaker instead of the Tracker master, and that effect is not present. So is not a psychoacoustic effect.

--

So;

I notice it clearly specially with short samples (kicks, snares...), not that clearly with longer samples. 

I actually can hear better the drums if the rest of the tracks are playing too.

**Comment by Intothegroove** [comment]
I am noticing this too, I have a project with all 8 tracks used and on two of them I have a pad playing. Whenever I press play and start the pattern, especially if I enter the pattern window from another menu, the pads are so much more louder than the drums and the volume resets to it's proper volume after the pattern starts over.

**Comment by Sft-mlk** [comment]
Yes, I think is another issue, maybe related in some way with this one, because the sensation of energy loss is pretty similar. The first hit of a pattern sometimes loose its volume. If that first sound is a kick, snare, hihat... Then the sensation is similar to loosing the quick attack time of that first step.

**Comment by piotr3500** [comment]
Please check on 1.1.22 and let us know if it the problem still exists.

**Comment by Sft-mlk** [comment]
[v1.1.22] Still present, same behavior described.

**Comment by piotr3500** [comment]
I have to ask for the video...

**Comment by Sft-mlk** [comment]
Not perfect quality but it's perfectly audible, **check drums before and after I mute the tracks 3** (bass) **and 4** (piano samples) [https://youtu.be/UIedJggoEZ0](url)

**Comment by Sft-mlk** [comment]
I can't open the video just clicking on it, I had to copy the link and paste it on my navigator.

I dont know if that is normal on github or what. Sorry if it's my fault.

**Comment by piotr3500** [comment]
Hard to judge from the video. 
The volumes might differ after muting certain track because of the limiter.
Please try setting the threshold to the max value.

**Comment by Sft-mlk** [comment]
> Please try setting the threshold to the max value.

Done, still happening. I also tried with a longer attack for the limiter and same.

**Comment by piotr3500** [comment]
Then perhaps having your project would help.

**Comment by Sft-mlk** [comment]
_I have good news I think 🤔 this morning finally I found a common point,_ **I notice that it only happens with [this project + JBL portable speaker].** _**So weird** cause is_ **not happening with other projects + JBL speaker**, _even with the same drum samples._ 

_**BUT the good new is I was able to record the project to the computer track by track without having this issue, is just a very weird listening issue**._

_Anyway I let the link of the project here if you want to check the weird thing._ https://mega.nz/folder/n2wiRbga#44eoYQsjIitRKH9j_LGEmw

**Comment by piotr3500** [comment]
No worries. Thanks for helping us make the firmware as good as it can get.
