### ISSUE TITLE
[v1.1.21] Can't turn up/down the volume of an instrument (not everytime, but usually)

### ISSUE THREAD

**Issue by Sft-mlk** [polyend/TrackerIssues#197]
**[Instrument Volume]** You can see the virtual white fader scrolling up and down but you change nothing. (It is not a freeze)

I try to change other instrument parameters (tune, fine tune, filter type...) and this action seems to recover the volume function.

**Comment by piotr3500** [comment]
Please check on 1.1.22 and let us know if it the problem still exists.

**Comment by Sft-mlk** [comment]
[v1.1.22] For the moment (about 1,5 hours testing) this issue is not present anymore.
Once I noticed a jump on the volume when I changed it, similar to a latency, but just once.
