### ISSUE TITLE
1.1.22/Realtime eq effect 

### ISSUE THREAD

**Issue by muhfugga** [polyend/TrackerIssues#198]
I'm using the latest 1.1.22 firmware. Really like it so far, especially the real overdrive effect and also the volume of recorded audio being good volume. In the future would it be possible to have a realtime 3band eq effect on either just the master level or instrument level as well? Thank you, I enjoy the work you're doing.

**Comment by piotr3500** [comment]
Yes, we are working on a 5-band eq on master.

**Comment by muhfugga** [comment]
OMG...This machine is crazy...best investment I've made as far as music equipment in a while...Thank you!!!
    On Saturday, October 10, 2020, 10:48:51 AM EDT, piotr3500 <notifications@github.com> wrote:  
 
 


Yes, we are working on a 5-band eq on master.
