### ISSUE TITLE
[1.1.22] Looping a pattern in green Song Mode highlights the wrong pattern

### ISSUE THREAD

**Issue by ambv** [polyend/TrackerIssues#202]
Always reproduces.

![Snapshot_002](https://user-images.githubusercontent.com/55281/95685388-de56f300-0bf7-11eb-893e-3b241f6c7753.jpg)

**Comment by ambv** [comment]
Note: playing the Song highlights the right pattern.

**Comment by piotr3500** [comment]
@ziej8asek 
1. go to slot x 
2. press "play pattern"
3. green frame highlights the first slot
