### ISSUE TITLE
[1.1.0] Rename Modulation Speed

### ISSUE THREAD

**Issue by sebsonf** [polyend/TrackerIssues#207]
Maybe a bit pedantic but I find it confusing that the modulation speed is actually setting the period length of modulation in number of steps. So its the inverse of what the name suggests if speed would refer to the modulation frequency.

**Comment by Jacknametrouble** [comment]
Dear, there's a published v1.1.22 firmware available for download here at the Github. We're currently working on v1.1.23.
Please download and update your unit, read the changelogs, then start posting. Thank you,
