### ISSUE TITLE
[1.1.22] MTP works on PC but not on Mac

### ISSUE THREAD

**Issue by eyeyeyeye** [polyend/TrackerIssues#212]
I am able to have the Tracker show up as a device using the MTP on my PC laptop (Windows 10), but it does not show up doing the same procedure on either my Macbook Pro or my Mac Pro. Both are running OSX 10.13.6

**Comment by Jacknametrouble** [comment]
You're duplicating an entry which was closed already. On macOS use Android File Transfer to access the Tracker in file transfer mode.
