### ISSUE TITLE
Beat Slice mode; Select a 'slice' automatically just touching its associated pad, not changing the function on the screen button.

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#217]
Would be nice if when you press a pad then the Tracker select automatically that slice, showing the yellow bar turning to red. Would save a lot of time.

Or maybe a switch button to turn on/off this possible new function, for other users who are get used to do in the current way.

**Comment by HakkahFR** [comment]
100% same opinion , i actually don't use the beat slicer for this reason, ultra buggy

**Comment by keith-macleod** [comment]
I actually take exception to the previous comment, the beat slicer works well. It's quite fast to navigate and edit with just the arrow keys and jog wheel.
However, I have to agree that from an interface standpoint, this just makes sense.
I'd love to see some things like threshold for autoslice, slice into equal segments, and snap to zero-crossing. Then it would be pretty feature-complete.

**Comment by danapeks** [comment]
Another +1 for adding this option. On old Akai samplers you could press prog edit then hit key on your midi keyboard and it would take you to that edit page. SUPER useful and speedy.

**Comment by otternet** [comment]
Add me to this too. So much faster rather than using the jog wheel to move along the slices.

**Comment by paalweb** [comment]
+1 from me as well. I think it would make slicing faster.

**Comment by vaeinoe** [comment]
+1 for this one, as mentioned in the other (closed) issue. Having a pad selection for active slice would speed up slicing workflow a LOT and make it fun. Now it's doable but just tedious enough that you don't want to start working on slicing a sample unless you're pretty certain the track calls for that particular one.

**Comment by antistatikk** [comment]
I‘m all for this one too!

**Comment by Nodoubtyall** [comment]
Yes, it would be much faster! 🤞
