### ISSUE TITLE
[1.1.22] some FX descriptions are shifted

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#219]
I realized today that some FX descriptions are shifted (I think it's due to the add of the overdrive FX). Here's a picture of one of them.

![IMG_20201014_185553](https://user-images.githubusercontent.com/71634523/96022097-a7c7e500-0e50-11eb-8e30-9c2077125e0d.jpg)

**Comment by Jacknametrouble** [comment]
Tru dat, already reported in a separate issue
Duplicate of #201, thank you thou!
