### ISSUE TITLE
volume preview in sample loader

### ISSUE THREAD

**Issue by Mo0ko** [polyend/TrackerIssues#228]
hey
is there a way to reduce the preview volume of a sample in sample loader
it's too high !!!!!
never do that before!!!

**Comment by ambv** [comment]
We're releasing 1.2 soon, this is fixed there.

**Comment by Electronisounds** [comment]
THIS PLEASE!
We need a way to manually adjust the volume when previewing samples!
When I preview samples to load to my track - they are way too loud.
Can we please have a setting in the config menu to MANUALLY ADJUST in db the sample preview volume, please.
:) :) :)
