### ISSUE TITLE
Sample End - FX Command

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#23]
It could be the reverse of the position command; meaning it would trim a sample (much like shortening the decay). 
Very useful for many applications.

**Comment by jaap3** [comment]
Would this be similar to entering CUT or FAD in the note column?

**Comment by MegaTurrican** [comment]
No - this is proposed to be an FX command, where you can control the amount of the decay from the ADSR, or the sample end (just like the one in the performance mode, but you could program it in the step editor)
