### ISSUE TITLE
[1.10 & 1.22] Note entry stops working / becomes disjointed

### ISSUE THREAD

**Issue by math0ne** [polyend/TrackerIssues#235]
#148 

# Steps to reproduce

Hard to reproduce but I have experienced this on all the firmware versions I have tried.  Saving and reloading the song seems to fix this *sometimes*.

1) Work on a song until it becomes complex
2) Switch to a new pattern
3) Use midi in for note entry (seems to happen more but I have had this happen without a midi controller as well)
4) Note entry doesn't work
5) Enter note using polyend
6) Note entry works
7) Switch to a new pattern
8) Switch back and pattern was not saved

### Attachments and links

https://streamable.com/l9ru4l

### Other important information

* How often does this bug happen? 

Prety much every song i work on this happens eventually.

* Does this bug happen in previous firmware versions?

Yes on all firmware versions I have tried.

* Does this bug happen in every project?

Doesn't seem to happen until a project gets complex.

*EDIT: better video link*

**Comment by piotr3500** [comment]
1.2.23 fixes it.
Please install and check.

**Comment by math0ne** [comment]
Confirmed, thanks!
