### ISSUE TITLE
1.1.23 Note display glitch

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#239]
Video link below.
There is a glitch in the note display screen when you scroll fast with the jog wheel.

* How often does this bug happen? every time

* Does this bug happen in previous firmware versions? No

* Does this bug happen in every project? Yes

https://www.dropbox.com/s/713hkbs5ow7nwy3/Note%20display%20glitch.mp4?dl=0

**Comment by piotr3500** [comment]
It's normal behaviour when you scroll faster.
