### ISSUE TITLE
1.1.23 Cannot get back to step record mode

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#240]
Midi clock/transport.
When you select Live record mode on the Tracker and then start the sequencer, you cannot step back to step record mode.

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? Yes (I think is a long standing problem to do with midi)

* Does this bug happen in every project? Yes

https://www.dropbox.com/s/rj0yu77bf63z5ci/Cannot%20get%20back%20to%20step%20rec%20mode.mp4?dl=0

**Comment by piotr3500** [comment]
You do it by pressing Play, not Rec.
