### ISSUE TITLE
1.1.23 After select Instrument - does not default back to note lane anymore.

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#241]
The title describes the issue adequately.
This was fixed previously, but now it is back.

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? Yes, but was fixed.

* Does this bug happen in every project? Yes

https://www.dropbox.com/s/oyg4wl018lo753m/Does%20not%20automatically%20default%20to%20note%20lane%20anymore.mp4?dl=0

**Comment by piotr3500** [comment]
It does, but not in a Pattern Instrument screen.
