### ISSUE TITLE
1.1.23 Enter Instrument Parameter screen defaults to page 2

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#243]
When you enter the Instrument parameter screen it defaults to page 2.
This is the same as the previous fault with the Master screen defaulting to page 2

* How often does this bug happen? All the time.

* Does this bug happen in previous firmware versions? No

* Does this bug happen in every project? Yes

**Comment by piotr3500** [comment]
There is no default screen.
It stays where you left it.
