### ISSUE TITLE
1.1.23 Inability to preview instrument

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#244]
Video attached.
Focus on pattern screen.
Track contains 2 instruments on 2 steps.
The instruments do not have any envelope or settings which allow it to fill the track with audio (no polyphony or conflicting triggers)
Try to play another instrument (any instrument) with the pads - no audio for that instrument
Try to play or preview the sample in Sample Playback screen - same result.

* How often does this bug happen? It will happen in every instance, but it can be inconsistent.

* Does this bug happen in previous firmware versions? Yes, this has been reported in previous firmwares

* Does this bug happen in every project? Yes

https://www.dropbox.com/s/c5r60huaxsg45ht/Inability%20to%20preview%20instruments.mp4?dl=0

**Comment by piotr3500** [comment]
You are trying to preview notes on the already occupied track.
Each note occupies the track until the next note or OFF message.
