### ISSUE TITLE
HPF/LPF controls on Master Reverb and Delay

### ISSUE THREAD

**Issue by deixic** [polyend/TrackerIssues#248]
Currently the Reverb and Delay play back all frequencies received, which can cause mixes to accumulate unwanted low-end (and high-end). Enabling HPF/LPF controls on the Master Reverb and Delay would give users the ability to make cleaner mixes for performance and composition, and open new creative possibilities. Please consider adding these controls. Thank You.

**Comment by dramaone** [comment]
I agree, both can really busy the mix in the low end. I very rarely need anything from these below 400hz. My preference based on the tracks I make.

**Comment by piotr3500** [comment]
Master EQ is coming very soon.
No chance for separate filter on sends tho.
