### ISSUE TITLE
[1.1.14] Caps Lock Cosmetic Issue 

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#25]
When you select the song/project naming tab and press Caps Lock, the letters on the keyboard don't change to Caps but remain in lowercase, so you don't know what you are typing.

**Comment by ambv** [comment]
Looks like this works as intended:
![caps](https://user-images.githubusercontent.com/55281/93325722-054c2000-f818-11ea-8fdf-04eb16a72831.jpg)

@MegaTurrican, can you take a picture of the device in the Caps state where the keys are not uppercased?

**Comment by MegaTurrican** [comment]
Here you are; You can see that I am typing both Caps & lowercase, and the issue occurs.

https://www.dropbox.com/s/5sl5s6q6yadicfi/Tracker_Caps.mp4?dl=0
