### ISSUE TITLE
[1.1.22] Midi unit freeze

### ISSUE THREAD

**Issue by sebsonf** [polyend/TrackerIssues#259]
Yesterday I managed to freeze my unit while sending midi commands with the following pattern:

Track 1:
- sends midi cc messages A & B on a per step basis

Track 2:
- sends midi program change every 4th step:

Here is a screenshot of the pattern
![16032111352326851021399967609596](https://user-images.githubusercontent.com/12183460/96615541-ae97a180-1301-11eb-96f1-123dfae2b90c.jpg)

This was working nice and I was really impressed! I had the pattern run for a few minutes and then it suddenly froze. Had to pull the power plug.

I will try to recreate the issue today.

**Comment by Jacknametrouble** [comment]
Please update to 1.1.25 and check if the issue persists.

**Comment by sebsonf** [comment]
Was not able to reproduce the issue
