### ISSUE TITLE
Equalizer in Sample Editor

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#26]
We really need a basic EQ in the sample editor, to roll-off unwanted frequencies and make adjustments to the samples for better mixing. The filters are nice but having the ability to resample with eq processing, would result to much better production quality.

**Comment by Jacknametrouble** [comment]
This task is done already and a firmware version containing it will soon be released for tests.

**Comment by MegaTurrican** [comment]
That's amazing! Great work guys, can't wait!
