### ISSUE TITLE
Relative volume effect

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#261]
The current implementation of the volume effect is absolute, in that changing the instrument volume has no effect on the volume of notes with a volume effect applied.

This makes it a very lengthy process to balance the levels of instruments when mixing when the instrument is used across a number of patterns, especially when it's used on tracks with other instruments.

The ability to have the effect act in a way that can be affected by the instrument volume would be really nice.

**Comment by piotr3500** [comment]
We have addition Relative Volume FX on the list, so it will be implemented, sooner or later.

**Comment by keith-macleod** [comment]
Thanks, Piotr. Great to hear!

**Comment by MetabaronCZ** [comment]
I support this enhancement. Volume Fx should be relative to instrument volume.

**Comment by static-noise-PT** [comment]
Please yes

**Comment by antf4rm** [comment]
Yes please. This is a must have.

**Comment by TheGrizard** [comment]
This is top of my list too! My way of thinking is the volume fx is pre fader to the track mixer - very hard to balance finished track otherwise. Thank you!
