### ISSUE TITLE
Limiter Out / Master Out per project

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#27]
There could be a "Limiter out" volume, that could be saved within the project. Or it would be useful to re-enable saving the master volume per project, as it was in past firmwares. When preparing a live set, you don't want to adjust the master volume each time you load a new project / track.

**Comment by jaap3** [comment]
I believe firmware version 1.3.0 added the ability to store limiter/master settings per project

**Comment by jaap3** [comment]
Mmm, never mind I'm wrong about this
