### ISSUE TITLE
FX - Envelope Parameters

### ISSUE THREAD

**Issue by uija** [polyend/TrackerIssues#278]
Hey!

I would love to be able to manipulate envelope parameters per step. For hihats modifying the decay and for sounds modifying the filter amount would be my number one targets. 
As there are too many options to provide a FX for them, maybe a modulation target list would be possible (like midi cc) just with more entries, as 5 might not be enough.

Jens

**Comment by uija** [comment]
I am unable to add an enhancement label on my iPad :(

**Comment by HakkahFR** [comment]
+1000 for this

**Comment by 60pfennig** [comment]
+10000 for this!

**Comment by keith-macleod** [comment]
+1,000,000 for this. If there was a way modulate amplitude envelope decay, performance fx, step fx, whatever. It's mind-boggling how powerful this is for bringing a beat to life. All envelope parameters would be nice, but this one is just so crucial, along with gate time, but that's another topic.

**Comment by x2db** [comment]
1Billion+  for this, but if there was a mod matrix, I would just take unused LFO (say fine pitch) and control the Decay with this LFO as I do on 10+ of my synths :)
