### ISSUE TITLE
Disable scroll easing

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#289]
Scrolling through lists seems to have an arbitrary speed limit imposed on it. This makes it very difficult to scroll quickly with the jog wheel without wildly overshooting. As in, you turn the jog wheel until you get to where you want to be, and the list keeps on scrolling until its event buffer has emptied, I guess.

An option to turn that off would be welcome. Actually, I can't think of a situation where it would be advantageous, but that could just be me.

**Comment by stevesomeone** [comment]
@keith-macleod I have mentioned a closely related observation regarding the speed of jog wheel scrolling in the note selection screen. Beyond a certain speed, the display jumped all over the place. It has been considered normal.
