### ISSUE TITLE
Ability to control if you hear velocity and micro timing when entering notes via midi in.

### ISSUE THREAD

**Issue by math0ne** [polyend/TrackerIssues#291]
I know this may not be possible for micro timing depending on how that is captured but with velocity especially it would be great to be able to hear the notes as they will be played back **even** if you have velocity capture disabled.  Right now with velocity capture disabled we hear it when playing notes over midi.

**Comment by ambv** [comment]
We couldn't do anything with micro-move but velocity is now fixed.

**Comment by math0ne** [comment]
> We couldn't do anything with micro-move but velocity is now fixed.

Thanks! Makes perfect sense, I'm sure notes are quantized back in time!
