### ISSUE TITLE
[v1.2] Samples disappearing

### ISSUE THREAD

**Issue by onlyruin** [polyend/TrackerIssues#295]
### Steps to reproduce

I just updated to v1.2, and a bunch of my samples are no longing showing up in the sample loader. All of my samples are or have been converted to 44.1 kHz and 16 bit, and they are showing up on the sd card when I put it in my computer. When I open old projects that are using the samples from before I updated the firmware, they appear to still be in the projects, but I can't find them anywhere in the actual sample folders.

### Attachments and links

Here is a quick video showing the samples on the sd card, then not reading on the tracker: https://youtu.be/4wjrJn8t-W0

### Other important information

* I have restarted the tracker, and this seems to be a permanent change.

**Comment by wjakobczyk** [comment]
Could you share with us these problematic samples? That would help us find the root cause and fix the issue.

**Comment by onlyruin** [comment]
> Could you share with us these problematic samples? That would help us find the root cause and fix the issue.

There are 1000s of them. Should I just share a few?

**Comment by onlyruin** [comment]
Here's a zip of one of the folders that is not showing up. 
[AcidAmen.zip](https://github.com/polyend/TrackerIssues/files/5436011/AcidAmen.zip)

**Comment by onlyruin** [comment]
After trying a few things, I think I've found part of the problem. It seems that by automatically breaking the folders up into multiple folders with 100 samples in them it's limiting how many samples are displayed overall. If I arrange everything differently and split them up into subfolders like "Drums" "Synths" etc, more show up, but it's still not showing all of them. Some of the subfolders have 1000+ samples in them, so it breaks those into 10 separate subfolders, which seems to be stopping it from showing the rest of the subfolders that already exist. I don't know if this makes sense, but I think it's part of what is happening.

**Comment by wjakobczyk** [comment]
Thanks that will help!

**Comment by wjakobczyk** [comment]
Could you also share one of these large folders with 1000+ files?

**Comment by wjakobczyk** [comment]
We have found a potential fix for the issue, could you please give the folllowing build a try and let us know if the problem is gone?
[Polyend_Tracker_Firmware_1.2.1.zip](https://github.com/polyend/TrackerIssues/files/5438600/Polyend_Tracker_Firmware_1.2.1.zip)

**Comment by onlyruin** [comment]
> We have found a potential fix for the issue, could you please give the folllowing firmware build a try and let us know if the problem is gone?
> [Polyend_Tracker_Firmware_1.2.1.zip](https://github.com/polyend/TrackerIssues/files/5438600/Polyend_Tracker_Firmware_1.2.1.zip)

These seems to have fixed it! Thank you so much!!

**Comment by wjakobczyk** [comment]
Good to hear that, thanks for the help.
