### ISSUE TITLE
[1.2.0] "Whine" noise in Sample Loader preview, but not in Sample Playback

### ISSUE THREAD

**Issue by jarradh** [polyend/TrackerIssues#298]
There appears to be a bug where the Sample Loader Preview audio output differs from actual Sample Playback with these particular 8bit samples. In the Sample Loader preview there is a "whine" that can be heard, but if the sample is loaded, and played, the sample plays correctly. I do not have this issues with other samples.

### Steps to reproduce

- Download the converted and re-tuned Amiga samples from
https://archive.org/details/AmigaSoundtrackerSamplePacksst-xx8192HzTuned
- Unarchive the zip and load samples onto SD Card
- Insert SD Card into Polyend Tracker
- Tap "Sample Loader" on Polyend Tracker and Navigate to a sample
- Tap and hold Preview and hear the sample with a whining noise
- Tap Add, then tap Sample Playback
- Play a note and hear the sample as intended, with no whine.

### Attachments and links

https://archive.org/details/AmigaSoundtrackerSamplePacksst-xx8192HzTuned

I have included one sample here for convenience.
[FilterBass.zip](https://github.com/polyend/TrackerIssues/files/5436902/FilterBass.zip)

### Other important information

* How often does this bug happen?
Every time

* Does this bug happen in previous firmware versions?
Did not test

* Does this bug happen in every project?
Yes

* Does this happen with other samples?
No

**Comment by wjakobczyk** [comment]
This will be fixed in next release, but note that there is still some difference in preview in imported sample - there are slightly different algorithms used due to performance/memory constraints when doing preview.
