### ISSUE TITLE
[1.2.0] The event disappeared from all patterns while editing a pattern.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#299]
About 30 patterns of events were all emptied in an instant.

I tried to restart it and when I pressed and held the power switch, the bar progressed, but I could not shut it down.

When I unplugged the power cable, it shut down, but when I started it, I was forced to insert the SD card even though the SD card was stuck.

The events that disappeared after repeatedly inserting and removing the SD card and starting and restarting has returned, so it's okay for the time being.

I couldn't keep a record because I gave priority to recovery and backup, but I will report it because there was a bug of # 294 in the same v1.2.0 yesterday.

I'm afraid that the errors I encounter in this version can lead to more data loss than ever before.

**Comment by muhfugga** [comment]
I had a similar thing happen. I was editing patterns in pattern view, going back and forth between 2 patterns and then they both disappeared. I then could not shut it down unless I unplug the usb cord.

**Comment by ambv** [comment]
Is this still happening in the current firmware? There's been rather large changes which likely fixed this problem.

**Comment by ambv** [comment]
Closing, please reopen if you end up seeing this again.
