### ISSUE TITLE
Chord / Arp FX command

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#31]
I am sure you guys have already thought about that, the Chord / Arp FX command inspired from LSDJ, would make a great addition for us oldschool chiptuners.

![5gPyNA4](https://user-images.githubusercontent.com/71126897/92912582-9c893000-f432-11ea-9ddf-00e19896c621.png)

**Comment by jemmons** [comment]
+1 I'd love some sort of arp functionality. Right now I fake it by really cranking up the BPM (which makes the rest of pattern a pain to work with) or rendering my arp sequence to a new instrument (which locks it to a tempo). An FX command would be ideal though this could also be achievable with finetune automation if finetune had a greater range and LFOs were more customizable? Or a new Instrument Parameter just for arp? Or even a roll if we could somehow give intervals to the roll in addition to step count?

**Comment by Madrayken** [comment]
Totally agree. I can't think of a tracker I've used which doesn't have some kind of note-arp. It's especially important in trackers, as each note chokes the previous one, meaning you run out of 'real' voices fairly quickly.

**Comment by RadicalAns** [comment]
+1 to this idea. I'd love to have this type of functionality.

**Comment by tilllt** [comment]
I dont know LSDJ but it sounds as if it is similar to what i meant in my suggestion.

**Comment by fragment23** [comment]
+1 for the arp fx

**Comment by MetabaronCZ** [comment]
I would like to see that too. There is Roll Fx which makes substeps, so it could be possible to extend this functionality.

**Comment by eholzbach** [comment]
Was thinking today I'd like to arpeggiate midi gear.

**Comment by muhfugga** [comment]
+1

**Comment by Jacknametrouble** [comment]
implemented
