### ISSUE TITLE
Loop Point import and save

### ISSUE THREAD

**Issue by modulationsource** [polyend/TrackerIssues#311]
Standard wav files can contain loop information. More Infos:
https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#smpl

So it would be very good, that the loop point information would be loaded when samples are importet.
I tried to import looped samples with impulse tracker files. This works with samples shorter than 0,5 seconds.
Samples longer than 1 second in the impulse tracker file are always importet without loop.

At least one of these ways for importing loopes wavs would be great.

**Comment by Jacknametrouble** [comment]
The 1.5 beta1 firmware allows to save/load instruments with all their properties now.
