### ISSUE TITLE
midi implementation

### ISSUE THREAD

**Issue by PaulAntioche** [polyend/TrackerIssues#312]
Hello.
can we hope for a full midi implementation on all parameters of effects, instruments, envelope, filters ... and all

**Comment by ambv** [comment]
Not on all parameters, there's far too many instruments and parameters for the number of available CC parameters in MIDI.

**Comment by MrMolletta** [comment]
At least main parts like envelope, filter etc etc, but for me, the essentials are the program change allow u to change pattern from midi. This is a must. Tracker Is a very nice machine, but, at this this, Is a little bit limited.
