### ISSUE TITLE
[1.2.0] Fill bug

### ISSUE THREAD

**Issue by pigeonsky** [polyend/TrackerIssues#315]
When using "fill", step value won't change. 
Example - using "fill", I put a sample on every 4 step. I then change the value to a different step number, the value won't change. 
I have to delete the sample and start the "fill" again.

**Comment by Jacknametrouble** [comment]
@pigeonsky What does it mean "I then change the value to a different step number, the value won't change."?
I'm testing this and the Fill tool works as supposed to. Filling each 4 and then each 2 is all fine.
If you refer to the Step tool, then it does not influence the Fill tool anyhow.
