### ISSUE TITLE
MicroPitch is interesting, but can we add a regular Pitch shift?

### ISSUE THREAD

**Issue by MachineAgeVoodoo** [polyend/TrackerIssues#320]
Hi. The title says it all, an FX that simply pitches in increments of semitones seems to be missing. Apologies if I am missing something obvious. A sample as it plays through the pattern, could be pitched up or down per step. Then not only by retriggering it on a new key. This could then also be used to achieve "pitch bend" type of effects.

Thank you for reading

**Comment by ROM72** [comment]
Yes, a pitch envelope would be great and not just a finetune envelope.

**Comment by dmt-hub** [comment]
Yes, please!

**Comment by tfspsound** [comment]
Totally onboard with this, it’d save copying samples to repitch them too.

**Comment by nthe** [comment]
I would that as well, but it looks like this one was already requested and rejected. 😞

Duplicate of #344

**Comment by MachineAgeVoodoo** [comment]
its implemented already in current firmware

**Comment by nthe** [comment]
I was reffering to pitch envelope feature in automation panel, or am I missing something? 🤔

I see that the ticket is just about pitch shift and not about automation.... sorry for confusion. 😐

**Comment by Jacknametrouble** [comment]
This isn't possible due to the used hardware resources.
