### ISSUE TITLE
[1.2.1] Render selection does not work properly

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#321]
It renders all tracks and all steps even not being selected.

If I mute tracks, those tracks then will not be rendered. On the other hand, is not possible to mute steps, so there is not a alternative solution for selective step rendering at the moment.

**Comment by Jacknametrouble** [comment]
Confirmed > mark steps on a single track only > render selection will render all the steps from all the active tracks no matter what the selection is. The Preview function works alright thou.
