### ISSUE TITLE
Restore the function to play song during perform

### ISSUE THREAD

**Issue by HakkahFR** [polyend/TrackerIssues#322]
With the 1.1 firmware we were able to use the perform mode with the entire song. Now it is only loop the current pattern. The two function are cool, but we actually can't play the entire song and use the perform mode at the same time. Sorry for this english

**Comment by Jacknametrouble** [comment]
This is an intentional change. The performance mode sign indicates you can mix tracks from different patterns and apply performance FX. You can switch to the Song screen and press "Continue song" to resume playing the entire song.

Sincerely,
