### ISSUE TITLE
[1.2.1] Notes get destructively clamped to same value when transposing high or low enough

### ISSUE THREAD

**Issue by vaeinoe** [polyend/TrackerIssues#329]
**Steps to reproduce:** Fill a pattern with some note data, select some notes, transpose them as high or as low as tracker allows using the jog wheel
**What should happen:** Either the whole selection is transposed only up until the highest note of the sequence is at maximum value / lowest note at minimum and the relative pitches are kept as is, OR the whole pattern is eventually non-destructively clamped to highest / lowest note and when transposing back, the relative note values return.
**What happens:** Transposing high or low enough, all the selected notes get clamped to same max / min pitch. When transposing back, they all stay the same with each other - effectively losing the whole pitch data of the selection.

I'm not sure if this is considered a bug or works as intended (I did not try this before 1.2.1 and I can't remember how it goes with different software trackers anyway), but at least it's accidentally easy to mess up a pattern by transposing it a bit too high / low, then transposing back to normal audible range.

**Comment by ambv** [comment]
This isn't something we can easily change. If you transpose your sequence too low, Undo to recover the previous note values.
