### ISSUE TITLE
[1.1.14] Recorded sample volume level is very low

### ISSUE THREAD

**Issue by Jacknametrouble** [polyend/TrackerIssues#33]
When sampling, set a good gain level and it sounds appropriate. After saving the sample, the level drops so much that it cannot be heard. Playing around with sampling the radio and the record level was at the higher end of the yellow and during monitoring, sounded fine. After saving, it's impossible to hear it unless cranking up the system volume a lot.

Additional questions to answer:
Does this bug happen every time or just once? - Always,
Does this bug happen in previous firmware versions? - Yes,
Does this bug happen in every project? - Yes,

**Comment by stevesomeone** [comment]
Does this bug happen every time or just once? - Always
Does this bug happen in previous firmware versions? - Yes
Does this bug happen in every project? - Yes

This issue also presents itself when previewing the recorded sample before saving.
