### ISSUE TITLE
Envelopes to zero when delete is pressed

### ISSUE THREAD

**Issue by Plieuw** [polyend/TrackerIssues#333]
A workflow enhancement, 

When editing the envelopes, hit delete to put adsr on 0ms.

**Comment by x2db** [comment]
yes, it is very annoying to change A,D,S,R anytime I go work with ANY envelope

**Comment by bambrose** [comment]
That's cool. I also suggested (in another issue) wrapping values (like in pattern scroll) so you can turn wheel to go from 0 to 100 or vice herds

**Comment by pinkcell-niico** [comment]
Yep !
