### ISSUE TITLE
Grid pad layout, pad directly above +5 semitones

### ISSUE THREAD

**Issue by amazinghoehne** [polyend/TrackerIssues#336]
Hello there :)
Recently I tried out Tracker and I really enjoy the aesthetics and workflow of It.
However I had an idea/request for an future firmware update of Tracker. It would be super great if it was possible to add an layout for the grid pads, where the pad directly above will increase +5 semitones. This layout would be reminiscent of an guitar/bass neck and make entering notes for guitar folks like me super intuitive. 
Keep up the good work :)
![17E3AAFD-DE44-4990-8355-6130623F1508](https://user-images.githubusercontent.com/74042226/98339965-dfb7e780-200c-11eb-96c8-559b8f26ec52.jpeg)

Best wishes

**Comment by vaeinoe** [comment]
This is already possible: Config -> General -> Pads layout -> select "5" as the layout.
