### ISSUE TITLE
[1.2.1] Export not rendering song properly (gaps and skipped patterns)

### ISSUE THREAD

**Issue by danapeks** [polyend/TrackerIssues#341]
Hi there, 

As the title says really - tried to export a full song (not stems) and I tried twice, both times the audio skipped and it jumped about on patterns. Screenshot here so you can see what i mean:
[Pic](https://ibb.co/HFt6sSd)
It did it in different places each time. 
[Pic2](https://ibb.co/Ryw2XL7)
There seemed to be less problems on the second export where I turned the limiter down. 

Any help appreciated. 
Thanks

**Comment by jaap3** [comment]
Song export has been reworked for firmware version 1.3.0. If you haven't upgraded already I'd suggest doing so and trying this again. Hopefully your issue has been resolved. If this issue is still present, please report back!

**Comment by shuler323** [comment]
@jaap3 is right again :)  other problems with exporting please write in existing open issues
