### ISSUE TITLE
Pitch envelope

### ISSUE THREAD

**Issue by muhfugga** [polyend/TrackerIssues#344]
I'm hoping it's possible to add a pitch envelope in the instrument parameter window in addition to the fine tune envelope thats already there? Maybe have an option to choose between regular tune and fine tune if having both at the same time isn't possible?

Again I love what you are doing with this instrument thanks for the firmware improvements you have added already.

**Comment by Jacknametrouble** [comment]
This isn't possible due to the used hardware resources.

**Comment by muhfugga** [comment]
Oh ok no problem. Thanks.
