### ISSUE TITLE
[1.2.2] Reverb and Delay not exported Pattern or Song Stems when Send are a in Post Fader mode.

### ISSUE THREAD

**Issue by Stazma** [polyend/TrackerIssues#354]
Hey there, I just noticed while exporting a new track that my reverb and delay wav are empty of any sounds as there should be some. So I checked creating another project, same thing, until I realized I could change to pre-fader and then it worked. 

Still it would be cool for this to work properly in Post-Fader mode.
[3.zip](https://github.com/polyend/TrackerIssues/files/5531770/3.zip)

### Attachments and links

Here is a simple beat I made that uses reverb, you can check by with this that it does work only with Pre-Fader sends.

### Other important information

* How often does this bug happen? In all projects

* Does this bug happen in previous firmware versions? I don't think so

**Comment by ambv** [comment]
This is fixed in 1.3, reverb and delay are now exported when post-fader is used.
