### ISSUE TITLE
[1.2.1] Tracker Freezes while editing patterns.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#356]
I can still hear the pattern playing sound, but everything is freezed and I can't do anything.

So far, restarting and inserting and removing SD card does not solve this problem,
I can recover by loading SD card on Mac and then launching Tracker.

This bug often happens in different projects.

I can't find it in this thread right now because it may have been closed,
But I've reported the same bug with my previous firmware Maybe.

**Comment by ambv** [comment]
If this is still happening on 1.3, please record a short video showing the problem.

**Comment by ambv** [comment]
Closing, please reopen if you end up recording the video.
