### ISSUE TITLE
[1.3.0b1] New 'Bass Boost' master function seems to not work.

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#367]
I'm not noticing any change on the sound when I turn up this value from 0 to 100. 

(Tried, of course, with a pattern with bass, kicks, snares, etc.)

On the other hand, I perfectly notice gain changes using it's brother parameter 'Space', and all the 5 bands of the new master equalizer are working fine.

**Comment by piotr3500** [comment]
Bass Boost slightly (0-5dB) increases 80Hz. 
Perhaps your samples do not go as low as that.

**Comment by LetsSeeIfWeSolveThis** [comment]
True, true! My fault, thanks for the explanation.
