### ISSUE TITLE
[1.3.0b1]  Line Out feeds back into Line In

### ISSUE THREAD

**Issue by bangcorrupt** [polyend/TrackerIssues#370]
## Hi, sorry you had trouble!

The new Line In through feature appears to be picking up signal internally from the Line Out.  

This happens even with nothing connected except the power.  

The line In meters also spike slightly when the Line Out jack is plugged/unplugged (only if the pattern is playing).

I can't tell if it's actually audible or just a bug with the metering code, as it's far too loud for headphones.  

### Steps to reproduce

Play sound at close to full level.  

On Global Mixer page 3/3 Line In meter will react to Line Out level.  

While the pattern is playing, plug and unplug the Line Out jack.  

The Line In meters will spike slightly higher as the jack is connected/disconnected.  

### Attachments and links

Project file demonstrating issue:

[line-in-feedback-bug.zip](https://github.com/polyend/TrackerIssues/files/5555449/line-in-feedback-bug.zip)

### Other important information

* How often does this bug happen? 

Every time.

* Does this bug happen in previous firmware versions?

Previous versions do not have Line In through feature.

* Does this bug happen in every project?

Every project I have tried.

**Comment by keith-macleod** [comment]
I can corroborate. Line in meter is following dry mix meter about 24db below.

Awesome update, guys. Still digging into the new features.
