### ISSUE TITLE
Insert  Exsert / Extract

### ISSUE THREAD

**Issue by tfspsound** [polyend/TrackerIssues#373]
So I find Insert useful for adding blank cells and moving the subsequent steps down. I’d like to be able to remove steps too pulling the subsequent steps up using Shift + Delete on an empty step. Basic but useful I think.

**Comment by bangcorrupt** [comment]
Using Shift + Delete (Backspace) will remove the step above the selected step.

**Comment by tfspsound** [comment]
My bad, I was sure I tried this before writing. I’m in the habit of pressing the top left pattern button when I want to press shift, I think it’s a hang up from my previous machine. 
Cheers
