### ISSUE TITLE
[1.3.0 beta 1] Cut no longer cuts sample in pattern editor

### ISSUE THREAD

**Issue by ilambert** [polyend/TrackerIssues#377]
Steps to reproduce:

Add a step to a pattern, use "Cut" on the following step. 

It behaves like an "off", not stopping the sample's envelopes.

* How often does this bug happen?
Every time

* Does this bug happen in previous firmware versions?
No. It seems to be a new one (or perhaps a regression)

* Does this bug happen in every project?
Yes, as far as I can tell.

**Comment by bangcorrupt** [comment]
Duplicate of #364?

**Comment by ilambert** [comment]
Yes. Didn't see that one.
