### ISSUE TITLE
[v.13.0b] Little visual bug on new master EQ

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#380]
(1) After moving up randomly the 5 white EQ bars (or faders, whatever is called) and...
(2) going back to Master 1/3... 
(3) If I go to EQ window again and I reset every bars to 0dB, **some of them will not be displayed at the same height** (not on the perfect center of the fader)

It get fix if you turn down or up totally the bar [+12dB, -12dB] and go again to 0dB.

----
Note about the first step (1) --> I can reproduce it only turning up the faders. At the moment I didn't see the bug when I turn every fader down (below 0dB)

**Comment by pigeonsky** [comment]
yes, i noticed this too.
