### ISSUE TITLE
Solo/Mute instrument, specially 'solo' function directly from the Instrument Parameter Window

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#383]
Most of the time I want to check what I'm doing to an instrument without any other distraction, and I have to go back and check the track where it's placed that instrument and mute the others tracks.

It would be useful for many other things.

**Comment by dramaone** [comment]
cirtical for me, for example, four channels running audio, I program a spliced beat on the 5th and then have to mute 4 channels to ensure the 5th is how I want it to sound, such as the loop is in time

**Comment by danapeks** [comment]
Upvoting this - would be super useful.
