### ISSUE TITLE
Wavetable smoother enhancement

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#386]
Hi, I find I'm a bit confused by the WT smoother algorithm, e.g it can smooth for an arbitrary window length, but WT playback only gives windows in powers of 2. 

Also, when window len * window num exceeds the sample length, which applies?

Also, what exactly does it do, and ... I guess what I'm saying is that the manual could definitely use some expansion in this area.

A guide on how to tailor a sample for good wave table results would also be a boon.

But the one enhancement that I think would be killer would be an auto smoother, which would pitch-detect the sample, choose the closest window length, pitch shift/phase shift to the correct frequency/alignment for that window, and then apply the smoother, with a manual override for window length and/or pitch if the pitch is vague or otherwise difficult to detect (e.g. short sample), or just to force a specific result.

The ability to duplicate instruments when one is doing experimentation with this kind of destructive edit would be a welcome addition as well.

Anyways, it's an idea, and I'm sure you have your own in the works, which I eagerly await. Keep on keepin on, as they say ;)

**Comment by jakubhlavaty** [comment]
I understand the smoother can help make arbitrary wavetables usable.
When I find that my wavetable sample isn't in line with the "power of 2" windows I go over to use the smoother, but the 2 values (number and window) aren't all that intuitive. Maybe I don't know how long the window is or how many waves there are.

Would be nice if I could select the window visually (e.g. with a jogwheel) - i.e. "zoom in" and see the wave. Window number could be pre-filled to be "as many as there are" and I could maybe reduce that with a parameter...
