### ISSUE TITLE
Pressing 'More' action swaps menu back to default

### ISSUE THREAD

**Issue by bgdnrz** [polyend/TrackerIssues#387]
Small feature request, not a big deal. 

In Pattern view, pressing More brings up a list of additional features. Pressing one of these would ideally swap the menu back to its default state (Pattern, Length, Step...) rather than having to press More again to get back to the default state.

For example: I press 'Copy Pattern', then have to press 'More' so that I can change the pattern so that I can paste it. Instead, ideally scenario would be to press 'Copy Pattern', menu goes back to Pattern, Length, etc so I can immediately change pattern and press More / Paste. 

Any of you agree or happy with it as is? I find it would reduce number of key presses.

**Comment by thebradclay** [comment]
I agree. I tend to hit the wrong button after pressing More. I end up hitting render next.
