### ISSUE TITLE
[1.2.2] Micro-timing & PRG Change on step 1 of a pattern doesn't behave as expected.

### ISSUE THREAD

**Issue by tc-joegiralt** [polyend/TrackerIssues#391]
### Steps to reproduce

* Get a Cirklon or an Elektron and configure it to  respond to scene/pattern changes via prg changes
* Slave above Sequencer to the Polyend Tracker.

## for the the tracker
* On step 1 of pattern 1(on any track) set fx 1 to micro-timing 100%(`m 100`), set fx2 to program change 0 (`f 0`)
* On step 1 of pattern 2(on any track) set fx 1 to micro-timing 100%(`m 100`), set fx2 to program change 0 (`f 1`)

## for the Elektron box or the Cirklon
* have two scenes or two patterns

## expected result
* the combination of micro-timing and the program changes would cue up the next pattern/scene on the criklon/elektron boxes

## actual result
* the micro time doesn't happen before the pattern starts, therefor it doesn't cue up the next scene, or pattern

### Attachments and links
[![Watch the video](https://yt-embed.herokuapp.com/embed?v=1mSu8KdmP7M)](https://youtu.be/1mSu8KdmP7M)

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

everytime

* Does this bug happen in previous firmware versions?

not sure but probably

* Does this bug happen in every project?

yes

**Comment by shuler323** [comment]
I have no Cirklon or an Elektron to chceck the same setup, but using MIDI monitoring software "program change" seems to be sent correctly. Checked on 1.2.2 and 1.3.0b2. Please chceck the newest beta and if problem occurs, please contact us.
