### ISSUE TITLE
Pad sensitivity issue

### ISSUE THREAD

**Issue by koraysels** [polyend/TrackerIssues#395]
Anyone else having issues with pads not being consistently triggered when pressed?

Ik makes finger drumming quite challenging..

**Comment by deixic** [comment]
Yes, very inconsistent here too.

**Comment by LetsSeeIfWeSolveThis** [comment]
I can't play two pads at the same time. Like a monophonic finger drumming experience.
Can you confirm this?

**Comment by koraysels** [comment]
Okay that solves your polyphony issue but I really have a problem even on an emtpy pattern first track. The pads are really "stiff" and do not consistently register finger presses. 

Could this possibly be fixed with software?

**Comment by LetsSeeIfWeSolveThis** [comment]
I have to give you the reason anyway, I mean, I always noticed issues in finger drumming, beyond my last comment issue.

But being too noob with this device yet, and thinking about the polyphony limit... I can't assure nothing yet. Maybe the release times of some drum samples when I play faster make it fails, or maybe its a real issue and something fixable thru the software. I need more time to verify, but It don't seems to be a hardware issue.

**Comment by koraysels** [comment]
Sorry @LetsSeeIfWeSolveThis but maybe you can open a seperate issue? I am actually talking about pad presses not registering.. even just a single pad. Nothing to do with polyfony, please open a seperate issue if you have other issues.

**Comment by LetsSeeIfWeSolveThis** [comment]
''_even just a single pad._'' I was just confirming If we had the same problem, you didn't mention that, please specify your problems before posting them.

**Comment by koraysels** [comment]
Okay cool, so you are a contributor? What i mean is like I said originally. I have a problem with overall consistency of the pad sensitivity for registering presses. With my unit it is not consistent;) apparently others have this too?

Just leaving it out here in case the software makers come across this and think they have a solution. Have a nice day.

**Comment by deixic** [comment]
koraysels: I have the exact same problem as you, inconsistent pad sensitivity.

**Comment by math0ne** [comment]
I experience this for sure, especially noticeable when entering hi hats into a beat.  If I use an external midi controller with pads, it's perfect.

**Comment by koraysels** [comment]
Damn I dont want to have to use an external midi controller. 

I wonder if the new hardware revision fixes this and if so, if we could send in our units for the new ones (rounded corder buttons version)?

**Comment by visualearner** [comment]
I have the same issue. It makes entering notes in time nearly impossible which when making music is a bad thing. Please fix.

**Comment by x2db** [comment]
> Damn I dont want to have to use an external midi controller.
> 
> I wonder if the new hardware revision fixes this and if so, if we could send in our units for the new ones (rounded corder buttons version)?

A new hardware revision ? could you share link where this was discussed ?

**Comment by szszoke** [comment]
I am having this issue as well with a second hand unit.

The unit was purchased from Thomann at the end of November 2021.

The pads require a rarher strong tap to trigger. All of them.

**Comment by szszoke** [comment]
> Damn I dont want to have to use an external midi controller. 
> 
> I wonder if the new hardware revision fixes this and if so, if we could send in our units for the new ones (rounded corder buttons version)? 

I seem to have the newer revision and the pads also feel a bit hard to trigger for me.
