### ISSUE TITLE
Sample loader - clearing the list of unused instruments in the project.

### ISSUE THREAD

**Issue by Tomsketom** [polyend/TrackerIssues#396]
Sample loader - one button clearing the list of unused instruments in the project. It would make life much easier.
Dzięki!

**Comment by jaap3** [comment]
Firmware 1.3.0 adds a "Delete unused" button to the sample loader screen (I think #358 is also a duplicate)

**Comment by Jacknametrouble** [comment]
This has been added in 1.3.0
