### ISSUE TITLE
[1.3.0b1] LFO panning crackles on longer samples (0.7 sec +)

### ISSUE THREAD

**Issue by jasll** [polyend/TrackerIssues#400]
Using samples of synth / longer tom hit sounds for example and wanting to pan quickly to give a shimmer effect produces a dirty signal full of crackling noise on higher LFO speeds. The lower you go the cleaner it gets.

**Comment by ambv** [comment]
Our digital LFOs aren't continuous but discrete. We're unlikely to change this behavior at this stage of the product. High rates are fine for many uses but for panning in particular it's something that exposes this limitation, esp. when the rate is shorter than 1 step.
