### ISSUE TITLE
[1.3.0b1] Changes in pattern mode get erased in song mode while using instrument to input data

### ISSUE THREAD

**Issue by dustinpero** [polyend/TrackerIssues#401]
I've noticed when I try to add a pattern on instrument 10 track 8 with a pattern that already exists in song mode (pattern 7). My changes get erased after playing up to pattern 7 in song mode. I'm also using instrument mode to input the data as well. The bug doesn't seem to happen when using note mode to input data.

* How often does this bug happen? 
Every time.

* Does this bug happen in previous firmware versions?
not that I'm aware of.

* Does this bug happen in every project?
Yes, i loaded a new project and tested it with a single sample on instrument 10. Pattern 1 in track 8 works as intended, but once I switched from pattern 1 to 7 in song mode, my pattern was erased again in track 8 on pattern 7.

**Comment by BerndPeuser** [comment]
https://github.com/polyend/TrackerIssues/issues/388

**Comment by shuler323** [comment]
> #388

:)
