### ISSUE TITLE
[1.3.1b3] Two notes playing when replacing one

### ISSUE THREAD

**Issue by Konevitsaus** [polyend/TrackerIssues#403]
The newest official firmware still has one thing that really messes with my creative flow: when overwriting some existing notes with new ones, it very often plays the replaceable note as well, not only the replacing one. Highly irritating at least for me. Any chance to fix this?

**Comment by shuler323** [comment]
Please add some more info - at least FW version where this bug occurs and steps to reproduce

**Comment by ambv** [comment]
Ideally we need a short video that shows the issue.

**Comment by Konevitsaus** [comment]
I hope this got uploaded. There's a video about me playing one note and then overwriting it with another. You can hear how at one point the old note is repeated between the new ones.

This one was quite a quick one and featured quite a little annoyance. But sometimes when tracking, it's almost constant. Very annoying.

[trackerbug.zip](https://github.com/polyend/TrackerIssues/files/5604790/trackerbug.zip)

**Comment by Konevitsaus** [comment]
(My firmware version is the latest one – I mean, even as a beta.)

**Comment by shuler323** [comment]
thanks for video, we'll work on it

**Comment by Konevitsaus** [comment]
> thanks for video, we'll work on it

Actually, now I noticed that it mostly happens when there's a note right next to the one I'm replacing – that NEXT note starts to play at the same time. Very, very distracting when trying to keep some new melodies in my head and put them on the track.
