### ISSUE TITLE
Trim/Cut function in sample editor

### ISSUE THREAD

**Issue by davidmattoid** [polyend/TrackerIssues#407]
Hi!

I would appreciate a Trim/Cut function in the sample editor.

I mean, with the crop function is possible to cut the beggining and the end of a sample but I'm asking for a function to cut int the middle. For instance, clear a silence zone between two sound events. 

Thanks for your great work!

**Comment by tfspsound** [comment]
I agree a remove or delete function would be very handy. Alternatively I could work with an option to remove or ignore a clip in clip mode.
