### ISSUE TITLE
[1.3.0beta1] song mode freeze

### ISSUE THREAD

**Issue by theGh0stCat** [polyend/TrackerIssues#410]
When using song mode to create new patterns tracker freezes about 1/2 of the time, accompanied by a visual glitch over tempo bar and green select box. . Regardless of project this occurs.

### Steps to reproduce

Build pattern 1 with more than one track used then in song mode copy paste to build a second pattern from track blocks of pattern 1.

### Other important information

* How often does this bug happen? 
Almost every time.

* Does this bug happen in previous firmware versions? 
No

* Does this bug happen in every project?
No, it occurred on 3/4 new projects.

**Comment by ambv** [comment]
I cannot reproduce this and copying and pasting is something I do often. We need some more information. Can you take pictures of your pattern view and config screens?
