### ISSUE TITLE
1.3.0b1 Pattern screen display glitch

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#414]
A minor concern, but a little annoying.

1. Pattern screen
2. Hold pattern button to change pattern
3. Screen temporarily stops scrolling
UPDATE - Yeah it seems to wait until the pads light up (there is a delay until this happens), then it begins scrolling again.

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? Yes, I have noticed this since possibly 1.17

* Does this bug happen in every project? Yep.

**Comment by mroemore** [comment]
I've also noticed this. It's especially obvious when you're in REC mode and your cursor is on a step which has no notes in either pattern.

**Comment by thebradclay** [comment]
Noticed this as well!
