### ISSUE TITLE
[1.3.01] Song stems are not in time with each other when exported.

### ISSUE THREAD

**Issue by Stazma** [polyend/TrackerIssues#415]
Hi there,

So i've been trying to export a few songs as stems to work on the mixdown in the computer and a old bug seem to have resurfaced, the stems are not perfectly in line with each other, some seems to drift a little with time so the more the song advance the more elements gets unsynced
![export bug](https://user-images.githubusercontent.com/71116037/100230937-9df0d180-2f26-11eb-868f-34d3f0db30bf.png)

* It seem to happen with every tracks I tried to export

* I remember I did mention this before but I also remember it being fixed at some point.

**Comment by doelman** [comment]
Same as #281 I don't think this has been solved in 1.3.01 as this bug is still open?

**Comment by shuler323** [comment]
Export function will be implemented in new way, you can expect fixing your issue in some new betas, which will be noted here.
(#281)

**Comment by dfordabs** [comment]
firmare 1.5.0 - still not fixed
