### ISSUE TITLE
Sample Purge

### ISSUE THREAD

**Issue by TwistedGenetics** [polyend/TrackerIssues#416]
Hi

It would be cool to either, have a marker in the "sample Loader" section to show currently used samples, or an option to purge unused samples from the instruments pool.

**Comment by mroemore** [comment]
I agree, but this is a duplicate of issue #396

**Comment by PaulAntioche** [comment]
yes!

**Comment by jaap3** [comment]
Firmware 1.3.0 adds a "Delete unused" button to the sample loader screen

**Comment by Jacknametrouble** [comment]
This has been added in 1.3.0
