### ISSUE TITLE
[1.2.2] Dangerously loud audio glitch in Perform mode

### ISSUE THREAD

**Issue by luwispurpul** [polyend/TrackerIssues#419]
### Steps to reproduce

This bug occurs when combining (I think) the RV and m FX with the Pattern Play Mode lane on the Perform Screen. Please see my video here:
[YouTube Video](https://youtu.be/PlVWve0lmWk)

DO NOT WEAR HEADPHONES WHILE WATCHING AND PLEASE WATCH AT A LOW VOLUME

The combination of these cause dangerously loud audio spikes.

### Attachments and links

Here is the project. i have not tried to reproduce it in other projects.
[IDM curzon.zip](https://github.com/polyend/TrackerIssues/files/5600306/IDM.curzon.zip)

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

It happens every time I select "Back" in the Pattern Play Mode lane and some of the other Custom settings (C1, C2 etc)

* Does this bug happen in previous firmware versions?

I don't know

* Does this bug happen in every project?

No, but this may be because of the combination of factors.

Thanks,

Ivan

**Comment by shuler323** [comment]
hi, I cannot reproduce this bug as it is shown on yt video (in v1.3.1b3) maybe something has been improved that was causing this problem. Please try v1.3.1b3 or higher and reopen issue if bug still occurs.
