### ISSUE TITLE
Add solo tracks to the performance page 

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#42]
Self explanatory really. In the same manner as mutes. Not sure how this could be worked in.....maybe a rolling shift function.
EG: on the performance page - default is track/pattern - press shift to display track/mutes - press shift again to display track/solo - press shift again to return to default track/pattern

**Comment by dramaone** [comment]
I thought I was going mad, seems strange to have a mute without a solo. Have to mute 7 tracks!
