### ISSUE TITLE
[1.3.0b1] When exporting song stems, Note changes between end of one pattern and start of next pattern don't occur right away

### ISSUE THREAD

**Issue by soundbylan** [polyend/TrackerIssues#420]
I have experienced an issue when exporting song stems where I have a sample at C5 in one pattern, and then C4 in the next pattern. When the song exports, the sample "spills" over in C5 at start of the pattern where it is programmed as C4. And the reverse happens also.

**Comment by shuler323** [comment]
Exporting will be implemented from scrach in next beta.
Please chceck next beta(1.3.0.b3) when it will be available and reopen issue if it still occurs
