### ISSUE TITLE
Disable Auto-save

### ISSUE THREAD

**Issue by Displeak** [polyend/TrackerIssues#430]
I would love to be able to disable auto save in the config menu.  That way it would be possible to change a bunch of things in a project to see if it works and if not just reload it. I always feel the pressure to  not experiment too much because of auto-saving. I know it is possible to save a different version but that can get messy rather fast. "NewTrack-2020_V.3_test2"

**Comment by hubparticipant** [comment]
This is needed

**Comment by k4ot** [comment]
yes pls i just killed a tune when loading sample in the wrong slot.

**Comment by Jacknametrouble** [comment]
This won't be possible due to the way the firmware was build initially.
