### ISSUE TITLE
[1.2.1] File Transfer

### ISSUE THREAD

**Issue by radiumxnl** [polyend/TrackerIssues#434]
### Steps to reproduce

Hi,wheni use the "file transfer protocol" and attempt to copy an entire
> pack (consisting of more folders filled with samples) my windows 10
> starts with the copying files dialog window and proceeds with the copying
> process like it should, but after a few files it fails and loses connection
> with the tracker.
> on the tracker there is the folder i tried to copy with about 5 samples
> which are copied ok, and 1 or 2 filenames (.wav) that have 0 bytes.
i have to select "start file transfer" on the tracker again to reconnect.

### Other important information

* happens every time

* Does this bug happen in previous firmware versions? > never had an older firmware version

* Does this bug happen in every project? > yes

**Comment by ambv** [comment]
I'll solve this as part of #574. Closing this one as duplicate.
