### ISSUE TITLE
[Sample editor/recorder] The ability to remove parts (f.o. silences) inside the sample, not only at start and ending.

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#453]
Functions like cut and paste pieces, or even rearranging them.
Those would be interesting to record drum samples in a row and not be worried about the silences between them occupying memory.

**Comment by tfspsound** [comment]
Is this the same request as this?

https://github.com/polyend/TrackerIssues/issues/407#issue-749531391

I agree tho. Some kind of extract / remove would be very useful. Also the ability to rearrange slices would be great.

**Comment by LetsSeeIfWeSolveThis** [comment]
Ops, yep, same. Thank u!
