### ISSUE TITLE
[1.3.0b2] Tempo resets to 130 upon restart

### ISSUE THREAD

**Issue by ilambert** [polyend/TrackerIssues#459]
Every time I turn off my tracker in the new beta, the tempo of an active, unsaved project is reset to 130, regardless of it's initial setting.

To reproduce: 
1. Open a new project. 
2. Set the tempo to anything but 130. 
3. Make a pattern. 
4. Turn the unit off.
5. Turn it back on.

**Comment by doelman** [comment]
I've also experienced this problem but not with 130 in my case, strangely enough. And it seems to actually save the tempo if you speficially save the project before turning the unit off.
