### ISSUE TITLE
[1.1.14] Tracker freezing with Roll Fx type RN3 used on pattern 3 of the enclosed project.

### ISSUE THREAD

**Issue by Jacknametrouble** [polyend/TrackerIssues#46]
Tracker is locking up on pattern 3 of the enclosed project. Occurs even after a restart. Started when I added Roll FX of type RN3 in the pattern.

[Polyend Tracker - Freeze Issue.zip](https://github.com/polyend/TrackerIssues/files/5238123/Polyend.Tracker.-.Freeze.Issue.zip)

* How often does this bug happen? - always in this particular project,

* Does this bug happen in previous firmware versions? - 1.1.14

* Does this bug happen in every project? - in this particular one,

**Comment by Unpaid-Intern** [comment]
Hello, I am the one who originally reported this bugt o Jacek, please let me know if you need additional information to reproduce this issue. Thanks! -Scott
