### ISSUE TITLE
1.3.0 b2 Master Space parameter resolution

### ISSUE THREAD

**Issue by stevesomeone** [polyend/TrackerIssues#473]
Possibly not considered a bug, but can we have better resolution on the Space parameter?
If you do an A/B comparison with the Bass Boost next to it, you will see what I mean.

* How often does this bug happen? (All the time since it was introduced)

* Does this bug happen in previous firmware versions? See above

* Does this bug happen in every project? Yes

**Comment by shuler323** [comment]
i'm sure that it would be better to have better resolution, but range 0-8 is limited by piece of hardware that generates this effect and it can't be greater than this.

**Comment by tilllt** [comment]
I am not sure, but I maybe there is a misunderstanding? IMO the parameters should be more _fine grained_ and not _more_. Setting space to "1" or "2" is not subtle at all, but extremely audible.

**Comment by tilllt** [comment]
I am not sure, but I maybe there is a misunderstanding? IMO the parameters should be more _fine grained_ and not _more_. Setting space to "1" or "2" is not subtle at all, but extremely audible.
