### ISSUE TITLE
Deleted sample in sample loader

### ISSUE THREAD

**Issue by ketumatek** [polyend/TrackerIssues#479]
1.3.0b2

In the sample loader there is possibility to deleted unused sample.
But there is no way to deleted a sample you don't want ...
Ok you can re-write with a new sample but not deleted may be it could be a nice possibility to have : 

A deleted bottom

**Comment by doelman** [comment]
It is possible, just use the device's delete button ;)

**Comment by ketumatek** [comment]
Ok thanks I didn't t see that ...

**Comment by jaap3** [comment]
Did you mean to reopen this?

**Comment by ketumatek** [comment]
No it is ok we can close it
