### ISSUE TITLE
[1.3.0b2] Performance info not updating in song mode

### ISSUE THREAD

**Issue by birdydy** [polyend/TrackerIssues#481]
Hi !

When you switch between performance mode and song mode, when returning to the performance screen, while the values are, as expected, reset, the info on the screen are still in the previous state, not reflecting the actual reset state : e.g enabled (red) tracks, reference to the pattern played per track, etc.  If you hop to pettern mode, however, then back to song and then performance, it behave as expected.  

### Steps to reproduce
Go to song
Play a song
Go to performance 
Tweak  parameters
Go to song mode
Hit continue song
After a new slot is being read, go to performance : the info you read (but not what you hear) is the "old" info.

Hop to pattern 
Back to song and perform : it is correct now.  

Always happens

**Comment by ambv** [comment]
Fixed, and also made performance mode stick on all screens except for Pattern Editor.
