### ISSUE TITLE
[1.3.0b2] Crash on Render Selection for the first time

### ISSUE THREAD

**Issue by eimhin** [polyend/TrackerIssues#482]
### Steps to reproduce

1. Make a selection in pattern view
2. Go to Render Selection, add a custom name (with spaces), select Render & Load
3. "Exporting pattern" will display and then hang/freeze at the end of the progress bar

I had to unplug the PT to restart it. This only happened once and the only thing I can think of is that the "Export" folder didn't exist on the SD yet. It was my first time using render selection. After restarting the PT, the Export folder (and subfolders) were there, but with no wav file. I performed render selection again and it's worked fine ever since.

### Other important information

* How often does this bug happen? Only once

* Does this bug happen in previous firmware versions? Not sure

* Does this bug happen in every project?

**Comment by shuler323** [comment]
1.3.0b3 has new export/render implementation, please try it
