### ISSUE TITLE
Suggestion: Improved LFO controls

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#493]
LFO is great but I'm really often missing two options: offset and sine wave. 

Would be really cool if you could add these two!

Also an LFO Amount Fx option would be really nice but I've already seen topics about it.

Thanks

**Comment by VVLVmusic** [comment]
Offset and sine, exactly what I was looking for as well, that would make the LFO section even better.

**Comment by x2db** [comment]
Agreed, also I miss delay parameter on LFO

**Comment by pinkcell-niico** [comment]
Yes delay! Good idea to mimic vibrato on long notes !
