### ISSUE TITLE
Suggestion: Better Wheel Scrolling 

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#495]
Sometimes it's hard to get the jogwheel moving to the speed you want in Sample Playback/Editor modes.
For examples in granular mode I need to turn the length setting for ages to get a long section.

What about using Shift + Jogwheel for fast scrolling (not precise) and the Joghweel alone for precise scrolling?

Thanks

**Comment by x2db** [comment]
Just to put more weight on this, the jog acceleration could be improved on some lengthy parameters in sample editor too

**Comment by bambrose** [comment]
Agreed. This would be great
