### ISSUE TITLE
[v1.1.15] Sample preview + arrows not working anymore.

### ISSUE THREAD

**Issue by djr005** [polyend/TrackerIssues#50]
### Steps to reproduce

Hi Guys, I loved in previous versions, we could continually hold down the "preview" button and cursor down using the direction arrows to preview each sample when auditioning samples to load. However, in the latest version, we can't seem to be able to do this. Cheers 

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
Every time
* Does this bug happen in previous firmware versions?
No
* Does this bug happen in every project?
Yes

**Comment by Jacknametrouble** [comment]
We're aware, this functionality will soon be back. Thank you.

**Comment by djr005** [comment]
Thanks Jacek 👍
