### ISSUE TITLE
[1.3b2] Save As... incomplete save

### ISSUE THREAD

**Issue by otternet** [polyend/TrackerIssues#501]
Hi, 

Working on a project and I wanted a backup copy so I hit "Save As", and the backup copy saves the complete project files correctly. Opened up the backup copy, project files load as expected. However, when I reopen the original project, steps and samples are missing. It seems like I should have hit "Save" to save original project first before trying to "Save As". 

Doesn't the Tracker autosaves whatever I am working on anyway?

**Comment by alexbuga** [comment]
No it doesn’t save automatically. It’s like the Elektron boxes. It saves in a temp folder. So you can resume work.
But to commit the actual work you have to hit save
