### ISSUE TITLE
Record automation

### ISSUE THREAD

**Issue by alexbuga** [polyend/TrackerIssues#504]
I tried starting live record and went to Instrument Parameters and tweaked the Cutoff. I was expecting the sequencer to record the movement. 

I know you can use fills but if you wanna tweak the filter real-time it would be awesome to record parameters in step FX.

**Comment by tilllt** [comment]
At least in Song Mode / Performance Mode it would be great if Performance FX could be recorded.

**Comment by Tombelliard** [comment]
I agree too, it will be nice to be able to record fx parameter in real time.
