### ISSUE TITLE
[1.3.0b3] Slices don’t play anymore in “Beat Slice” mode

### ISSUE THREAD

**Issue by alexbuga** [polyend/TrackerIssues#506]
### Steps to reproduce

I have a guitar loop chopped. The pattern plays only one slice. If I go to Sample Playback and tweak the slices when I play the pads, it still plays just one slice which you can’t change.

* How often does this bug happen? (every time, often, "it only happened once”)
Every time

* Does this bug happen in previous firmware versions?
No

* Does this bug happen in every project?
Will test.

**Comment by LetsSeeIfWeSolveThis** [comment]
Jhmm, I have the samples, but now on the second octave, not the third. (C2 ; C#2 ...) 
Its the same problem?

**Comment by alexbuga** [comment]
I can’t test it anymore. Rolled back to prev beta

**Comment by alexbuga** [comment]
I tried what you say but still can’t play them.
Reverted to beta 2 for the moment.

**Comment by ketumatek** [comment]
I try to make a slice on a beat on the last beta b2 firmware it was working well.
means slice begun on C3 and all the other slice was after.
Now with the new beta b3. It just play the last slice on all the pad...same as if I took an old slice I did before...
Same problem

**Comment by prds100** [comment]
I have this problem too, fixed by adding slice fx on the tracks but not ideal, hopefully this is patched out quick.  Tried altering the octaves of the notes in the step but always fell on the last slice of the sequence (also in sample playback menu)

**Comment by atav1k** [comment]
having the same problem with beat slice. only higher notes past C3, C2-B3 do not play.

**Comment by sakke-makke** [comment]
Same here. I use equal slice command and it chops the sample nicely, but it plays only the last slice. Certainly needs a fix!
