### ISSUE TITLE
[1.2.2] Feature Request: Use Copy/Paste in Sample Loader

### ISSUE THREAD

**Issue by zepi8888** [polyend/TrackerIssues#507]
Greetings. I recently got my new tracker and I am extatic. This thing boosts my creativity. Thanks guys.

Here comes my first Feature Request.

I found that I keep coming back into the Sample Loader during working on a Project. I usually pick an Instrument that's already there and add new copies of it. Later I change it the Sample Playback and use both copies of the same sample which now sound different and are separate Instruments. 

Unfortunately the path to the Sample is not in the Instrument List, and most of the time the Samples are selected from different Folders. As I understand, the only way to add a Sample to an Instrument that is already there, is to find it in the folder structure on the lift side. This can be quite complicated, because you need to find the sample first. It would be really handy (and simple) to use the copy/paste buttons in the Intstrument List, right?

Would this be a good idea?

**Comment by dustinpero** [comment]
I believe you can copy and paste in the sample loader. Sometimes you have to hit copy on the file for it to take, but I copy files and paste all the time in the sample loader window.

**Comment by zepi8888** [comment]
The idea is to copy/past Instruments in the Sample Loader (in the right box) without having to find the original sample. Eg. the pointer to Instrument Nr. 6 > press Copy > move the pointer to Nr. 7 > press Paste. 
![IMG_4309](https://user-images.githubusercontent.com/75882942/102006849-6a82b500-3d24-11eb-89dc-b7b611c2c8c6.jpg)

**Comment by zepi8888** [comment]
Ok, sorry, I just tried the "press copy multiple times" trick and it worked. That's exactly what I was looking for. 
For some reason it seemed like it doesn't work first but it does now. 
Thank you guys and sorry for the confusion.
