### ISSUE TITLE
[1.3] Big latency issue

### ISSUE THREAD

**Issue by gherat** [polyend/TrackerIssues#511]
There seems to be a really big latency problem when using midi (with use of a midi cable). It runs completely out of sync and is therefor unuseable in combination with other gear. The latency is around 20ms (!)

**Comment by clickysteve** [comment]
Is this for MIDI output (clock + notes), or input?

**Comment by gherat** [comment]
I encounterd the issue when running the tracker as a slave to ableton. When I do a -20ms clock sync delay in the preferences it runs ok.

**Comment by sebpmtl** [comment]
I feel there's a latency issue in the machine itself, like there a slight delay when playing notes with the pads and not in midi either.

**Comment by Adam-Vandal** [comment]
looks like this is reported long time ago. I'm also impatiently waiting for the fix :)
https://github.com/polyend/TrackerIssues/issues/92

**Comment by shuler323** [comment]
try 1.3.0b4, it has implemented first sync delay compensation in PT

**Comment by gherat** [comment]
Great! I’ll give it a go!

**Comment by Adam-Vandal** [comment]
Looks like MIDI compensation now works only for incoming signal, not when Tracker is as master . :( Right?

**Comment by shuler323** [comment]
@Adam-Vandal don't be sad! it will be implemented soon :)
