### ISSUE TITLE
1.3.0.b3] Stem render issues/Sample Library inaccessible after rendering stems

### ISSUE THREAD

**Issue by thebradclay** [polyend/TrackerIssues#514]
### Render a songs stems then hit sample loader

Render a songs stems

hit sample loader

Under SD card nothing is there

After rendering stems there is no audio and Ableton cannot read or load any of the files.

### Attachments and links

![PTBUG](https://user-images.githubusercontent.com/73397631/102022238-79cd2700-3d53-11eb-83de-2b06fd0f45de.jpg)

### Other important information

* How often does this bug happen? I have rendered the stems twice and this has happened both times. EDIT: I reverted back to the previous beta and rendered and it worked fine except for the problem of no audio for reverb and delay (but that is already a known issue)

* Does this bug happen in previous firmware versions? No, however the song that was rendered was made under the previous beta fw if that matters.

* Does this bug happen in every project? Yes

**Comment by shuler323** [comment]
@thebradclay please attach project which generates this bug, thanks

**Comment by thebradclay** [comment]
Hi Shuler323,
Project attached below:

[12122020TEST.zip](https://github.com/polyend/TrackerIssues/files/5704187/12122020TEST.zip)

**Comment by shuler323** [comment]
thread moved to #697
