### ISSUE TITLE
[1.1.15] Song view add/delete slot malfunction & freeze.

### ISSUE THREAD

**Issue by rpc9943** [polyend/TrackerIssues#53]
1. Create a few patterns with notes etc
2. Go to song view
3. Add and remove slots of a few patterns while song is playing
4. Stop transport
5. Add remove slots and it will not respond, sometimes triggers a sound, repeat and it will freeze

Occurs on any new project as well as a saved one

**Comment by Unpaid-Intern** [comment]
Also experiencing this issue (in 1.1.15). Also: Switching to pattern mode and back to song mode temporarily fixes the issue.

**Comment by piotr3500** [comment]
Duplicate of #67
