### ISSUE TITLE
Line In Toggle Mono or Stereo

### ISSUE THREAD

**Issue by bichan17** [polyend/TrackerIssues#548]
It would be great to be able to toggle the Line In input as Mono or Stereo in the settings, so I can play my mono instruments thru the tracker. Currently when I try to run my guitar on this input I can only hear it in one ear and there is no way to pan the line in signal.

An alternative solution could be to allow the Mic In input to be accessible in the master mix along with Line In as that input is already mono.

**Comment by sunfallz** [comment]
Definitely second this! 
In the manual it states “use a mono or stereo cable”, but:
Currently, when sampling my modular into the tracker, using a mono patch cable, i can only hear the left side out of the tracker output as well.
Example: Sampling bass to make kick drums does not require a stereo signal. 

Using a Mono cable to sample should normalize  to both left and right when monitoring output.

And/or have the option to quickly toggle mono or stereo in the sample recorder page.

**Comment by wraggal** [comment]
yes please!

**Comment by CliffRoberson** [comment]
Bump!

**Comment by sunfallz** [comment]
Bump!

**Comment by sunfallz** [comment]
Bump!

**Comment by sunfallz** [comment]
Bump!

**Comment by Jacknametrouble** [comment]
done
