### ISSUE TITLE
[1.3.0b4] Starting not Starting

### ISSUE THREAD

**Issue by db9979** [polyend/TrackerIssues#549]
### Steps to reproduce
If I push Play only the time in the upper bar starts and counts the seconds up but the track/pattern won't start. 

### Other important information

* How often does this bug happen?
Every time on all projects. 

* Does this bug happen in previous FW
In 1.2.2 this does not happen

* Does this bug happen in every project?
Yes

**Comment by dimant** [comment]
I can confirm this reproes for me too. Works fine with 1.3.0b1

**Comment by math0ne** [comment]
Same behavior here on 1.3.0b4

**Comment by isbtn01** [comment]
Same here.
Thank you.

**Comment by Timour** [comment]
Confirm same here on 1..0b4. If I switch to midi clock usb and back to internal clock, while playing, it starts playing. So seems like a clock problem.

**Comment by piotr3500** [comment]
It's fixed. 
Please download and install 1.3.0b4 once again.
Sorry for that!
