### ISSUE TITLE
Additional randomization capabilities using the Fill tool

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#55]
I hope the Fill tool can randomize ADR of instrument volume, filter respectively and start and end of sample playback. 

And I would appreciate it if I could set the pitch envelope of instruments, so I would like to request these if possible.

**Comment by piotr3500** [comment]
You can control the filter and start of the sample by using dedicated FXs.
We are thinking about adding ADR and sample end too.

**Comment by modmodmodmod** [comment]
Thank you.  I use filters and sample start a lot.  I also loop play back the samples as decay.  Still, I think it would be great if you could add volume envelope to the fill feature.  As you may already know, decay and release are especially important to composition of the songs :)
