### ISSUE TITLE
[1.3 beta 3 and 4] Beat Slice not working properly

### ISSUE THREAD

**Issue by isbtn01** [polyend/TrackerIssues#550]
Hey guys,
I came across this one by accident but its seems like in 1.3 betas (tested beta 3 and 4) the beat slice is only playing the last slice available. Even the pads are not responding to the slices (pad layout 12, chromatic scale, tried every C route available). Its happening in every project since i was checking out older stuff where i was using this and its completely changed and playing just one slice over and over in the pattern.

thanks a lot as always and keep it up!
Also get some rest during christmas, you absolutely deserve it!

**Comment by piotr3500** [comment]
fixed in 1.3.0b5 - released soon (today)
