### ISSUE TITLE
[1.3.0b1] Beat slice - always plays last slice

### ISSUE THREAD

**Issue by keith-macleod** [polyend/TrackerIssues#551]
Hi, I've just run into this problem, I can't be sure if it coincided with the latest update, but certainly not before.

When I use a sample in beat slice mode, the last slice is always played. It seems to happen both when triggered by pad and when triggered by the sequencer.

This happens with all projects.

I've tried downgrading the firmware as far as 1.3.0b1 and the problem persists. I also tried using my old SD card, which I haven't touched since 1.1, thinking maybe there was some sort of corruption in the workspace directory, but there was no change. I've also been resetting config every time.

Edit: any other suggestions as to how I can clear the state on the tracker to get rid of this condition? I'm going to try switching to even older firmwares later tonight, but thus far, it seems like this is sticking around. I would suspect hardware except this happens with both played and sequenced notes.

**Comment by alexbuga** [comment]
Fixed. You can close it.

**Comment by LetsSeeIfWeSolveThis** [comment]
> Fixed. You can close it.

It's fixed on b4 for you? I still have it.
