### ISSUE TITLE
[1.3.0b3] more filter types

### ISSUE THREAD

**Issue by jtkthx** [polyend/TrackerIssues#552]
Simple request:  In the list of filter types, options for 2-pole and 4-pole low pass and high pass filters.

Even better would be modeled filters like moog or oberheim, but I know that's a lot to ask.

**Comment by Displeak** [comment]
I like this idea ! I'm pretty sure there are some nice open source filters from the eurorack world

**Comment by bambrose** [comment]
Yeah the preen2FM open source project has some nice filters (Bass is a good one)

**Comment by fragment23** [comment]
+1 Notch and two peaks (where the peaks could be moved in spacing to each other) would be great

**Comment by danapeks** [comment]
Adding my name to this. Not hugely loving the sound on the existing filter, a few more options would be ace!

**Comment by bambrose** [comment]
FWIW I love the existing filter. One of the favourite digital filters I've ever used .. so don't change it !! just some more options would be cool if possible

**Comment by static-noise-PT** [comment]
A would prefer to first see a comb filter (would step up sound design a lot) and than on second different slopes and maybe a notch one.
