### ISSUE TITLE
[1.3.0b5] Glitch in Instruments Parameter

### ISSUE THREAD

**Issue by EridonHermetz** [polyend/TrackerIssues#554]
### Steps to reproduce

Pick any instruments

Go to the Main Parameters Instruments

Choose the Enveloppe Parameter in any mode (wavetable lfo , volume , etc etc)

Change the "Amount" Value , and ... it is still moving while you are changing AN OTHER parameter

It is locked somehow in the "Amount" parameter whatever you are doing once you selected it

The only way to "escape" the bug is to click again on "Instruments Parameter"

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
Every Time

* Does this bug happen in previous firmware versions?
Nope

* Does this bug happen in every project?
YES

**Comment by piotr3500** [comment]
Can you check if something similar happens when you change Cutoff?

**Comment by EridonHermetz** [comment]
Yes , it happens too

Every parameter , on the Automation Page (2/2)

Every time you select the Amount , you cant deactivate it and move whatever you are choosing

**Comment by piotr3500** [comment]
Got it, we're on it.
Thanks for reporting.

**Comment by EridonHermetz** [comment]
there is something to download to have this fixed ?? or should i just redownload the firmware ?
