### ISSUE TITLE
1.3.0b5 performance mode - sample position and end fx

### ISSUE THREAD

**Issue by VinceKabel** [polyend/TrackerIssues#556]
Hi, the latest beta updates seem to have turned off both of these performance fx modes. Is this a known issue? 

Many thanks

**Comment by piotr3500** [comment]
No. They work as they should. Obviously, they don't work with Granular, WT and Slices - perhaps that's the case.

**Comment by VinceKabel** [comment]
Thanks, didn't realise it had never operated with slices!
