### ISSUE TITLE
[1.3.0b5] Polyend Tracker does not sync to midi clock properly

### ISSUE THREAD

**Issue by splitradix** [polyend/TrackerIssues#559]
The below issue is while the Polyend Tracker is synced to an external clock (Clock in: MIDI In jack, Clock out: Off)

The new clock sync delay is creating new midi sync problems.

At 0.0 delay (ie off) the Tracker plays consistently 16ms behind everything else (ie, my previous bug which has not been fixed: https://github.com/polyend/TrackerIssues/issues/92)

When the clock sync delay is changed, the Tracker drifts out of time at different speeds:

Tracker midi latency set to -50: After 10 minutes the Tracker audio will be 10 milliseconds early.
Tracker midi latency set to -25: After 10 minutes the Tracker audio will be 1.861 seconds early (a much more drastic change)
Tracker midi latency set to -12.5: After less than two minutes audio the Tracker audio will be 1.750 seconds early

An easy way to test this is to load the same length drum loop into the Tracker and another sampler (I used an Akai MPC1000).

Using an 8 second sample playing at 120bpm, if you adjust the Tracker midi latency to -12.5 or -25, or a number of other values, you will hear the Tracker drift out of sync.

**Comment by bnckd** [comment]
Just to add this here as well (yesterday i opened an issue with general audio latency coming from tracker), as it seems to be part of the same problem: after this beta i had random clock glitches after every cycle - but only when sending out midi to other devices and synced internally (which happens most of the time as my tracker is the masterhub during the creative process). so on the last note the loop hangs for a splitsecond and everything else get's completely messy syncwise. when synced the midi clock delay doesn't affect / improve stuff, neither the audio latency nor the midi instability changes. 

audio > https://www.dropbox.com/s/1hwowzkgerzv2v3/glitchclock.mp3?dl=0
