### ISSUE TITLE
[1.1.15] Red edit mode may not be possible to cancel.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#56]
Sometimes It may not be possible to cancel RED mode while working on the pattern screen. Please check the video as it was linked externally.

[https://drive.google.com/file/d/1byKVikY_bJZlfJJ0AL7v0TE-qTAeUvkA/view?usp=drivesdk](https://drive.google.com/file/d/1byKVikY_bJZlfJJ0AL7v0TE-qTAeUvkA/view?usp=drivesdk)

**Comment by Jacknametrouble** [comment]
Please provide access to the linked video.

**Comment by modmodmodmod** [comment]
Excuse me.  It seems that I forgot to set the folder sharing settings.  Please check the URL as it has been updated.

**Comment by piotr3500** [comment]
It seems that the Shift button is pressed. Can you click it a few times and check again?

**Comment by modmodmodmod** [comment]
Thank you for reply.  I've been working on this and other projects since then, but the shift key is fine.
