### ISSUE TITLE
Different length of tracks in same pattern

### ISSUE THREAD

**Issue by 60pfennig** [polyend/TrackerIssues#560]
It might be not the oldschool tracker style, but why not offer some more possibilties. I think it would be nice to assign different track lengths per pattern and as far as I've read there are many more people wishing the same. So maybe it will get possible someday  :)

**Comment by tilllt** [comment]
That would enable some polyrythmic madness

**Comment by Tombelliard** [comment]
I agree !!

**Comment by gmli** [comment]
The Tracker is already doing it in performance mode, so enabling it in pattern mode should be possible. The only thing to visually change is the playing « cursor », maybe it should follow the one on the currently selected track.

**Comment by sunfallz** [comment]
Wonderful suggestion 👍

**Comment by sunfallz** [comment]
> The Tracker is already doing it in performance mode, so enabling it in pattern mode should be possible. The only thing to visually change is the playing « cursor », maybe it should follow the one on the currently selected track.

side note: When using the pattern length fx in performance mode, you're effecting every track at the same time, not individual tracks, essentially you can only have "pattern length" as an effect slot on 1 track at the moment.
so great feature request 💯
