### ISSUE TITLE
Preview on Toggle

### ISSUE THREAD

**Issue by db9979** [polyend/TrackerIssues#562]
### A new feature

In the Sample loader would be great to turn on preview (double click) and hear the preview direct by browsing through the library without pushing the preview button. 
Works actually only by holding down the preview button.

**Comment by tfspsound** [comment]
I was thinking of requesting that Pattern (screen key on the left) would be useful if I could latch that too.

**Comment by jaap3** [comment]
I think this is similar/the same as #382
