### ISSUE TITLE
Use FX track on live input

### ISSUE THREAD

**Issue by tilllt** [polyend/TrackerIssues#566]
I thought it would be great (if possible) to use a live input instead notes on a track. So basically just use the fx part of the track and instead of using it on a prerecorded sample, use it on the live input. I am sure not all of the fx can be used in realtime but some probably can, maybe this feature could be named "live fx" and just feature the ones available for realtime processing.

**Comment by jtkthx** [comment]
So basically, add live input to the instrument list?  That would be amazing.
