### ISSUE TITLE
Delete pattern shortcut

### ISSUE THREAD

**Issue by tilllt** [polyend/TrackerIssues#567]
I would love to see a "Delete Pattern" shortcut (while In pattern mode) to clear the pattern you are currently working on. I know it's fairly fast to select everything and delete, but only _fairly_ fast, not immediate like pretty much everything else on this wonderful machine.

**Comment by keith-macleod** [comment]
Also, even if you clear all the event on a pattern, it's still marked as used, i.e. the grid button remains lit.
