### ISSUE TITLE
Tracker freezes when trying to load a game [1.3]

### ISSUE THREAD

**Issue by bnckd** [polyend/TrackerIssues#572]
tried this 3 times, freezes straight away. 
the rest seems to work just like in the beta!

**Comment by bambrose** [comment]
you're pressing the black buttons (the ones under the screen without legends) to start the game right ?

**Comment by bnckd** [comment]
Of course, there's only one option, can't remember if it said load or select, I think the most right one underneath the screen.

**Comment by bambrose** [comment]
There's no legend... I just clicked them until it worked.
the second one in from the right starts or pauses the game (alternates between these two states)

**Comment by piotr3500** [comment]
There is a legend in the Games menu.

**Comment by bnckd** [comment]
I select a game with the cursor up down and press load or whatever it says
on the right, freezes.

**Comment by bnckd** [comment]
done, works, my bad. and how do you stop the game? ;)

**Comment by bambrose** [comment]
no worries :)
soft reset to restart as far as I can establish (i.e. hit the power button)
