### ISSUE TITLE
[1.3.0] stereo information is gone in exported stems

### ISSUE THREAD

**Issue by doelman** [polyend/TrackerIssues#580]
### Steps to reproduce

already briefly mentioned in #512 . Besides the fact that it takes about 5 hours to generate stems for one project (which is way too long) the exported files don't contain the stereo information (panning, LFO panning etc.) that is defined in the project. Both left and right channels are the same. 

The master file is in stereo but the tracks are not. 

Project is attached but it happens with every project

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
every time

* Does this bug happen in previous firmware versions?
yes happened in beta 1.3.0.b5 as well. It worked fine before the export behaviour got changed.

* Does this bug happen in every project?
Yes

I hope this got fixed soon, for me it's a major issue that exporting stems is not properly possible with every firmware release so far. 

[wise shoe.zip](https://github.com/polyend/TrackerIssues/files/5741821/wise.shoe.zip)

**Comment by shuler323** [comment]
thread moved to #697
