### ISSUE TITLE
Holding down << or >> when changing pattern in Song mode would continue incrementing

### ISSUE THREAD

**Issue by bgdnrz** [polyend/TrackerIssues#587]
Is it possible to create a hold condition for the << and >> buttons in Song mode (change pattern) so that if held down, the increment/decrement keeps going please? So if I hold down >>, it would keep incrementing by 1. This would be preferable to pressing >> 25 times, for example. 

Thanks kindly

**Comment by keith-macleod** [comment]
I think selecting the patterns using the grid in song mode would be a nice touch.

**Comment by eatcodeplay** [comment]
Hold + Wheel would be nice as well.

**Comment by clickysteve** [comment]
Please implement something to make pattern selection in Song Mode better. Just now it's a real pain. The suggestion from @keith-macleod would work best.
