### ISSUE TITLE
[1.3.0] Incorrect notes within scales

### ISSUE THREAD

**Issue by b8ck8tt** [polyend/TrackerIssues#589]
Hey, wonderful people of Polyend

### Steps to reproduce

1. Press "Config" button -> "Project Settings" menu -> "Pads scale" item -> Press button 6 "Change"
2. Choose a scale that has a bug (list below), press button 6 "Apply"
3. Press "Pattern" button
4. Hold "Note" button
5. Observe the notes in relation to the root

### Other important information

1. Melodic minor: it's identical to Dorian in it's current implementation. It contains b7, while it needs to be a natural 7.
2. Blues Major: since it's not a conventional scale, there are several ways to go about it, but in it's current implementation it still doesn't make sense to me. It doesn't have a natural 3rd, which I believe is a must to be called "major"; it has a b6, which is neither a part of "blues" nor a "major"; and it doesn't contain the flat 5. Something like: "R 2 b3 **3** 4 **b5** 5 **6** b7 7" would make more sense.
3. Todi scale: now, I had no idea it exists, but since I started my investigation of scales that Tracker has, I googled Todi, and all of the sources say it **should not** contain natural 4th (like it does currently), and **should** contain flat 6th (which currently it does not). Cannot vouch for it myself, but maybe it's worth for you to check out.
4. Gypsy: in current implementation it's identical to Double Harmonic scale. To fix it natural 7th should be lowered to b7. It's also spelled as "g**i**psy" instead of "g**y**psy".

I hope that helps, and thank you for continuing to improve this amazing product.

**Comment by ambv** [comment]
Extremely helpful. Thanks!

1. Fixed.
2. Changed from heptatonic blues which is arguably not very useful to proper 6-note major blues as R 2 b3 3 5 6 as defined by Dan Greetblatt, confirmed on Wikipedia, [JazzGuitar.be](https://www.jazzguitar.be/blog/blues-scales/#major) and [MasterClass](https://www.masterclass.com/articles/what-is-the-blues-scale-learn-how-to-play-major-and-minor-blues-scales#what-is-the-major-blues-scale).
3. Todi changed to R b2 b3 4 5 b6 b7 per [Hanumatodi](https://ianring.com/musictheory/scales/2379) Wikipedia page. There are other variants like [Todi That](https://ianring.com/musictheory/scales/2507) or [Raga Gurjari Todi](https://ianring.com/musictheory/scales/2379), we're not implementing those.
4. You're right that Gypsy was the same as Double Harmonic. Changed to Gypsy Minor also known as [Hungarian Minor](https://en.wikipedia.org/wiki/Hungarian_minor_scale) or "the Pink Panther theme scale" 😆
