### ISSUE TITLE
[1.1.15] MIDI Input not displaying in Pattern step record

### ISSUE THREAD

**Issue by eyeyeyeye** [polyend/TrackerIssues#59]
### Steps to reproduce

Setup:
-Playing MIDI input from external controller (Medusa) over USB (I have not tested MIDI DIN)
-Playback is stopped
-Pattern mode with record on (red cursor)

When I play notes on the controller, I can hear the Instrument being played, but the cursor does not advance, it just stays at the current step. But then if I turn the scroll wheel or use the arrow keys the cursor will jump to the step I would have been on and the entered notes appear in the pattern. So there is some kind of updating error.

### Attachments and links

Let me know if you need video

### Other important information

* Happening every time so far, in multiple projects

**Comment by piotr3500** [comment]
Yes, we need a video, please.
