### ISSUE TITLE
[1.3.0] strange midi record behaviour

### ISSUE THREAD

**Issue by bambrose** [polyend/TrackerIssues#592]
When restricting record to 1-2 tracks and using the tracker pads to record a melody there's some strange behaviour where it becomes impossible to augment the recording in the second pass around of the same loop.
I think it may be linked to the fact that the "off" is recorded.. seemingly once recorded it prevents "filling in" any gaps in the recording.
Sorry, I can't be more specific at the moment. Hard to identify exactly what the issue is.
Easily replicated by limiting the recording (armed tracks) to two channels and then trying to record a simple melody.

**Comment by XANi** [comment]
See the issue https://github.com/polyend/TrackerIssues/issues/469, that's pretty much what you're talking about, I got same problem
