### ISSUE TITLE
[1.3.0] display issue

### ISSUE THREAD

**Issue by phaelam** [polyend/TrackerIssues#605]
after going into page 2 of Instruments Parameters, and returning to page 1
![IMG_1266](https://user-images.githubusercontent.com/27602715/103182259-0bae5700-485f-11eb-8266-c7025163710b.jpeg)

**Comment by Jacknametrouble** [comment]
Also, transitions between Instrument Effects and Instrument Parameters is "moving" the amount pole from Automation to the Instrument Effects screen.

**Comment by tilllt** [comment]
@Jacknametrouble could you outline the process at polyend on how bugs are prioritized and processed? I am a bit surprised that two bugs in a plethora of bugs received the bugs confirmed tag, others, which are older, didn't.

**Comment by ziej8asek** [comment]
Duplicate of #595

**Comment by ambv** [comment]
We'll be fixing it as part of #595.
