### ISSUE TITLE
[1.3.0] Cannot use Mute/Unmute shortcut in Song mode

### ISSUE THREAD

**Issue by tilllt** [polyend/TrackerIssues#607]
There is a bug in the Master + Track selector shortcut for muting and unmuting a track in song mode. The Menu page shows up for a second and then disappears again when holding down master button.

https://youtu.be/f9VmvuShCOA

**Comment by ambv** [comment]
After consulting with the team: this is not a bug. Holding the MASTER key always focuses on changing MASTER VOLUME as it is a critical functionality. If you want to mute/unmute with Master 2/2, just short-press it, mute what you need, and short-press Song again.
