### ISSUE TITLE
[1.3.0] Cosmetic bug on file name in .mod import page.

### ISSUE THREAD

**Issue by MegaTurrican** [polyend/TrackerIssues#618]
When you try to import a mod file (specifically a .it file) that has a big name and underscore characters, the name is mixed with the transport info (see attached pics).

![issue1](https://user-images.githubusercontent.com/71126897/103358365-1581c580-4abe-11eb-8d34-96f72e448e96.jpg)
![issue2](https://user-images.githubusercontent.com/71126897/103358381-1fa3c400-4abe-11eb-9b45-42d05289ed8c.jpg)

**Comment by shuler323** [comment]
@MegaTurrican please attach specified .it file

**Comment by MegaTurrican** [comment]
[tetris_drm_tetrisbgm1.zip](https://github.com/polyend/TrackerIssues/files/5808579/tetris_drm_tetrisbgm1.zip)
