### ISSUE TITLE
[1.3] 1.1 Projects loading with issues into 1.3

### ISSUE THREAD

**Issue by mrjakeone** [polyend/TrackerIssues#619]
### Steps to reproduce

I load projects created on 1.1 Firmware into 1.3 and sample slices play back incorrectly

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

Everytime

* Does this bug happen in previous firmware versions?

No

* Does this bug happen in every project?

Everything with sample slices

**Comment by ambv** [comment]
Try changing the Root Note setting in Config/Project Settings and see if that helps. This setting used to be global, now it's configurable per-project.
