### ISSUE TITLE
[1.1.15] Repeated pad notes scale

### ISSUE THREAD

**Issue by pigeonsky** [polyend/TrackerIssues#63]
Scale function issue - The pad notes are repeating themselves on the scale i.e. press note D3 and 3 other pads light up, which are all note D3 as well. 
Also pad root note only goes from C2 upto C4. 

Wasn't happening in previous firmware versions (1.1.10 & 1.1.12)
![IMG_20200920_194148781](https://user-images.githubusercontent.com/71585704/93719702-2d22e700-fb7c-11ea-87f6-a58d06c9aec6.jpg)
![IMG_20200920_194158102](https://user-images.githubusercontent.com/71585704/93719704-2f854100-fb7c-11ea-9ab8-ace3cb9ba418.jpg)

**Comment by piotr3500** [comment]
Grid/scale editor will be rebuilt totally in next updates.
