### ISSUE TITLE
[1.3.0] Fill problem

### ISSUE THREAD

**Issue by topheb** [polyend/TrackerIssues#638]
fill type selected : from-to
Fill 8 step
Track1 : C5 to C6 Major.   OK
Track2 : F5 to F6 Major.    KO
Track3: C5 to C6 Ukrainian.  KO
Track4: F5 to F6 Ukrainian.  KO

For Result , see enclosure

Thank you for your attention
Christophe

![IMG_20210103_230105](https://user-images.githubusercontent.com/59713911/103489850-bc949300-4e17-11eb-8821-486473585ca2.jpg)

**Comment by wjakobczyk-polyend** [comment]
This is fixed and will be available in next release.
