### ISSUE TITLE
Save collections of instruments as 'kits' to load in to projects

### ISSUE THREAD

**Issue by seanlclarke** [polyend/TrackerIssues#641]
I realise this can be done by just making blank projects and saving them with instruments in, but it would be great if we could save 'kits' of say XX samples that could be loaded in to a project in the next XX slots. People can then make 'drum kits' for example that can be loaded in with one click without overwriting other samples...

**Comment by modulationsource** [comment]
This would be nice. Would also open the possibility to preserve instrument information.
Imagine sampling a synth on different notes, apply semitone offst, loops and filter options and save them as kit.
This would be a kind of mutlisample.

**Comment by LetsSeeIfWeSolveThis** [comment]
Absolutely

**Comment by seanlclarke** [comment]
I pretty much always start by loading 4-5 drum samples that work well together  (kick, snare, hat, clap, crash etc) on every project, so being able to load say 'D&B Kit' would be a real time saver  and hopefully not too hard to add ('save instruments as kit' option and a load 'kit' option in the samples page.

**Comment by sprottenkopf** [comment]
Good idea! I was myself thinking in line of saving instruments as separate instrument files. The way its done in Milkytracker and Fasttracker. Those files include all settings and audio files.

**Comment by Jacknametrouble** [comment]
This has been added in the newest 1.5b1 beta.
