### ISSUE TITLE
[Firmware 1.2 to 1.3] update failed

### ISSUE THREAD

**Issue by tweetch** [polyend/TrackerIssues#645]
### Steps to reproduce

i'v buy today a new tracker
its in 1.2 so i'v download the 1.3 and the tool on the site.
method via polyend tool stuck a "100" and i ' w waited more than 10 mn
method via the 1.3 file directly inside the "/firmware" folder say "update failed"
any clue ?

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

* Does this bug happen in previous firmware versions?

* Does this bug happen in every project?

**Comment by Jacknametrouble** [comment]
@tweetch - restart your unit, see if it updated to 1.3 on the start screen.

Read - https://github.com/polyend/TrackerIssues/blob/master/HOWTO_BETA_FIRMWARE.md
The end section about other possible ways to flash your unit.

If the issue persists, use - https://help.polyend.com/submit_ticket for customer support.r
