### ISSUE TITLE
[1.3.0] Text and Selection Glitch in Instrument Effects Menu

### ISSUE THREAD

**Issue by sunegg1024** [polyend/TrackerIssues#647]
### Steps to reproduce

On all save files I have, if you select an instrument, go to Instrument Parameters and then to Effects, roughly 25% of the time the Overdrive and Bit Depth text will be covered by (what looks like the word) Destination and only the Overdrive will be selectable and editable. The Bit Depth is not accessible unless you go back, change the Instrument and navigate fully back in.

### Attachments and links

![IMG_20210106_171827](https://user-images.githubusercontent.com/77073782/103832405-d1ee0500-5043-11eb-9b39-16a629055f44.jpg)

### Other important information

* How often does this bug happen? About 25% of the time or more. It has happened to me a lot in the span of a week or so of having the device.

* Does this bug happen in previous firmware versions? I have not confirmed this on other firmwares.

* Does this bug happen in every project? Yes.

**Comment by ziej8asek** [comment]
We'll be fixing it as part of #595.
