### ISSUE TITLE
Other Frequency-Bands for internal Radio?

### ISSUE THREAD

**Issue by tilllt** [polyend/TrackerIssues#648]
More of a question than a feature request:

Since most SDR Circuits can do multiple Frequence-Bands, would it be possible to have AM  or even Longwave Radio?
I remember that AM and Longwave have much more interesting interference sounds (and radio stations from faw away), so as a base for sampling that would be maybe even more interesting than FM.

**Comment by cesiumswimsuit** [comment]
I wondered if this was possible too, would be an excellent addition to have access to AM as well. When live shows are more possible it will be great to grab local snippets to cut up into tracks
