### ISSUE TITLE
Allow playback while in Sample Recorder

### ISSUE THREAD

**Issue by 0x0zzz** [polyend/TrackerIssues#649]
Currently, while in Sample Recorder, pressing the Play button does nothing.

Starting playback in this mode by pressing the Play button would help with recording performances played on external instruments through Line In along with the current pattern you are working with (i.e. acoustic and other instruments without MIDI).

An alternative to this could possibly be a metronome in the Sample Recorder, if there is some technical reason why this isn't feasible.

**Comment by synthexpert** [comment]
This would be a great feature!

**Comment by gurkenkimchi** [comment]
would be also great if you return back to the sample recorder page after recording line in saving and loading a sample rather than a jump to the instruments page.

**Comment by Goldfasan** [comment]
Considering the competition (4o4mk2), this would be a high value feature... This alone is a decision maker, simple and ingenious.
