### ISSUE TITLE
[1.3.1b1] Roll, R1-12 Rv1-16 broken

### ISSUE THREAD

**Issue by thebradclay** [polyend/TrackerIssues#654]
### Steps to reproduce

Open a  1.3.0 project with rolls.  Had three hard freezes immediately after power up. Also frozen during an attempt at rendering stems.

Open a new project in 1.3.1.b1. place a sample in a step, add a roll, watch the magic.  Specifically the Rv1. it just continually rolls. RV1-RV16 produced no sound with. Rn all fine, RN fine, RR fine(? I guess are okay but I have no clue what the random parameters are and never use it)

Please get the stem rendering and sync issue fixed or I won't be able to continue to use the tracker and that makes me sad.

### Attachments and links

[TCB Mix song.zip](https://github.com/polyend/TrackerIssues/files/5789361/TCB.Mix.song.zip)

### Other important information

* How often does this bug happen? The roll issue happened in the 1.3.1b1 while using a project that had been composed in 1.3.0.  However, Roll is broken in new projects created in 1.3.1b1.  

* Does this bug happen in previous firmware versions? No

* Does this bug happen in every project? So far

**Comment by shuler323** [comment]
@thebradclay thanks for reporting that bug. Sorry for having much trouble with exporting. I can assure you that we working on it as much as we can. I think that some new beta that fixes some problems will appear next week.
