### ISSUE TITLE
1.3.0 Tracker Freezes when accessing empty games tab/folder from the file menu.

### ISSUE THREAD

**Issue by Goldfasan** [polyend/TrackerIssues#661]
Tracker Freezes when accessing empty games tab/folder from the file menu.
No way to exit the games selection menu, seems to be frozen.
I have no games in my folder...
Recreate by: Turn on Tracker, press file button, press games tab, viola

**Comment by Just-Peter** [comment]
Solved in 1.3.1b1

**Comment by ambv** [comment]
Indeed, fixed in 1.3.1b1. Please wait for the official release of 1.3.1, that will fix it.
