### ISSUE TITLE
Tune of Performance FX pitch the Midi Channel Tracks

### ISSUE THREAD

**Issue by loktez** [polyend/TrackerIssues#678]
Hi everybody !
Hope you're fine

Could we imagine that the Tune section in performance FX mode could interact on MIDI notes for MIDI channel tracks ?
Like the samples  -48 / 48 ? 
The possibility to tweek the pitch of external gears, could be extreme ! 

my best !

**Comment by snesmeister** [comment]
This would be brilliant. Why closed?
