### ISSUE TITLE
[1.3.1.b2] MIDI CC Out setting is GONE :(

### ISSUE THREAD

**Issue by phaelam** [polyend/TrackerIssues#695]
I cant locate the place to set the MIDI CC Number anymore. the MIDI > Out setting is gone. this is really sad :(
PLEASE bring that back. thats a BIG one

I went back to version 1.3.0b2 and MIDI Out was there. was that forgotten in latest or has it been removed. that was an AWESOME feature.

please bring this back
<img width="904" alt="Screen Shot 2021-01-14 at 10 47 43 PM" src="https://user-images.githubusercontent.com/27602715/104691184-9cd45900-56ba-11eb-9955-f70d4cf4f3a6.png">

**Comment by talktogreg** [comment]
MIDI CC's are now settable for each MMxx (when selected as instrument on a track).

To access settings, select MMxx (ie MM01 for Channel 1), then when you click <Instrument Parameters> you'll see all the settings for that MIDI channel, which will then be used for any other Step using the same Channel.

**Comment by Just-Peter** [comment]
This is not a bug. The developers changed the use of it, far more flexible.

**Comment by phaelam** [comment]
ya I just came back to delete this...found it the change. thanks
