### ISSUE TITLE
[1.1.14] Tracker as MIDI slave to Seq gets out of sync and freeze

### ISSUE THREAD

**Issue by Jacknametrouble** [polyend/TrackerIssues#7]
The Seq is a master clock. On the video, we can hear the progressive shift between the two Kick and at the end, the tracker stop and freeze. I have to unplug tracker for turn it off. When the clock is internal there is no problem.

Additional questions to answer:
Does this bug happen every time or just once? - Always,
Does this bug happen in previous firmware versions? - Hard to say,
Does this bug happen in every project? - Doesn't matter,

**Comment by pandamaschine** [comment]
all ready the same problem on 1.1.15 but without freeze .
no problem on 1.1.12
