### ISSUE TITLE
[1.3.0] External CC modulation of performance fx not working properly

### ISSUE THREAD

**Issue by sunfallz** [polyend/TrackerIssues#709]
Incoming CC modulation of performance fx not functioning properly. Glitchy, unstable. Not registering proper values reflective of assigned modulation amount.
Also, incoming performance fx CC's stop working when exiting performance page.

example:
- Midi CC51 is for slot one in Performance mode, i set it to Pattern Length 
- i could only get the Pattern Length external modulation to kind of move in increments of 1, 2, 4, 8, 16. 
Nothing in between and nothing over, and it was extremely glitchy at best. not really holding on any one value that was set. 
so not optimal just yet. hopefully an update will allow for any length modulation from 1-128
steps within a pattern
- Just thought I'd add: gear used for external cc's: digitakt, digitone, deluge.

* How often does this bug happen? - every time,

* Does this bug happen in previous firmware versions? untested in previous firmware

* Does this bug happen in every project? Yes

**Comment by piotr3500** [comment]
The values fo Pattern Length are fixed to values: 1, 2, 4, 8, 16.
It has nothing to do with CC messages.

**Comment by sunfallz** [comment]
> The values fo Pattern Length are fixed to values: 1, 2, 4, 8, 16.
> It has nothing to do with CC messages.

Thanks for the clarification. So CC values we are to enter for Pattern Length are locked at 1, 2, 4, 8, 16? 
That is odd to say the least. Reckon this should've been listed as a feature request.
Cheers
