### ISSUE TITLE
Pattern Length FX

### ISSUE THREAD

**Issue by tfspsound** [polyend/TrackerIssues#715]
So I think it’d be cool if the Performance FX Pattern Length should apply from the step you apply it to. So if Pattern length is set to 8 steps and I trigger pattern length on step 4 as the pattern is playing it would loop the pattern between steps 4 and 12.

**Comment by anemlife** [comment]
I agree, this could also be a new perfomance FX called "looping" maybe so it wouldn't affect the actual way it works!
