### ISSUE TITLE
[1.3.0] Pattern button + Arrow = Delete?

### ISSUE THREAD

**Issue by thebradclay** [polyend/TrackerIssues#716]
### Steps to reproduce

Over the last few days I've noticed that occasionally while listening to patterns play when I press the pattern button (the one on the right, beside fx2) and an arrow key sometimes my pattern will delete. Once the pattern is deleted I press undo and it returns. This has happened just now but I can't consistently reproduce it. It seems to happen if I press the  button combo right as the pattern is ending.

### Other important information

* How often does this bug happen? Seems random but more likely if the buttons are pressed as the pattern is ending

* Does this bug happen in previous firmware versions? Not that I am aware of

* Does this bug happen in every project? Has happened in three so far.

**Comment by piotr3500** [comment]
Are you sure that this combination doesn't change the pattern (from one to another)?

**Comment by thebradclay** [comment]
@piotr3500 It does change the pattern. What I am saying is that it has also deleted the entire pattern occasionally that is why the title has a question mark. As in why is this happening.  So to clarify yes it does change the pattern, which it should do. However, this same combination has also resulted in deletion of the pattern which it should not.

**Comment by piotr3500** [comment]
Got it, thanks for clarifying.
We'll look into it.

śr., 20 sty 2021 o 13:41 thebradclay <notifications@github.com> napisał(a):

**Comment by ambv** [comment]
Repro: https://www.dropbox.com/s/yuum0lduu4vtcxg/PatternDeletedByWellTimedSwitch.mov?dl=0

**Comment by ambv** [comment]
An easier repro is that you can confuse the sequencer by letting go "sync pattern change" on last step of pattern, current pattern number doesn't get updated but the new pattern gets loaded.
