### ISSUE TITLE
Suggestion --> Faster access to some of the configs

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#720]
I think that some of the options you can find in Config mode could be more/easily accessible to enhance the workflow.

Example:

1) **Metronome**: an option to turn it on off in pattern view would be great! Pattern view is the one where you record everything so having access to the metronome here would be more useful than always going to the config menu!

also to mention ==> I know that most buttons are already used for options in pattern view (fill, shrink, etc...) but organizing these in submenus (shrink/expand/invert in one submenu, copy/paste/duplicate in another one, render options in another one, etc...) could allow for more options in the pattern view! (metronome on/off, clear pattern, etc...). This is just an idea here we go before I forget it!

2) **Pads scale/root/layout**: This is a really important one in my opinion. 
I think that the Note layout (the one that shows every note for every pad when you keep the note button pressed) could also be used to switch between scale/root/layout. 
Having a visual representation of what changes you do to the pads + an access to these options without leaving the pattern view would be killer!! It's kind of limiting to get only 4 complete scales and to go to config every time you want to do a more complex melody. Also when youuse a scale and want to go back to a sliced instrument. 

3) **MIDI Settings**: I think we should get an option to record 3 "profiles" of MIDI options and switch between these. I use all type of clocks settings so I keep having to change these but it takes times! Having access to 3 user profiles would be 100% faster as we could set these to our general needs and switch these with a simple toggle!

These are the 3 configs that should be usable "faster" in my opinion but let me know If I forgot anything!
Also sorry about the big topic but these were all kind of related!

**Comment by Displeak** [comment]
Midi profiles is such a great idea !
