### ISSUE TITLE
Play pause, resume from current position

### ISSUE THREAD

**Issue by phaelam** [polyend/TrackerIssues#724]
...would be a nice addition.

**Comment by talktogreg** [comment]
Doesn't shift-play resume?

**Comment by phaelam** [comment]
Just shift? I was pressing shift+play. 
I swear I tried shift, I went rando trying. I’ll check tomorrow. My day has come to an end.

**Comment by Just-Peter** [comment]
Shift-Play resumes from current position in Track view. Please close this issue.

**Comment by phaelam** [comment]
you are correct sir.

**Comment by hubparticipant** [comment]
A way to playback from the position the playhead was stationed previously would be a very welcome addition. 
It’s hard to explain. 
So if you put the playhead on step 17. A combination of let’s say LEFT+PLAY will start the sequence on step 17, regardless of the position of the playhead. Or an extra function button can be added: START FROM CURRENT POSITION / SET CURRENT POSITION AS START POINT FOR PLAYBACK. 
Add to this a loop playback selection. 

Currently Preview Selection works well enough though.
