### ISSUE TITLE
Save pattern library

### ISSUE THREAD

**Issue by eclectocrat** [polyend/TrackerIssues#736]
Hi, sometimes one makes a great drum beat or musical phrase that doesn't quite fit into the current song but you would like to save. It would be great to have a "pattern library" that you could quickly add selected phrases to, like "drum brk A", or "theme 1", and then copy those phrases out in any project you are in.

**Comment by Jacknametrouble** [comment]
Check the 1.5 beta1 with the capabilities of saving instruments with all their properties. Not exactly the same thing but may speed up your workflow in a similar way.
