### ISSUE TITLE
Audio export

### ISSUE THREAD

**Issue by Matti14** [polyend/TrackerIssues#750]
Hello, i have a problem with the song audio export. The panning is after the export reversed. An example: i have the bass on the right side. Hear the wav file then the bass is on the left. Same with the other sounds. Firmware is on 1.3
I know there is a equal report, but with no solution.
I am the only one with this problem?

**Comment by doelman** [comment]
No you're not the only one and you're right, I've already created an issue
for this quite some time ago.

**Comment by ambv** [comment]
This is fixed in 1.3.1b3.
