### ISSUE TITLE
Suggestion --> Perform mode: option to record the output as a "stem"

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#773]
It would be crazy if we could record the output of the master when playing in Performance mode with let's say a pre-defined limit in steps for every recording (128/64/32 step recording, etc...). Not sure about the way this could work but it would be super useful to manipulate the samples in a deeper way.

Example: 

- I set the Perform mode as I want (choosing each pattern for each track, muting the ones I don't need etc...)
- I set the Perform parameters as I want them. (step repeat, reverse, etc...).
- I press on "record performance" (no idea how this could be implemented)
- The tracker asks for the length of the recording in steps. I chose the one I want.
- I press play, perform the pattern as I want, it gets recorded and we're done!
- The file could then be renamed as we want and finally get saved to the export folder in a "Perform" subfolder!

Thanks :)

**Comment by synthexpert** [comment]
This would be a huge improvement! Please you guys at Polyend add this :)

**Comment by tfspsound** [comment]
I think I read a similar idea to this towards the end of last year it’s a neat idea. I’d like to see a second performance screen with another grid where you could store ‘presets’ of performance mode fx combinations so you could change all fx simultaneously to your own predefined configurations.
