### ISSUE TITLE
External midi controller - request for on+off for Mute/Solo/Rec

### ISSUE THREAD

**Issue by danapeks** [polyend/TrackerIssues#774]
Hey there 

Please could we have the option to map on/off midi cc to mute/solo/rec functions on controllers like the Korg Nanokontrol or Novation Launch control XL? Be super helpful so we can use when doing live performances. 

Alongside this be great to be able to set maximum CC values for external controllers - am finding volume faders are tricky to use on my nanokontrol as pushing them fully up pushes the vol super high, be cool to be able to limit it without setting the vol of a channel really low. However, if could just use the mute function on the nanokontrol this would not be as much of an issue

Thanks

**Comment by phaelam** [comment]
I second this. MUTE CC would be smurvey

**Comment by static-noise-PT** [comment]
Yes mute and solo at least please
