### ISSUE TITLE
[1.3.1b3] Recording Microtiming broken

### ISSUE THREAD

**Issue by aheger** [polyend/TrackerIssues#778]
### Steps to reproduce

- Enable recording with Microtiming
- Start Recording Pattern
- Randomly press notes

Expect:
- Microtiming is recorded correctly

Actual:
- Microtiming is 2

### Attachments and links

https://user-images.githubusercontent.com/55574996/107122707-9f7d3500-6899-11eb-98fe-e896e3ef9a2f.mp4

### Other important information

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? Did not notice it before

* Does this bug happen in every project? Yes

**Comment by Just-Peter** [comment]
This is a known bug. It will be fixed in the next firmware, I read.
