### ISSUE TITLE
[1.3.1b3] Only one SOLO supported

### ISSUE THREAD

**Issue by talktogreg** [polyend/TrackerIssues#786]
In my experience (for what that's worth haha), Mixers allow for more than one Track to be SOLO'd at a time.

Tracker currently implements SOLO as an anti-MUTE, so SOLOing a Track actually just MUTEs all of the others. I believe the correct logic should be:

1) if ANY Track is marked as SOLO - play all Tracks marked as SOLO and MUTE all others, regardless of MUTE states
2) if NO Tracks are marked as SOLO - play all Tracks not marked as MUTE.
3) Toggling of the SOLO state of any Track shall not alter/reset its MUTE state setting

Please note I consider this a very 'gentle' bug - and almost a 'Feature Request' as how it works now may simply be as you intended.

**Comment by tfspsound** [comment]
Was about to submit a request to change the behaviour when solo is turned back off but then I found this which covers it in point 3. 

If a track is muted when another track is soloed surely when it is unsoloed the track that was muted should remain muted and not unmuted as is the case now. 

Soloing multiple tracks simultaneously would also be very helpful.
