### ISSUE TITLE
Naming the cells in songmode

### ISSUE THREAD

**Issue by rotarycuff** [polyend/TrackerIssues#787]
It would be great to be able to name the cells in the song mode, so it becomes easier to remember/see what is what when copy pasting. 

The tracknaming on the top is already something, but just being able to name the cells in the actual grid by number for example, would make the overall overview for copy/pasting even better. (Even if it would only allow 2 or 3 digits to fit within the cell, but i think there is space for more like: intro, bass 1, bass 2,...

**Comment by rotarycuff** [comment]
Posted in #535

**Comment by ketumatek** [comment]
related post #421 and #535

Agree with you it will be easier for song mode if we could add colors and names...because just number it is for me to confusing...

**Comment by LetsSeeIfWeSolveThis** [comment]
#363 I wrote this time ago, could be the same thing.

**Comment by rotarycuff** [comment]
Ah yes indeed. Will lock this one then.
