### ISSUE TITLE
[1.1.16] Pattern button + Arrow keys doesn’t advance pattern

### ISSUE THREAD

**Issue by eyeyeyeye** [polyend/TrackerIssues#79]
Thanks for adding the functionality to hold the pattern button (the one on the right) to change patterns. It works fine with the scroll wheel, but not with arrow keys. If you press the left and right keys pattern on the left will blink red and display the new pattern # but will not switch to the new pattern when the current pattern ends. Up/down have no change.

**Comment by AirDnB** [comment]
This happens on mine as well (1.1.16)
However it does work if you use the Up and Down arrows, as opposed to the L and R keys.

Cheers,

Julian
