### ISSUE TITLE
micro timing disabled?

### ISSUE THREAD

**Issue by BlakRainbow** [polyend/TrackerIssues#792]
When I play notes while live recording the tracker does not record micro timing, so if I'm trying to play a triplet or anything other than a strait 8th note some of the notes get cutoff by OFF messages created by the tracker. This happens with an external keyboard or the tracker pads.

### Attachments and links

Often the best way to show the problem is to record a short video,
attach the Tracker project you were working on, and provide links.

Pro-tip: You can drag and drop images and `.zip` files directly to the edit
box when writing your bug reports. Videos are too big as attachments, you
will have to use an external service for this and provide us links. Please
don't use services that delete files after short periods of time.

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

* Does this bug happen in previous firmware versions?

* Does this bug happen in every project?

**Comment by ambv** [comment]
This is handled in #778.
