### ISSUE TITLE
OFF message option

### ISSUE THREAD

**Issue by BlakRainbow** [polyend/TrackerIssues#793]
ability to turn off the automatic OFF messages created by the tracker when live recording with an external midi keyboard.
The OFF messages end up muting half of the notes I'm trying to play on the keyboard.

**Comment by talktogreg** [comment]
Hi. See my note re:MONO mode. I think we're on a similar page here.

**Comment by BlakRainbow** [comment]
ah yes, definitely. I'm also having a hard time with held ON notes when sequencing external gear. 
It really sucks when you're trying to sequence a hardware synth with the tracker. Im used to being able to enter notes on a sequencer and have them trigger a 16th note (or whatever the grid is set to) while adjusting the adsr on my actual synth for note length...

**Comment by Andreuparri** [comment]
Hi, I also asked for an automatic note off in here which would allow to set step length for new entered steps.
https://github.com/polyend/TrackerIssues/issues/779#issue-802795685

**Comment by topherdavis** [comment]
+1

**Comment by SahidH** [comment]
+1
