### ISSUE TITLE
[1.3.1 beta3] Delete unused samples not working

### ISSUE THREAD

**Issue by MrMolletta** [polyend/TrackerIssues#800]
Hi!New to the tracker world!Nice maschine!

In the samples loader screen, the function delete unused samples doensn't works. It simply do nothing instead of purging samples.

Many thanks!

**Comment by BenisonBT** [comment]
Same here

**Comment by MetabaronCZ** [comment]
Yes, I can also confirm this. I think in 1.3.0 it worked corrrectly

**Comment by thebradclay** [comment]
It did work for me in 1.3.0 but doesn't work for me in the 1.3.1b3.

**Comment by modmodmodmod** [comment]
+1. I'm also suffering from this bug on 1.3.1b3.

**Comment by soffer** [comment]
Same here
