### ISSUE TITLE
Enhancement: Shift+Wheel for moving cursor left/right on Pattern View

### ISSUE THREAD

**Issue by ConnorCarbon** [polyend/TrackerIssues#807]
**### Shift+Wheel Turning for allowing left/right cursor movement without the hand leaving the wheel in Pattern view or possibly Globally?**

This one is pretty simple and I have noticed that this control combo is currently not assigned to a function, at least not in the Pattern view. The knob is great for scrolling up and down a track but to go left or right, it's all about repositioning the hand off of the knob and/or onto arrow keys, etc.

The idea here would be to allow holding SHIFT+Turning Knob left or right to move the cursor left/right (at probably a less rapid rate than up/down's rate / acceleration rate). For users with average right hands, this allows the right index or middle finger to rest very comfortably on SHIFT while the rest of the hand turns the knob as normal, and the difference between scrolling up/down with the knob and left/right with it would then be only a press/release difference on the SHIFT key!

Edit: I forgot to mention that another benefit to this isn't just about the slight time saved from having to get a few fingers to land on the arrow keys (without accidentally hitting insert or backspace, which can be a big oops), but it's also about how the accelerative turn rate of the wheel going left/right can get people across the 8 tracks (or other horizontal scrolling) much faster. Right now, there's no shortcut like SHIFT+HOME that will snap to the far left or far right, or anything, so to zip across as many as 8 tracks, a user has to either press the arrow keys a bunch of times super rapidly (fast but primitive and clacky to other people in the environment) or press-and-hold LEFT or RIGHT to wait for the keyboard-input acceleration rate to kick in, which is quieter but takes longer and feels kind of defeating to wait for when there's only 8 items to scroll across.

So, this shortcut would defeat that user-choice snafu between being bored and looking/sounding like they had too many cups of coffee every time they try going from Track 8 to 1 and back. With SHIFT+WHEEL, they could move the knob left or right slowly and precisely to jump over to the next track and save themselves from having to employ their brain's "dexterity switch" onto the keyboard (more brain power for other thoughts related to song workflow) yet they could also jam the wheel hard to zip right over to Track 8--faster, with less effort/distraction, _and_ without looking hopped up on caffeine and clacking the ears off of people around them, ha!

EDIT 2: Oh! And this would be massively helpful for menus with a lot of left/right scrolling usefulness, like the Instrument Parameters page, some of the Master pages, and more! Allowing SHIFT+KNOB L/R to move from "Volume" to "Panning" and "Tune" and "Finetune" and "Filter Type" and "Cutoff" and "Resonance" and "Effects" could be a great alternative to the other ways of getting there (like pressing the corresponding button or using the arrow keys.) In this case, it's not nearly as big of a deal, but it would help improve one-hand operation on these screens, again avoiding having to use any brain power to "find" the arrow keys or move fingers back and forth. This section is just an extra bonus of taking this shortcut global, as I mention below.

That's about it, other than noting this shortcut could be global to the tracker wherever scrolling left/right was applicable, on present and possible future menus that could benefit from users being conditioned for this method of input.

It's not dire, because of course the arrow keys can do this, but the repetitious repositioning of the hand back and forth between the keys and the knob eats up probably 1-2 minutes of time every hour session of use. After mastery (1,000 hours of use, let's call it), that might waste 16-33 hours of each user's time toward mastery on repositioning their hand to move the cursor a different direction and then resume knob control. If the user's professional "Work time" is worth $20/hr, that'd make adding this feature to the Tracker cause it to be $332+ more valuable to each user by the time they've mastered it.

If there are other plans for using up this shortcut that could fill a need that is otherwise not available on the Tracker through other control methods, I wouldn't worry about it, but if that shortcut mapping doesn't have any big plans, then I think adding this would be a huge time-saver, add to fluidity of control and user experience, and add value to each Tracker for each user.

**Comment by tfspsound** [comment]
Personally I was hoping Shift + Jogwheel would increase the speed at which we could scroll through a waveform in Sample Playback and Sample Editor. That takes up far more of my time than moving left or right across the tracks. I agree though that going from Track 1 to Track 8 could be done quicker by screen wrapping the left and right like they do top to bottom. 
As there are only 48 sample slots I find it useful to use lots of sliced samples, I’d prefer to have a Jogwheel that lives longer than getting back very small amounts of lost time. I know there is the zoom function and I’m gradually getting used to jumping between Zoom and Adjust so my Shift + Jogwheel suggestion may also be redundant anyway. 
Not sure if holding Shift and turning Jogwheel on Master screen would be a quicker way to go through Filter and Fine Tune etc when there is a Screen/F key already assigned to that job.
Another quick point, if you were getting paid by the hour to make music wouldn’t it be in your interest to have the process take longer? You’d be out of pocket by at least $320 right?
Any way just adding my thoughts on this for discussion, I think we both agree there should be an alternative way of getting from Track 1 - 8 quicker and hitting Insert or Backspace by accident is a nightmare I’m so glad we have undo. 
Peace

**Comment by ConnorCarbon** [comment]
> Personally I was hoping Shift + Jogwheel would increase the speed at which we could scroll through a waveform in Sample Playback and Sample Editor.

That is absolute necessity! But I think the Knob's acceleration functionality should apply to scrolling (and start and end-point movement, etc.) in the sample editing menu(s). It shouldn't even be a shortcut, unless the Knob's "rate-acceleration" can't be put to use on that screen.

You should search or there are already open issues about that and if not, make one, because it's a pet peeve of mine too. It is excruciatingly slow to move across a sample. Zoom can help, but not nearly as much as increasing the "scrub speed" as a video editor would call it.
