### ISSUE TITLE
Scale Mode / Keyboard layout should be project specific

### ISSUE THREAD

**Issue by SerrArris** [polyend/TrackerIssues#83]
Dear all!

I add this feature request I already submitted via Mail, as it can not be found in GitHub yet:

It is useful that randomization sticks to the currently used scale. However, this is a global setting and when switching between projects with different keys, this causes problems (especially if one uses the Random Note FX). One must always remember the scale of the project and adjust the grid/scale accordingly.

Best regards,
   Markus

**Comment by jaap3** [comment]
I believe this is now possible with firmware version 1.3.0
