### ISSUE TITLE
Recommendation on SD card formatting

### ISSUE THREAD

**Issue by karachinsky** [polyend/TrackerIssues#832]
[The link](https://help.polyend.com/784248-What-size-SD-card-can-be-used-and-whats-the-file-partition-format-used) at FAQ only offers an app for Windows.

**Here is a simple Mac terminal command:**
`sudo diskutil eraseDisk FAT32 SDCardNewName MBRFormat /dev/disk3`

disk3 — SD card number could be found with `diskutil list` command.

**Comment by hepto** [comment]
Pretty sure I formatted my 256GB card with Disk Utility and it works fine.
