### ISSUE TITLE
[v1.3.1 beta 4] Visual glitch on song mode when changing of slot.

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#843]
https://user-images.githubusercontent.com/72809187/109492795-6775a600-7a83-11eb-8c48-d4083b07bc37.mp4

When I let the song mode change between slots naturally, I notice the two columns trembling (slot and pattern, not the 8 track columns or tempo colums, only those two; slot and pattern)

**Comment by eholzbach** [comment]
I experience the same, but I'd argue this is a feature. Extra visual feedback while entering another pattern is fun.

**Comment by LetsSeeIfWeSolveThis** [comment]
They didn't mention new features, just fixed. But I will try to think the same you think, it's a band aid to my anxiety.👍🏼

**Comment by jaap3** [comment]
Yeah I see it happen as well. Doesn't look intentional
