### ISSUE TITLE
[1.1.16] Sample isn't played from very start in pattern mode or sample playback window (EDIT: Was due to ENV attack being set to 0.010s by default)

### ISSUE THREAD

**Issue by splitradix** [polyend/TrackerIssues#85]
I loaded a few samples onto the SD card.

When I import them they play fine in the sample editor window, but in the sample playback and in pattern mode the start of the sample has been moved forward by a few milliseconds, so I'm not hearing the start of the sample. I can

This happens even though I haven't adjusted the start time of any of the samples (start time is 0.000s for everything).

**Comment by Jacknametrouble** [comment]
Hey, I cannot reproduce this issue. Can you please zip and link us the particular project where this happens? Thank you.

**Comment by teamoth** [comment]
Probably a daft suggestion, but I was wondering if this might be an attack issue? Also I notice that the default attack is 0.010s for instruments and the volume envelope that deals with ADSR is on by default.

**Comment by splitradix** [comment]
[bug.zip](https://github.com/polyend/TrackerIssues/files/5278607/bug.zip)
Project attached.

**Comment by splitradix** [comment]
Just after I exported the file I noticed that every instrument had an attack setting set to 0.010s despite me not specifying that when loaded them into the new project. This may be human error but I'll try to load a few more samples to see if I can reproduce.

**Comment by splitradix** [comment]
> Probably a daft suggestion, but I was wondering if this might be an attack issue? Also I notice that the default attack is 0.010s for instruments and the volume envelope that deals with ADSR is on by default.

I just saw your comment and I am seeing the same thing.

**Comment by teamoth** [comment]
If dialling down the attack to zero fixes the issue then I guess the bug to be fixed here in the next version is to have zero attack as the default. Perhaps also the volume envelope shouldn’t be switched on by default?

**Comment by bambrose** [comment]
I would agree. I initially didn't clock the 0.010 attack time which renders any percussive samples 'dull'
I would politely suggest probably better to have a default of 0

**Comment by Stazma** [comment]
I'm also voting for a default attack time of 0 !

**Comment by splitradix** [comment]
> I'm also voting for a default attack time of 0 !

Actually the envelope is technically an effect, like the filter. It should be off by default.

**Comment by piotr3500** [comment]
Agreed, Env Attack will be 0 ms by default in 1.1.18.
