### ISSUE TITLE
[1.1.16] WAV sample conversion broken

### ISSUE THREAD

**Issue by ArtFluids** [polyend/TrackerIssues#86]
In the latest update it says 

> Automatic sample conversion in the Sample Loader. All the previously unsupported .WAV files are now being converted to supported 44.1kHz 16bit mono PCM files automatically.

I tried this with several WAV files. They come out as glitchy messes that sound nothing like the original sample, maybe the data is being read incorrectly. The strange thing is that the sample preview in the loader sounds perfect, but once it's added to the project the file gets broken. 

Here's a famous tracker sample pack I was importing from: https://archive.org/details/AmigaSoundtrackerSamplePacksst-xx
If you try to import sounds from this pack you will get the same result as me. I included a zip of a selection in case you don't want to download the whole pack. This is happening with other WAV files as well, not just the ones in the pack.

Again, the preview in the loader sounds right, it's only when they are added to the project that they turn into glitchy messes.

[ST-01.zip](https://github.com/polyend/TrackerIssues/files/5274803/ST-01.zip)

Oh, also, another perhaps related issue: when I would load a broken sound into a slot, it would also overwrite instrument 01 with the same wave. Something about importing a broken sound would cause the first slot to also be replaced.

**Comment by wjakobczyk** [comment]
Thanks, the issue is related to low byte rate (8 bit mono) of the samples.
Though I can't reproduce the problem of overwriting first slot. Please report separately if it still happens in 1.1.18.
