### ISSUE TITLE
Missing FX effect (v1.3.0)

### ISSUE THREAD

**Issue by AmiDonk** [polyend/TrackerIssues#864]
Looks like some FX features have disappeared? Like "X - Break Pattern / xBRK" 

![Snap2](https://user-images.githubusercontent.com/22320763/110213902-545b3f80-7ea2-11eb-8d4a-72c9207e8f1a.png)
![Snap3](https://user-images.githubusercontent.com/22320763/110213905-558c6c80-7ea2-11eb-946a-6ff07c5c9079.jpg)

**Comment by Jacknametrouble** [comment]
Update to the newest beta.

**Comment by AmiDonk** [comment]
x still missing in latest beta.

**Comment by Jacknametrouble** [comment]
Alright, thank you for the report then. Yet, this isn't a missing Fx, just something which probably is not supposed to be there.

**Comment by ambv** [comment]
XBRK isn't a supported effect for Tracker projects. It's there for compatibility with MOD imports.
