### ISSUE TITLE
Option to automatically slice sample into slices of equal lengths

### ISSUE THREAD

**Issue by ThunderingMantis** [polyend/TrackerIssues#869]
A really useful feature would be the option to automatically slice a sample into slices of equal lengths (in addition to the existing options to manually add slice points, and detecting transients).

You could have this option selected, choose number of slices (e.g. 4, 8 or 16), hit a key to confirm, and you have your slices.

This would be really useful for breakbeats that have already been processed, or really any sample that matches the song tempo (because it's already been timestretched, for instance). It makes rearranging samples such as these REALLY fast. You can turn a loop into a drum kit this way too. There are so many possibilities.

The only workarounds I have found are manually adding every slice point (very time-consuming and not as accurate), or resampling every couple of steps of a sample that lasts 16 steps (but you fill up your sample slots very quickly).

Thanks for your consideration!

**Comment by talktogreg** [comment]
Hold SHIFT whilst in SLICE menu, its already there :)
