### ISSUE TITLE
I wish undo is possible in sample loader section.

### ISSUE THREAD

**Issue by modmodmodmod** [polyend/TrackerIssues#898]
If I can use undo even if accidentally delete an instrument while rearranging the instruments in sample loader section, it will be helpful.

**Comment by Just-Peter** [comment]
Is this a statement or a feature request? And please change 'ando' in 'undo'

**Comment by modmodmodmod** [comment]
I’m sorry, l rewrite it (this is just request).

**Comment by clickysteve** [comment]
This would be helpful.
