### ISSUE TITLE
[1.1.16] Tracker doesn't stay synced to midi clock, speeds up over time

### ISSUE THREAD

**Issue by splitradix** [polyend/TrackerIssues#90]
When "clock in" and "transport in" is set to "MIDI In jack", the Tracker starts approximately 14ms late, and then gradually speeds up over time to overtake the master midi clock.

After approximately 3 minutes running at 120pm the Tracker plays 139ms early.

* How often does this bug happen? Every time

* Does this bug happen in previous firmware versions? No. In 1.0.10 the Tracker also starts 14ms late but stays in sync with the midi clock (always 14ms late).

* Does this bug happen in every project? Yes.

**Comment by splitradix** [comment]
1.1.17 has fixed the Tracker speeding up bug.

**Comment by Jacknametrouble** [comment]
This has been fixed in the 1.1.17
