### ISSUE TITLE
/REQ/ Folder structure in Project Root Folder + sort options

### ISSUE THREAD

**Issue by notaprogrammer9** [polyend/TrackerIssues#919]
Request 1/
The ability to create and remove folders in the project root for better project managment

Request 2/
In project root having the ability to sort by:
- date created/saved
- name, type/name

🖤

**Comment by danapeks** [comment]
Yes please. Really not sure why this still isn't possible !

**Comment by charliekemp** [comment]
+1 This is definitely needed, my project folder is a mess
