### ISSUE TITLE
/REQ/ save-load instruments

### ISSUE THREAD

**Issue by notaprogrammer9** [polyend/TrackerIssues#920]
Request:

Having the ability to save and load instruments with custom parameter values, playback mode + slice markers etc

👌🏻

**Comment by bambrose** [comment]
There's already a request for this dating back to the early releases

**Comment by bambrose** [comment]
https://github.com/polyend/TrackerIssues/issues/641
https://github.com/polyend/TrackerIssues/issues/135
https://github.com/polyend/TrackerIssues/issues/875
all relate in one way or other

**Comment by pinkcell-niico** [comment]
Saving intruments, not just sample yes. :)

**Comment by Jacknametrouble** [comment]
This has been added in the newest 1.5b1 beta.
