### ISSUE TITLE
How to hook up Midi Keyboard to control tracker pads?

### ISSUE THREAD

**Issue by muhfugga** [polyend/TrackerIssues#927]
This is not so much as a issue or bug but just I cant figure out how to use a midi keyboard to trigger my Polyend Tracker pads. I have tried different settings in the configuration and I can't figure it out but also I'm not so good with midi lol. I have a midi cable going from the out of the keyboard to the in of the tracker.

**Comment by Jacknametrouble** [comment]
Need customer support, use > https://help.polyend.com/submit_ticket
