### ISSUE TITLE
[1.3.1] Samplerate  : 44117Hz

### ISSUE THREAD

**Issue by acidf2018** [polyend/TrackerIssues#929]
When you export to Wav (Master or stems), the Samplerate is 44117Hz

The bug happens every time and with every project.

![Sans titre](https://user-images.githubusercontent.com/42499666/112638802-ea4e0e80-8e3f-11eb-9ddb-9980dab98a27.png)

**Comment by birdydy** [comment]
This has been anwered here : #886
