### ISSUE TITLE
Open source the tracker code please.

### ISSUE THREAD

**Issue by accidentonacid** [polyend/TrackerIssues#945]
Hello friends,

I give credit where its due - to Polyend for realising such a amazing project. 
And massive, massive big up for manufacturing it locally in Poland.

my ramblings are as follows:

(a) the project is already on GitHub sort of, but why not go all the way and release the source under open source license or something?  Theres so many super smart people out there that has know how and could help out of pure love for hacking and thinkering.

(b) It just makes sense. What are your thoughts on this?

(c) What makes me the maddest is that as a consumer is that I don't really own the product and im not free to do whatever I want with it. (thanks bill gates aka the greatest dr. evil out there) If I have the code, the schematics to the product. I can fix it myself or die trying. I can work on the software and share it with the community. Knowing that most electronics produced basically goes to the fucking bin it's mind boggling.

So dear humans @ Polyend, i believe in you as a company to be the change you want to see in the music hardware industry! 
And this shit right here is the daddy of all feature requests! :)

Yours sincerely 

Autist

**Comment by tilllt** [comment]
I can totally understand why companies do NOT want to open source their work. But closing the issue here without any comment, a link to a similar question that has been answered before etc. is just not good communication.
