### ISSUE TITLE
Project snapshots/locks like on Maschine

### ISSUE THREAD

**Issue by brian3kb** [polyend/TrackerIssues#95]
On Maschine, entering lock mode, lets you change many parameters in the project, then exiting lock mode will revert back to the previous project state.

Snapshots can also be stored, and then the stored states can be morphed between over time.

This video demos it much better than my explanation, on a Maschine Jam controller - https://www.youtube.com/watch?v=hBQvq1Y9d9E

**Comment by piotr3500** [comment]
You can kind of do the same using Perform features.
