### ISSUE TITLE
Mutable Instruments Plaits synthesis modes

### ISSUE THREAD

**Issue by NoraCodes** [polyend/TrackerIssues#954]
This is kind of a silly one, perhaps, but: Tracker already uses the Mi-Verb, so there's clearly not a license issue with that code. I know Tracker is intended to be a sampling powerhouse more than anything, but it would be extremely cool if we could have some Plaits or Braids modes available for synthesis!

The UI for these would not, in my opinion, be so hard to make; each mode has only 3 parameters, so you could easily have 3 FX options for "timbre", "morph", and "harmonics", plus maybe one for "AUX crossfade" if you want to implement that, with corresponding envelope/LFO panes in the Instrument Parameters mode.

Again, I recognize that this is a long shot, and "this would take too much dev time to consider" or "there is not enough spare CPU time to do this consistently" are absolutely good answers, I just think it would be cool if it's possible, and it would take Tracker to a whole new level, as well as providing a significant competitive edge, especially with the release of the M8. Personally, I think the M8's software is superior, but its interface hardware has nothing on the Tracker.

Thanks so much for making such a wonderful instrument.

**Comment by theorize999** [comment]
I wouldn't say no to this. I'm guessing you nailed it with the whole can the CPU handle it thing though, but never hurts to ask and it would be pretty awesome.

**Comment by charliekemp** [comment]
This would be amazing if possible. I've been using Braids in M8 Headless and it works so well with this style of sequencing.

**Comment by Jacknametrouble** [comment]
Thank you for sharing your idea. This won't be possible due to the limited resources of the instrument.
