### ISSUE TITLE
quicker slice selection while editing start end time

### ISSUE THREAD

**Issue by x2db** [polyend/TrackerIssues#980]
I do appreciate the pads to play slices in 1.3.1 but while editing slices it would be great if I can select slice on the display by shift+pad. As of 1.3.1 I need to hit the slice button and arrow up to select the next slice and then I need to hit the start position button to start to tweak with jog.

**Comment by static-noise-PT** [comment]
I also would love to see that.

**Comment by fairchild670** [comment]
This would be a major time saver for me.
