### ISSUE TITLE
[1.3.1] iConnectivity mioXM cannot detect Polyend Tracker as USB device

### ISSUE THREAD

**Issue by angeloscalas** [polyend/TrackerIssues#986]
Hello,
this issue is pretty simple to riproduce: Tracker is not detected as USB device on every mioXM device.

I sent an email to iConnectivity that replied in this way:

"Hi, thanks for contacting us.

That list is user created as we couldn't own all the products in it. It's likely we were told it partially works.
After looking at it better Polyend send "CDC (serial) and Raw HID." which our USB-A host ports cannot accept.
It's really on both companies in some ways here. 
Polyend could write a firmware to not include that information and it would work OR we could attempt to try and take that data into our host ports which would be an effort on our part to make work.

I don't see that being possible form our side in a near future situation unfortunately. I've had conversations about a bunch of different items like conductive labs stuff and Polyend  stuff internally and we are trying to see if or when that might be possible ever."

Could be possible to introduce an option to disable sending send "CDC (serial) and Raw HID" on the Tracker?

Thanks for you great work. Please keep going. 

Cheers

**Comment by Jacknametrouble** [comment]
https://help.polyend.com/431975-My-iConnectivity-MIDI-USB-hub-is-not-recognising-my-Polyend-instrument-why
