### ISSUE TITLE
[v1.3.1] Having issues to rename tracks

### ISSUE THREAD

**Issue by LetsSeeIfWeSolveThis** [polyend/TrackerIssues#987]
Its all right when I press SHIFT on mixer's window, I can see the bottom of the mixer changing from ''mute'' to ''solo'' mode. 

But if I press _**SHIFT+REC**_, I can see the **_''Edit'' red-colored mode for a few hundredths of a second and it dissapears_**. If I try several times I'm able to access to the function. But is not consistent.

Not in previous versions. All projects.

**Comment by ambv** [comment]
It's just done with REC (without SHIFT) but I guess we can also make it work with Shift+REC.
