### ISSUE TITLE
Suggestion --> Copy Instruments samples back to the SD

### ISSUE THREAD

**Issue by anemlife** [polyend/TrackerIssues#992]
Could we get an option to copy/paste a sample from the instrument's list back to the SD?

I would like to process samples (chorus, etc...) and then copy them to a folder without having to resample, render, rename etc...
I think it would be a huge gain of time.

Thanks!

**Comment by theorize999** [comment]
This would be so useful

**Comment by Anexium** [comment]
Agreed, this would make the Tracker so much more versatile.

**Comment by Jacknametrouble** [comment]
Option to save instruments has been added in the newest 1.5b1 beta.
