### ISSUE TITLE
[1.3.1] Performance mode kills song mode

### ISSUE THREAD

**Issue by gordwithers** [polyend/TrackerIssues#995]
Start song with "play song"
click the Perform button
click the first black button to turn track 1 on for performance mode.
the song is now stuck in pattern mode instead of song mode - just keeps repeating the pattern in slot 1. 

This happens on my projects, and I've confirmed it happens on the Tim Koch sample project.

**Comment by gordwithers** [comment]
OK, having read the manual again, I see this is how it is supposed to work, so closing this. 

It wasn't intuitive to me that it would work this way but I can see how this makes sense.

**Comment by ambv** [comment]
Fixed in 1.4
