### ISSUE TITLE
Allow me to see list of patterns where an instrument is used 

### ISSUE THREAD

**Issue by x2db** [polyend/TrackerIssues#996]
I constantly change pitch, effects, distortion, volume etc on an instrument that is being used in other patterns. That messes other patterns. Especially, if I have more instruments than tracks (obvious we have 40+ slots for instruments)  

**Request:**

Somewhere in the Instrument parameter page (next to resonance) add a list of patterns where the instrument is used, so I know if I change instrument setting then I'm messing with all those listed patterns.   

Even better I could hit enter while on this pattern list and JUMP to that pattern.

Yes I know I can duplicate the instrument so that each pattern has a "new" instance of an instrument but that is counter productive. Most of user-friendliness of this beautiful machine is in quick navigation and this feature would add to workflow efficiency

**Comment by Jacknametrouble** [comment]
Thank you for your feedback.
