### ISSUE TITLE
Pitch manipulation in Instrument Parameters.

### ISSUE THREAD

**Issue by Aisjam** [polyend/TrackerIssues#999]
I would like to be able manipulate the pitch of my sample via an lfo or envelope similar to the other tabs in the Instrument parameters. It opens up a more options in sound design.

Also a nice plus would be an vibrato FX command similar to the lfo FX manipulators.

**Comment by theorize999** [comment]
If nothing else at least in wavetable mode, with resampling and a couple of enhancements to the synth engine PT could be a sound design powerhouse, layering, filtering, resampling and then BOOM! a new sample exists where there was none and now it can be tracked. There is serious potential.
